The thermochemical analysis of the Molecule:                     C8H6

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000       0.0000000000       0.5854390000       0.0000000000
  C     6   12.00000      -1.2044140000      -0.1195570000       0.0000000000
  C     6   12.00000       1.2044140000      -0.1195570000       0.0000000000
  C     6   12.00000      -1.2005740000      -1.5035680000       0.0000000000
  C     6   12.00000       1.2005740000      -1.5035680000       0.0000000000
  C     6   12.00000       0.0000000000      -2.1985370000       0.0000000000
  H     1    1.00782      -2.1379880000       0.4274750000       0.0000000000
  H     1    1.00782       2.1379880000       0.4274750000       0.0000000000
  H     1    1.00782      -2.1395290000      -2.0422520000       0.0000000000
  H     1    1.00782       2.1395290000      -2.0422520000       0.0000000000
  H     1    1.00782       0.0000000000      -3.2810700000       0.0000000000
  C     6   12.00000       0.0000000000       2.0162150000       0.0000000000
  C     6   12.00000       0.0000000000       3.2151450000       0.0000000000
  H     1    1.00782      -0.0000010000       4.2785390000       0.0000000000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           1
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          36
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
         -0.00000001      0.02170171      0.00000000

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x       327.56919         0.00000         0.00000
    y         0.00000        87.84811         0.00000
    z         0.00000         0.00000       415.41730

              Principal moments of inertia (amu*A**2): 
             327.56919000          87.84811000         415.41730000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation              264121.07506       The ln(Q)   12.48416

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       27.78942  (cal/mol*K)    116.27094    (J/mol*K)         0.00004429  (hartree/K)
  G rotation       -7.39669   (kcal/mol)    -30.94774     (kJ/mol)        -0.01178736    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:   102.04695   amu

              *****      Translation thermodynamic functions     ******

  Q translation            40518679.77610       The ln(Q)   17.51727
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       39.77846  (cal/mol*K)    166.43307    (J/mol*K)         0.00006339  (hartree/K)
  G translation      -10.37873   (kcal/mol)    -43.42462     (kJ/mol)        -0.01653955    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   36
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   36


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      143.482         140.325         yes       2.03275    0.201        0.615        2.799       -0.220        1.913
  2      162.077         158.512         yes       1.87045    0.227        0.621        2.567       -0.144        1.893
  3      374.161         365.929         yes       1.20633    0.523        0.739        1.097        0.412        1.542
  4      415.546         406.404         yes       1.16373    0.581        0.771        0.939        0.491        1.456
  5      476.153         465.677         yes       1.11819    0.666        0.823        0.750        0.600        1.326
  6      546.360         534.340         yes       1.08212    0.764        0.889        0.578        0.717        1.174
  7      563.485         551.088         yes       1.07526    0.788        0.906        0.542        0.745        1.137
  8      642.188         628.060         yes       1.05073    0.898        0.989        0.404        0.869        0.973
  9      677.302         662.401         yes       1.04265    0.947        1.028        0.354        0.922        0.903
 10      711.362         695.712         yes       1.03609    0.995        1.066        0.311        0.974        0.837
 11      716.287         700.528         yes       1.03523    1.001        1.072        0.305        0.981        0.828
 12      783.365         766.131         yes       1.02543    1.095        1.151        0.237        1.080        0.708
 13      791.259         773.852         yes       1.02447    1.106        1.160        0.230        1.092        0.695
 14      873.463         854.247         yes       1.01647    1.221        1.261        0.167        1.212        0.565
 15      957.003         935.949         yes       1.01105    1.338        1.368        0.121        1.331        0.453
 16      999.622         977.631         yes       1.00902    1.398        1.423        0.102        1.392        0.402
 17     1012.993         990.707         yes       1.00846    1.416        1.440        0.097        1.411        0.388
 18     1027.941        1005.326         yes       1.00788    1.437        1.460        0.092        1.433        0.371
 19     1062.875        1039.492         yes       1.00667    1.486        1.506        0.080        1.482        0.336
 20     1113.977        1089.470         yes       1.00524    1.557        1.574        0.065        1.554        0.289
 21     1190.319        1164.132         yes       1.00365    1.664        1.676        0.048        1.662        0.229
 22     1211.546        1184.892         yes       1.00330    1.694        1.705        0.044        1.692        0.215
 23     1234.815        1207.649         yes       1.00295    1.726        1.737        0.040        1.725        0.200
 24     1318.805        1289.791         yes       1.00199    1.844        1.851        0.028        1.843        0.153
 25     1361.123        1331.178         yes       1.00163    1.903        1.909        0.024        1.902        0.133
 26     1492.376        1459.543         yes       1.00087    2.087        2.090        0.014        2.086        0.086
 27     1542.139        1508.211         yes       1.00069    2.156        2.159        0.011        2.156        0.073
 28     1648.237        1611.976         yes       1.00042    2.304        2.306        0.007        2.304        0.050
 29     1678.241        1641.320         yes       1.00036    2.346        2.348        0.006        2.346        0.045
 30     2244.904        2195.516         yes       1.00003    3.139        3.139        0.001        3.139        0.006
 31     3196.286        3125.968         yes       1.00000    4.469        4.469        0.000        4.469        0.000
 32     3205.792        3135.265         yes       1.00000    4.482        4.482        0.000        4.482        0.000
 33     3214.632        3143.910         yes       1.00000    4.494        4.494        0.000        4.494        0.000
 34     3222.579        3151.683         yes       1.00000    4.506        4.506        0.000        4.506        0.000
 35     3227.432        3156.428         yes       1.00000    4.512        4.512        0.000        4.512        0.000
 36     3479.677        3403.124         yes       1.00000    4.865        4.865        0.000        4.865        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   9.28945       The ln(Q)    2.22888
    H vibration       70.11216   (kcal/mol)    293.34927     (kJ/mol)         0.11173073    (hartree)
    U vibration       70.11216   (kcal/mol)    293.34927     (kJ/mol)         0.11173073    (hartree)
           ZPE        67.83656   (kcal/mol)    283.82819     (kJ/mol)         0.10810435    (hartree)
    S vibration       12.06162  (cal/mol*K)     50.46582    (J/mol*K)         0.00001922  (hartree/K)
   Cv vibration       19.38321  (cal/mol*K)     81.09933    (J/mol*K)         0.00003089  (hartree/K)
    G vibration       66.51599   (kcal/mol)    278.30288     (kJ/mol)         0.10599987    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total      99414158769329.20312       The ln(Q)   37.26343
        H total       72.48210   (kcal/mol)    303.26511     (kJ/mol)         0.11550747    (hartree)
        U total       71.88961   (kcal/mol)    300.78615     (kJ/mol)         0.11456329    (hartree)
       Cv total       25.34483  (cal/mol*K)    106.04275    (J/mol*K)         0.00004039  (hartree/K)
           ZPE        67.83656   (kcal/mol)    283.82819     (kJ/mol)         0.10810435    (hartree)
        S total       79.62950  (cal/mol*K)    333.16983    (J/mol*K)         0.00012690  (hartree/K)
        G total       49.33305   (kcal/mol)    206.40948     (kJ/mol)         0.07861715    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.11456329 (hartree)
                       Thermal correction to Enthalpy :   0.11550747 
              Thermal correction to Gibbs Free Energy :   0.07767296 (hartree)
              ZPE correction to the Electronic Energy :   0.10810435 (hartree)


