The thermochemical analysis of the Molecule:                     C3H6

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000       0.0000000000       0.8659750000       0.0000000000
  C     6   12.00000      -0.7499560000      -0.4329870000       0.0000000000
  C     6   12.00000       0.7499560000      -0.4329870000       0.0000000000
  H     1    1.00782       0.0000000000       1.4518170000       0.9091500000
  H     1    1.00782       0.0000000000       1.4518170000      -0.9091500000
  H     1    1.00782      -1.2573100000      -0.7259090000       0.9091500000
  H     1    1.00782      -1.2573100000      -0.7259090000      -0.9091500000
  H     1    1.00782       1.2573100000      -0.7259090000       0.9091500000
  H     1    1.00782       1.2573100000      -0.7259090000      -0.9091500000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           6
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          21
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
          0.00000000      0.00000024      0.00000000

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x        24.86935         0.00000         0.00000
    y         0.00000        24.86934         0.00000
    z         0.00000         0.00000        39.74243

              Principal moments of inertia (amu*A**2): 
              24.86935000          24.86934000          39.74243000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation                1996.10457       The ln(Q)    7.59895

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       18.08150  (cal/mol*K)     75.65299    (J/mol*K)         0.00002881  (hartree/K)
  G rotation       -4.50227   (kcal/mol)    -18.83750     (kJ/mol)        -0.00717482    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    42.04695   amu

              *****      Translation thermodynamic functions     ******

  Q translation            10716599.25035       The ln(Q)   16.18730
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       37.13553  (cal/mol*K)    155.37508    (J/mol*K)         0.00005918  (hartree/K)
  G translation       -9.59075   (kcal/mol)    -40.12768     (kJ/mol)        -0.01528381    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   21
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   21


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      753.867         737.282         yes       1.02934    1.054        1.116        0.265        1.037        0.760
  2      753.867         737.282         yes       1.02934    1.054        1.116        0.265        1.037        0.760
  3      868.973         849.856         yes       1.01683    1.215        1.256        0.170        1.205        0.572
  4      899.979         880.179         yes       1.01451    1.258        1.295        0.151        1.250        0.528
  5      899.979         880.179         yes       1.01451    1.258        1.295        0.151        1.250        0.528
  6     1066.872        1043.401         yes       1.00655    1.492        1.511        0.078        1.488        0.332
  7     1066.872        1043.401         yes       1.00655    1.492        1.511        0.078        1.488        0.332
  8     1102.690        1078.430         yes       1.00552    1.542        1.559        0.068        1.538        0.299
  9     1160.275        1134.749         yes       1.00420    1.622        1.636        0.054        1.620        0.252
 10     1218.308        1191.506         yes       1.00319    1.703        1.714        0.043        1.701        0.210
 11     1218.308        1191.506         yes       1.00319    1.703        1.714        0.043        1.701        0.210
 12     1221.706        1194.828         yes       1.00314    1.708        1.719        0.042        1.706        0.208
 13     1480.514        1447.942         yes       1.00092    2.070        2.074        0.015        2.069        0.090
 14     1480.514        1447.942         yes       1.00092    2.070        2.074        0.015        2.069        0.090
 15     1532.648        1498.929         yes       1.00072    2.143        2.146        0.012        2.142        0.075
 16     3154.344        3084.948         yes       1.00000    4.410        4.410        0.000        4.410        0.000
 17     3154.344        3084.948         yes       1.00000    4.410        4.410        0.000        4.410        0.000
 18     3163.454        3093.858         yes       1.00000    4.423        4.423        0.000        4.423        0.000
 19     3234.074        3162.925         yes       1.00000    4.522        4.522        0.000        4.522        0.000
 20     3234.074        3162.925         yes       1.00000    4.522        4.522        0.000        4.522        0.000
 21     3254.782        3183.176         yes       1.00000    4.551        4.551        0.000        4.551        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   1.14817       The ln(Q)    0.13817
    H vibration       50.57173   (kcal/mol)    211.59212     (kJ/mol)         0.08059111    (hartree)
    U vibration       50.57173   (kcal/mol)    211.59212     (kJ/mol)         0.08059111    (hartree)
           ZPE        50.22113   (kcal/mol)    210.12521     (kJ/mol)         0.08003239    (hartree)
    S vibration        1.45049  (cal/mol*K)      6.06884    (J/mol*K)         0.00000231  (hartree/K)
   Cv vibration        5.24589  (cal/mol*K)     21.94879    (J/mol*K)         0.00000836  (hartree/K)
    G vibration       50.13927   (kcal/mol)    209.78270     (kJ/mol)         0.07990194    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total         24561042462.70505       The ln(Q)   32.51278
        H total       52.94167   (kcal/mol)    221.50796     (kJ/mol)         0.08436785    (hartree)
        U total       52.34919   (kcal/mol)    219.02900     (kJ/mol)         0.08342366    (hartree)
       Cv total       11.20751  (cal/mol*K)     46.89221    (J/mol*K)         0.00001786  (hartree/K)
           ZPE        50.22113   (kcal/mol)    210.12521     (kJ/mol)         0.08003239    (hartree)
        S total       56.66752  (cal/mol*K)    237.09691    (J/mol*K)         0.00009031  (hartree/K)
        G total       36.63874   (kcal/mol)    153.29648     (kJ/mol)         0.05838749    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.08342366 (hartree)
                       Thermal correction to Enthalpy :   0.08436785 
              Thermal correction to Gibbs Free Energy :   0.05744331 (hartree)
              ZPE correction to the Electronic Energy :   0.08003239 (hartree)


