The thermochemical analysis of the Molecule:                     C6H6

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000       0.0000000000       1.3872980000       0.0000000000
  H     1    1.00782       0.0000000000       2.4701630000       0.0000000000
  C     6   12.00000       1.2014360000       0.6936490000       0.0000000000
  H     1    1.00782       2.1392240000       1.2350820000       0.0000000000
  C     6   12.00000       1.2014360000      -0.6936490000       0.0000000000
  H     1    1.00782       2.1392240000      -1.2350820000       0.0000000000
  C     6   12.00000       0.0000000000      -1.3872980000       0.0000000000
  H     1    1.00782       0.0000000000      -2.4701630000       0.0000000000
  C     6   12.00000      -1.2014360000      -0.6936490000       0.0000000000
  H     1    1.00782      -2.1392240000      -1.2350820000       0.0000000000
  C     6   12.00000      -1.2014360000       0.6936490000       0.0000000000
  H     1    1.00782      -2.1392240000       1.2350820000       0.0000000000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):          12
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          30
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
         -0.00000000     -0.00000000      0.00000000

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x        87.73380        -0.00000         0.00000
    y        -0.00000        87.73388         0.00000
    z         0.00000         0.00000       175.46769

              Principal moments of inertia (amu*A**2): 
              87.73380000          87.73388000         175.46769000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation                7398.22443       The ln(Q)    8.90900

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       20.68482  (cal/mol*K)     86.54530    (J/mol*K)         0.00003296  (hartree/K)
  G rotation       -5.27845   (kcal/mol)    -22.08504     (kJ/mol)        -0.00841174    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    78.04695   amu

              *****      Translation thermodynamic functions     ******

  Q translation            27101239.03245       The ln(Q)   17.11509
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       38.97924  (cal/mol*K)    163.08913    (J/mol*K)         0.00006212  (hartree/K)
  G translation      -10.14045   (kcal/mol)    -42.42762     (kJ/mol)        -0.01615981    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   30
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   30


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      416.158         407.003         yes       1.16318    0.582        0.772        0.937        0.492        1.455
  2      416.158         407.003         yes       1.16318    0.582        0.772        0.937        0.492        1.455
  3      627.162         613.364         yes       1.05466    0.877        0.973        0.427        0.845        1.004
  4      627.162         613.364         yes       1.05466    0.877        0.973        0.427        0.845        1.004
  5      697.396         682.053         yes       1.03864    0.975        1.050        0.328        0.953        0.864
  6      726.468         710.485         yes       1.03352    1.016        1.084        0.294        0.996        0.809
  7      878.857         859.522         yes       1.01605    1.229        1.268        0.164        1.219        0.558
  8      878.857         859.522         yes       1.01605    1.229        1.268        0.164        1.219        0.558
  9      996.512         974.589         yes       1.00915    1.393        1.419        0.104        1.388        0.406
 10      996.512         974.589         yes       1.00915    1.393        1.419        0.104        1.388        0.406
 11     1015.975         993.624         yes       1.00834    1.420        1.444        0.096        1.416        0.384
 12     1029.767        1007.112         yes       1.00781    1.440        1.462        0.091        1.435        0.369
 13     1031.064        1008.380         yes       1.00776    1.442        1.464        0.090        1.437        0.368
 14     1073.110        1049.501         yes       1.00636    1.500        1.519        0.077        1.497        0.326
 15     1073.110        1049.501         yes       1.00636    1.500        1.519        0.077        1.497        0.326
 16     1179.741        1153.787         yes       1.00383    1.649        1.662        0.050        1.647        0.237
 17     1209.099        1182.498         yes       1.00334    1.690        1.702        0.044        1.688        0.217
 18     1209.099        1182.498         yes       1.00334    1.690        1.702        0.044        1.688        0.217
 19     1339.107        1309.647         yes       1.00180    1.872        1.879        0.026        1.871        0.143
 20     1390.013        1359.433         yes       1.00142    1.943        1.949        0.021        1.943        0.121
 21     1529.241        1495.598         yes       1.00073    2.138        2.141        0.012        2.138        0.076
 22     1529.241        1495.598         yes       1.00073    2.138        2.141        0.012        2.138        0.076
 23     1669.411        1632.684         yes       1.00038    2.334        2.336        0.007        2.334        0.047
 24     1669.411        1632.684         yes       1.00038    2.334        2.336        0.007        2.334        0.047
 25     3188.011        3117.875         yes       1.00000    4.457        4.457        0.000        4.457        0.000
 26     3197.824        3127.472         yes       1.00000    4.471        4.471        0.000        4.471        0.000
 27     3197.824        3127.472         yes       1.00000    4.471        4.471        0.000        4.471        0.000
 28     3213.914        3143.208         yes       1.00000    4.493        4.493        0.000        4.493        0.000
 29     3213.914        3143.208         yes       1.00000    4.493        4.493        0.000        4.493        0.000
 30     3224.307        3153.373         yes       1.00000    4.508        4.508        0.000        4.508        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   1.78983       The ln(Q)    0.58212
    H vibration       63.14753   (kcal/mol)    264.20926     (kJ/mol)         0.10063190    (hartree)
    U vibration       63.14753   (kcal/mol)    264.20926     (kJ/mol)         0.10063190    (hartree)
           ZPE        62.13869   (kcal/mol)    259.98829     (kJ/mol)         0.09902422    (hartree)
    S vibration        4.54045  (cal/mol*K)     18.99726    (J/mol*K)         0.00000724  (hartree/K)
   Cv vibration       11.47290  (cal/mol*K)     48.00260    (J/mol*K)         0.00001828  (hartree/K)
    G vibration       61.79379   (kcal/mol)    258.54523     (kJ/mol)         0.09847459    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total        358863654914.57190       The ln(Q)   34.81230
        H total       65.51747   (kcal/mol)    274.12510     (kJ/mol)         0.10440864    (hartree)
        U total       64.92499   (kcal/mol)    271.64614     (kJ/mol)         0.10346446    (hartree)
       Cv total       17.43452  (cal/mol*K)     72.94602    (J/mol*K)         0.00002778  (hartree/K)
           ZPE        62.13869   (kcal/mol)    259.98829     (kJ/mol)         0.09902422    (hartree)
        S total       64.20452  (cal/mol*K)    268.63169    (J/mol*K)         0.00010232  (hartree/K)
        G total       46.96738   (kcal/mol)    196.51152     (kJ/mol)         0.07484722    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.10346446 (hartree)
                       Thermal correction to Enthalpy :   0.10440864 
              Thermal correction to Gibbs Free Energy :   0.07390303 (hartree)
              ZPE correction to the Electronic Energy :   0.09902422 (hartree)


