The thermochemical analysis of the Molecule:                    C4H10

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000       0.7011980000       1.8214010000       0.0000000000
  C     6   12.00000       0.7011980000       0.2986750000       0.0000000000
  H     1    1.00782       1.7163080000       2.2217490000       0.0000000000
  H     1    1.00782       0.1878470000       2.2127500000       0.8815300000
  H     1    1.00782       0.1878470000       2.2127500000      -0.8815300000
  C     6   12.00000      -0.7011980000      -0.2986750000       0.0000000000
  H     1    1.00782       1.2470680000      -0.0686200000       0.8750480000
  H     1    1.00782       1.2470680000      -0.0686200000      -0.8750480000
  C     6   12.00000      -0.7011980000      -1.8214010000       0.0000000000
  H     1    1.00782      -1.2470680000       0.0686200000       0.8750480000
  H     1    1.00782      -1.2470680000       0.0686200000      -0.8750480000
  H     1    1.00782      -1.7163080000      -2.2217490000       0.0000000000
  H     1    1.00782      -0.1878470000      -2.2127500000       0.8815300000
  H     1    1.00782      -0.1878470000      -2.2127500000      -0.8815300000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           2
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          36
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
         -0.00000000      0.00000000      0.00000000

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x       117.68738       -44.69499         0.00000
    y       -44.69499        42.16925         0.00000
    z         0.00000         0.00000       147.41762

              Principal moments of inertia (amu*A**2): 
             138.43805000          21.41858000         147.41762000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation               25252.87212       The ln(Q)   10.13670

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       23.12452  (cal/mol*K)     96.75298    (J/mol*K)         0.00003685  (hartree/K)
  G rotation       -6.00585   (kcal/mol)    -25.12846     (kJ/mol)        -0.00957092    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    58.07825   amu

              *****      Translation thermodynamic functions     ******

  Q translation            17397046.55131       The ln(Q)   16.67181
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       38.09835  (cal/mol*K)    159.40349    (J/mol*K)         0.00006071  (hartree/K)
  G translation       -9.87781   (kcal/mol)    -41.32875     (kJ/mol)        -0.01574128    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   36
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   36


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      120.288         117.642         yes       2.30854    0.168        0.608        3.139       -0.328        1.935
  2      225.835         220.867         yes       1.52542    0.316        0.648        1.952        0.066        1.809
  3      261.655         255.899         yes       1.41018    0.366        0.666        1.690        0.162        1.753
  4      264.785         258.960         yes       1.40174    0.370        0.668        1.669        0.170        1.748
  5      433.357         423.823         yes       1.14857    0.606        0.786        0.879        0.524        1.418
  6      743.640         727.280         yes       1.03083    1.040        1.104        0.275        1.022        0.778
  7      821.034         802.971         yes       1.02120    1.148        1.197        0.205        1.135        0.646
  8      855.067         836.256         yes       1.01799    1.195        1.239        0.180        1.185        0.593
  9      972.098         950.712         yes       1.01028    1.359        1.387        0.114        1.353        0.434
 10      990.549         968.757         yes       1.00941    1.385        1.411        0.106        1.379        0.413
 11     1036.927        1014.115         yes       1.00755    1.450        1.472        0.088        1.445        0.362
 12     1085.639        1061.755         yes       1.00599    1.518        1.536        0.073        1.514        0.314
 13     1180.508        1154.537         yes       1.00382    1.650        1.663        0.050        1.648        0.237
 14     1215.953        1189.202         yes       1.00323    1.700        1.711        0.043        1.698        0.212
 15     1297.479        1268.935         yes       1.00220    1.814        1.822        0.031        1.813        0.164
 16     1330.294        1301.028         yes       1.00188    1.860        1.867        0.027        1.859        0.148
 17     1340.110        1310.628         yes       1.00179    1.874        1.880        0.026        1.873        0.143
 18     1408.010        1377.034         yes       1.00130    1.969        1.974        0.020        1.968        0.114
 19     1419.647        1388.414         yes       1.00123    1.985        1.990        0.019        1.984        0.110
 20     1420.688        1389.433         yes       1.00123    1.986        1.991        0.019        1.986        0.110
 21     1494.869        1461.981         yes       1.00086    2.090        2.094        0.014        2.089        0.086
 22     1496.474        1463.551         yes       1.00086    2.092        2.096        0.014        2.092        0.085
 23     1502.423        1469.370         yes       1.00083    2.101        2.104        0.013        2.100        0.083
 24     1504.236        1471.143         yes       1.00083    2.103        2.107        0.013        2.103        0.083
 25     1508.740        1475.548         yes       1.00081    2.109        2.113        0.013        2.109        0.082
 26     1515.201        1481.867         yes       1.00078    2.118        2.122        0.013        2.118        0.080
 27     3033.201        2966.471         yes       1.00000    4.241        4.241        0.000        4.241        0.000
 28     3040.768        2973.871         yes       1.00000    4.251        4.251        0.000        4.251        0.000
 29     3045.035        2978.044         yes       1.00000    4.257        4.257        0.000        4.257        0.000
 30     3045.906        2978.896         yes       1.00000    4.259        4.259        0.000        4.259        0.000
 31     3058.912        2991.616         yes       1.00000    4.277        4.277        0.000        4.277        0.000
 32     3081.213        3013.426         yes       1.00000    4.308        4.308        0.000        4.308        0.000
 33     3114.638        3046.116         yes       1.00000    4.355        4.355        0.000        4.355        0.000
 34     3118.155        3049.555         yes       1.00000    4.360        4.360        0.000        4.360        0.000
 35     3122.863        3054.160         yes       1.00000    4.366        4.366        0.000        4.366        0.000
 36     3123.596        3054.877         yes       1.00000    4.367        4.367        0.000        4.367        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   9.04971       The ln(Q)    2.20273
    H vibration       83.29284   (kcal/mol)    348.49723     (kJ/mol)         0.13273546    (hartree)
    U vibration       83.29284   (kcal/mol)    348.49723     (kJ/mol)         0.13273546    (hartree)
           ZPE        81.41231   (kcal/mol)    340.62910     (kJ/mol)         0.12973866    (hartree)
    S vibration       10.68460  (cal/mol*K)     44.70438    (J/mol*K)         0.00001703  (hartree/K)
   Cv vibration       13.94024  (cal/mol*K)     58.32595    (J/mol*K)         0.00002222  (hartree/K)
    G vibration       80.10722   (kcal/mol)    335.16862     (kJ/mol)         0.12765887    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total       3975766910298.16064       The ln(Q)   35.54635
        H total       85.66278   (kcal/mol)    358.41307     (kJ/mol)         0.13651220    (hartree)
        U total       85.07029   (kcal/mol)    355.93411     (kJ/mol)         0.13556802    (hartree)
       Cv total       19.90186  (cal/mol*K)     83.26937    (J/mol*K)         0.00003172  (hartree/K)
           ZPE        81.41231   (kcal/mol)    340.62910     (kJ/mol)         0.12973866    (hartree)
        S total       71.90747  (cal/mol*K)    300.86085    (J/mol*K)         0.00011459  (hartree/K)
        G total       64.81605   (kcal/mol)    271.19036     (kJ/mol)         0.10329086    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.13556802 (hartree)
                       Thermal correction to Enthalpy :   0.13651220 
              Thermal correction to Gibbs Free Energy :   0.10234668 (hartree)
              ZPE correction to the Electronic Energy :   0.12973866 (hartree)


