The thermochemical analysis of the Molecule:                     C4H6

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000       0.0000000000       0.0000000000       0.5992480000
  C     6   12.00000       0.0000000000       0.0000000000      -0.5992480000
  C     6   12.00000       0.0000000000       0.0000000000      -2.0565020000
  H     1    1.00782       0.0000000000       1.0195190000      -2.4458330000
  H     1    1.00782      -0.8829290000      -0.5097590000      -2.4458330000
  H     1    1.00782       0.8829290000      -0.5097590000      -2.4458330000
  C     6   12.00000       0.0000000000       0.0000000000       2.0565020000
  H     1    1.00782       0.0000000000       1.0195190000       2.4458330000
  H     1    1.00782       0.8829290000      -0.5097590000       2.4458330000
  H     1    1.00782      -0.8829290000      -0.5097590000       2.4458330000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           6
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          24
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
          0.00000000      0.00000004      0.00000000

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x       149.43528         0.00000         0.00000
    y         0.00000       149.43528         0.00000
    z         0.00000         0.00000         6.28531

              Principal moments of inertia (amu*A**2): 
               6.28531000         149.43528000         149.43528000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation                4769.88881       The ln(Q)    8.47008

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       19.81261  (cal/mol*K)     82.89594    (J/mol*K)         0.00003157  (hartree/K)
  G rotation       -5.01840   (kcal/mol)    -20.99698     (kJ/mol)        -0.00799732    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    54.04695   amu

              *****      Translation thermodynamic functions     ******

  Q translation            15617518.49231       The ln(Q)   16.56390
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       37.88392  (cal/mol*K)    158.50630    (J/mol*K)         0.00006037  (hartree/K)
  G translation       -9.81388   (kcal/mol)    -41.06125     (kJ/mol)        -0.01563939    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   24
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   24


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1       24.127          23.596         yes       9.29161    0.034        0.593        6.306       -1.287        1.985
  2      204.232         199.739         yes       1.61659    0.286        0.638        2.136        0.001        1.840
  3      204.431         199.934         yes       1.61565    0.286        0.638        2.134        0.002        1.840
  4      416.900         407.728         yes       1.16252    0.583        0.772        0.935        0.494        1.453
  5      417.018         407.844         yes       1.16241    0.583        0.772        0.934        0.494        1.453
  6      730.855         714.776         yes       1.03281    1.022        1.089        0.289        1.003        0.801
  7     1053.800        1030.616         yes       1.00697    1.473        1.494        0.083        1.469        0.345
  8     1053.818        1030.634         yes       1.00697    1.473        1.494        0.083        1.469        0.345
  9     1068.100        1044.602         yes       1.00651    1.493        1.513        0.078        1.489        0.331
 10     1068.114        1044.616         yes       1.00651    1.493        1.513        0.078        1.490        0.331
 11     1177.511        1151.605         yes       1.00387    1.646        1.659        0.050        1.644        0.239
 12     1420.677        1389.422         yes       1.00123    1.986        1.991        0.019        1.986        0.110
 13     1421.744        1390.465         yes       1.00122    1.988        1.993        0.019        1.987        0.109
 14     1485.622        1452.938         yes       1.00090    2.077        2.081        0.014        2.077        0.088
 15     1485.622        1452.939         yes       1.00090    2.077        2.081        0.014        2.077        0.088
 16     1485.673        1452.988         yes       1.00090    2.077        2.081        0.014        2.077        0.088
 17     1485.674        1452.989         yes       1.00090    2.077        2.081        0.014        2.077        0.088
 18     2396.753        2344.024         yes       1.00001    3.351        3.351        0.000        3.351        0.003
 19     3054.487        2987.288         yes       1.00000    4.271        4.271        0.000        4.271        0.000
 20     3055.053        2987.842         yes       1.00000    4.271        4.271        0.000        4.271        0.000
 21     3124.874        3056.127         yes       1.00000    4.369        4.369        0.000        4.369        0.000
 22     3124.880        3056.132         yes       1.00000    4.369        4.369        0.000        4.369        0.000
 23     3125.607        3056.843         yes       1.00000    4.370        4.370        0.000        4.370        0.000
 24     3125.612        3056.849         yes       1.00000    4.370        4.370        0.000        4.370        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                  35.13967       The ln(Q)    3.55933
    H vibration       53.85260   (kcal/mol)    225.31929     (kJ/mol)         0.08581951    (hartree)
    U vibration       53.85260   (kcal/mol)    225.31929     (kJ/mol)         0.08581951    (hartree)
           ZPE        52.02574   (kcal/mol)    217.67571     (kJ/mol)         0.08290822    (hartree)
    S vibration       13.20044  (cal/mol*K)     55.23065    (J/mol*K)         0.00002104  (hartree/K)
   Cv vibration       11.53938  (cal/mol*K)     48.28076    (J/mol*K)         0.00001839  (hartree/K)
    G vibration       49.91689   (kcal/mol)    208.85227     (kJ/mol)         0.07954756    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total       2617688117324.69727       The ln(Q)   36.68714
        H total       56.22255   (kcal/mol)    235.23513     (kJ/mol)         0.08959625    (hartree)
        U total       55.63006   (kcal/mol)    232.75617     (kJ/mol)         0.08865206    (hartree)
       Cv total       17.50100  (cal/mol*K)     73.22418    (J/mol*K)         0.00002789  (hartree/K)
           ZPE        52.02574   (kcal/mol)    217.67571     (kJ/mol)         0.08290822    (hartree)
        S total       70.89696  (cal/mol*K)    296.63289    (J/mol*K)         0.00011298  (hartree/K)
        G total       35.67710   (kcal/mol)    149.27299     (kJ/mol)         0.05685503    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.08865206 (hartree)
                       Thermal correction to Enthalpy :   0.08959625 
              Thermal correction to Gibbs Free Energy :   0.05591084 (hartree)
              ZPE correction to the Electronic Energy :   0.08290822 (hartree)


