The thermochemical analysis of the Molecule:                     C3H6

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000       0.0000000000       0.4722250000       0.0000000000
  C     6   12.00000       1.2841380000       0.1507780000       0.0000000000
  H     1    1.00782       2.0577450000       0.9083170000       0.0000000000
  H     1    1.00782       1.6084370000      -0.8845710000       0.0000000000
  H     1    1.00782      -0.2765260000       1.5234750000       0.0000000000
  C     6   12.00000      -1.1315740000      -0.5043720000       0.0000000000
  H     1    1.00782      -0.7701250000      -1.5334480000       0.0000000000
  H     1    1.00782      -1.7674550000      -0.3627800000       0.8776980000
  H     1    1.00782      -1.7674550000      -0.3627800000      -0.8776980000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           1
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          21
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
          0.02160029      0.01679587      0.00000000

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x        14.13672       -11.66483         0.00000
    y       -11.66483        50.53303         0.00000
    z         0.00000         0.00000        61.56423

              Principal moments of inertia (amu*A**2): 
              10.71912000          53.95064000          61.56423000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation               14414.01676       The ln(Q)    9.57596

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       22.01021  (cal/mol*K)     92.09073    (J/mol*K)         0.00003508  (hartree/K)
  G rotation       -5.67362   (kcal/mol)    -23.73841     (kJ/mol)        -0.00904148    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    42.04695   amu

              *****      Translation thermodynamic functions     ******

  Q translation            10716599.25035       The ln(Q)   16.18730
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       37.13553  (cal/mol*K)    155.37508    (J/mol*K)         0.00005918  (hartree/K)
  G translation       -9.59075   (kcal/mol)    -40.12768     (kJ/mol)        -0.01528381    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   21
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   21


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      201.152         196.726         yes       1.63131    0.281        0.636        2.164       -0.009        1.844
  2      435.078         425.506         yes       1.14719    0.608        0.787        0.873        0.527        1.415
  3      596.556         583.432         yes       1.06369    0.834        0.940        0.479        0.797        1.067
  4      936.817         916.207         yes       1.01216    1.310        1.342        0.131        1.303        0.478
  5      955.504         934.482         yes       1.01113    1.336        1.366        0.122        1.329        0.455
  6      960.891         939.752         yes       1.01084    1.343        1.373        0.119        1.337        0.448
  7     1036.438        1013.636         yes       1.00757    1.449        1.471        0.089        1.445        0.363
  8     1081.437        1057.646         yes       1.00611    1.512        1.530        0.074        1.508        0.318
  9     1201.074        1174.651         yes       1.00347    1.679        1.691        0.046        1.677        0.222
 10     1338.148        1308.709         yes       1.00181    1.871        1.878        0.026        1.870        0.144
 11     1412.857        1381.774         yes       1.00127    1.975        1.980        0.019        1.975        0.113
 12     1457.992        1425.916         yes       1.00103    2.038        2.043        0.016        2.038        0.097
 13     1483.655        1451.015         yes       1.00091    2.074        2.078        0.014        2.074        0.089
 14     1498.798        1465.825         yes       1.00085    2.096        2.099        0.014        2.095        0.084
 15     1741.176        1702.870         yes       1.00027    2.434        2.436        0.005        2.434        0.036
 16     3044.032        2977.063         yes       1.00000    4.256        4.256        0.000        4.256        0.000
 17     3103.336        3035.063         yes       1.00000    4.339        4.339        0.000        4.339        0.000
 18     3129.156        3060.314         yes       1.00000    4.375        4.375        0.000        4.375        0.000
 19     3149.702        3080.409         yes       1.00000    4.404        4.404        0.000        4.404        0.000
 20     3161.355        3091.805         yes       1.00000    4.420        4.420        0.000        4.420        0.000
 21     3240.999        3169.697         yes       1.00000    4.531        4.531        0.000        4.531        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   2.10774       The ln(Q)    0.74562
    H vibration       49.97439   (kcal/mol)    209.09284     (kJ/mol)         0.07963919    (hartree)
    U vibration       49.97439   (kcal/mol)    209.09284     (kJ/mol)         0.07963919    (hartree)
           ZPE        49.16654   (kcal/mol)    205.71281     (kJ/mol)         0.07835180    (hartree)
    S vibration        4.19122  (cal/mol*K)     17.53607    (J/mol*K)         0.00000668  (hartree/K)
   Cv vibration        7.17374  (cal/mol*K)     30.01495    (J/mol*K)         0.00001143  (hartree/K)
    G vibration       48.72478   (kcal/mol)    203.86446     (kJ/mol)         0.07764780    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total        325580927341.22406       The ln(Q)   33.12022
        H total       52.34433   (kcal/mol)    219.00868     (kJ/mol)         0.08341593    (hartree)
        U total       51.75185   (kcal/mol)    216.52972     (kJ/mol)         0.08247174    (hartree)
       Cv total       13.13536  (cal/mol*K)     54.95836    (J/mol*K)         0.00002093  (hartree/K)
           ZPE        49.16654   (kcal/mol)    205.71281     (kJ/mol)         0.07835180    (hartree)
        S total       63.33697  (cal/mol*K)    265.00188    (J/mol*K)         0.00010093  (hartree/K)
        G total       34.05290   (kcal/mol)    142.47733     (kJ/mol)         0.05426670    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.08247174 (hartree)
                       Thermal correction to Enthalpy :   0.08341593 
              Thermal correction to Gibbs Free Energy :   0.05332251 (hartree)
              ZPE correction to the Electronic Energy :   0.07835180 (hartree)


