The thermochemical analysis of the Molecule:                     C5H8

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000       0.6626730000       1.0694830000      -0.0471120000
  C     6   12.00000      -0.6626730000       1.0694830000      -0.0471120000
  C     6   12.00000       1.2274200000      -0.3177130000       0.1039390000
  C     6   12.00000      -1.2274200000      -0.3177140000       0.1039390000
  C     6   12.00000       0.0000000000      -1.2194500000      -0.1365490000
  H     1    1.00782       1.2831310000       1.9546960000      -0.1049620000
  H     1    1.00782      -1.2831320000       1.9546960000      -0.1049620000
  H     1    1.00782       2.0399260000      -0.5241190000      -0.5957350000
  H     1    1.00782      -2.0399260000      -0.5241200000      -0.5957350000
  H     1    1.00782       1.6404370000      -0.4504700000       1.1099950000
  H     1    1.00782      -1.6404360000      -0.4504710000       1.1099950000
  H     1    1.00782       0.0000000000      -1.5562980000      -1.1747330000
  H     1    1.00782       0.0000000000      -2.1084540000       0.4934990000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           1
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          33
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
          0.00000000      0.02484757     -0.00200261

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x        68.65520        -0.00002        -0.00000
    y        -0.00002        69.22049        -0.00159
    z        -0.00000        -0.00159       127.08912

              Principal moments of inertia (amu*A**2): 
              68.65520000          69.22049000         127.08912000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation               59367.84186       The ln(Q)   10.99151

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       24.82321  (cal/mol*K)    103.86030    (J/mol*K)         0.00003956  (hartree/K)
  G rotation       -6.51231   (kcal/mol)    -27.24751     (kJ/mol)        -0.01037802    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    68.06260   amu

              *****      Translation thermodynamic functions     ******

  Q translation            22070798.48931       The ln(Q)   16.90977
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       38.57122  (cal/mol*K)    161.38196    (J/mol*K)         0.00006147  (hartree/K)
  G translation      -10.01879   (kcal/mol)    -41.91863     (kJ/mol)        -0.01596595    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   33
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   33


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      149.483         146.194         yes       1.97577    0.209        0.617        2.721       -0.194        1.907
  2      397.849         389.096         yes       1.18057    0.556        0.757        1.004        0.458        1.493
  3      617.784         604.193         yes       1.05727    0.864        0.963        0.443        0.831        1.023
  4      722.569         706.672         yes       1.03416    1.010        1.079        0.298        0.990        0.816
  5      790.879         773.480         yes       1.02452    1.106        1.160        0.230        1.091        0.695
  6      833.749         815.406         yes       1.01994    1.166        1.212        0.195        1.154        0.626
  7      904.123         884.232         yes       1.01422    1.264        1.300        0.149        1.256        0.522
  8      921.957         901.673         yes       1.01306    1.289        1.323        0.139        1.281        0.498
  9      928.800         908.366         yes       1.01264    1.299        1.331        0.135        1.291        0.489
 10      987.462         965.738         yes       1.00955    1.381        1.407        0.107        1.375        0.416
 11      992.674         970.835         yes       1.00932    1.388        1.414        0.105        1.382        0.410
 12     1054.795        1031.589         yes       1.00693    1.475        1.495        0.082        1.471        0.344
 13     1077.333        1053.631         yes       1.00623    1.506        1.525        0.075        1.503        0.322
 14     1137.509        1112.484         yes       1.00468    1.590        1.605        0.059        1.588        0.269
 15     1166.651        1140.985         yes       1.00408    1.631        1.644        0.053        1.629        0.247
 16     1238.504        1211.257         yes       1.00290    1.732        1.742        0.039        1.730        0.198
 17     1242.725        1215.385         yes       1.00284    1.737        1.747        0.039        1.736        0.195
 18     1318.994        1289.976         yes       1.00198    1.844        1.851        0.028        1.843        0.153
 19     1334.073        1304.723         yes       1.00185    1.865        1.872        0.027        1.864        0.146
 20     1343.370        1313.816         yes       1.00177    1.878        1.885        0.026        1.877        0.141
 21     1393.145        1362.496         yes       1.00140    1.948        1.953        0.021        1.947        0.120
 22     1489.394        1456.628         yes       1.00089    2.082        2.086        0.014        2.082        0.087
 23     1496.305        1463.386         yes       1.00086    2.092        2.096        0.014        2.092        0.085
 24     1516.857        1483.486         yes       1.00078    2.121        2.124        0.013        2.120        0.079
 25     1711.165        1673.520         yes       1.00031    2.392        2.394        0.006        2.392        0.040
 26     3036.733        2969.924         yes       1.00000    4.246        4.246        0.000        4.246        0.000
 27     3038.582        2971.733         yes       1.00000    4.248        4.248        0.000        4.248        0.000
 28     3071.625        3004.050         yes       1.00000    4.295        4.295        0.000        4.295        0.000
 29     3088.965        3021.008         yes       1.00000    4.319        4.319        0.000        4.319        0.000
 30     3093.738        3025.676         yes       1.00000    4.325        4.325        0.000        4.325        0.000
 31     3128.372        3059.547         yes       1.00000    4.374        4.374        0.000        4.374        0.000
 32     3199.725        3129.331         yes       1.00000    4.474        4.474        0.000        4.474        0.000
 33     3224.878        3153.931         yes       1.00000    4.509        4.509        0.000        4.509        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   2.93314       The ln(Q)    1.07607
    H vibration       73.37189   (kcal/mol)    306.98797     (kJ/mol)         0.11692544    (hartree)
    U vibration       73.37189   (kcal/mol)    306.98797     (kJ/mol)         0.11692544    (hartree)
           ZPE        72.21403   (kcal/mol)    302.14350     (kJ/mol)         0.11508028    (hartree)
    S vibration        6.02185  (cal/mol*K)     25.19542    (J/mol*K)         0.00000960  (hartree/K)
   Cv vibration       11.32435  (cal/mol*K)     47.38107    (J/mol*K)         0.00001805  (hartree/K)
    G vibration       71.57647   (kcal/mol)    299.47596     (kJ/mol)         0.11406427    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total       3843278578297.67139       The ln(Q)   34.89560
        H total       75.74183   (kcal/mol)    316.90381     (kJ/mol)         0.12070218    (hartree)
        U total       75.14934   (kcal/mol)    314.42485     (kJ/mol)         0.11975799    (hartree)
       Cv total       17.28597  (cal/mol*K)     72.32449    (J/mol*K)         0.00002755  (hartree/K)
           ZPE        72.21403   (kcal/mol)    302.14350     (kJ/mol)         0.11508028    (hartree)
        S total       69.41627  (cal/mol*K)    290.43768    (J/mol*K)         0.00011062  (hartree/K)
        G total       55.63785   (kcal/mol)    232.78878     (kJ/mol)         0.08866448    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.11975799 (hartree)
                       Thermal correction to Enthalpy :   0.12070218 
              Thermal correction to Gibbs Free Energy :   0.08772030 (hartree)
              ZPE correction to the Electronic Energy :   0.11508028 (hartree)


