The thermochemical analysis of the Molecule:                     C3H4

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000       0.0000000000       0.0000000000       0.0000000000
  C     6   12.00000       0.0000000000       0.0000000000       1.2986680000
  C     6   12.00000       0.0000000000       0.0000000000      -1.2986680000
  H     1    1.00782       0.0000000000       0.9284320000       1.8570910000
  H     1    1.00782       0.0000000000      -0.9284320000       1.8570910000
  H     1    1.00782      -0.9284320000       0.0000000000      -1.8570910000
  H     1    1.00782       0.9284320000       0.0000000000      -1.8570910000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           4
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          15
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
          0.00000000      0.00000000      0.00000000

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x        56.11748         0.00000         0.00000
    y         0.00000        56.11748         0.00000
    z         0.00000         0.00000         3.47492

              Principal moments of inertia (amu*A**2): 
              56.11748000          56.11748000           3.47492000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation                1997.80857       The ln(Q)    7.59981

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       18.08319  (cal/mol*K)     75.66009    (J/mol*K)         0.00002882  (hartree/K)
  G rotation       -4.50278   (kcal/mol)    -18.83962     (kJ/mol)        -0.00717562    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    40.03130   amu

              *****      Translation thermodynamic functions     ******

  Q translation             9955309.89635       The ln(Q)   16.11362
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       36.98910  (cal/mol*K)    154.76240    (J/mol*K)         0.00005895  (hartree/K)
  G translation       -9.54709   (kcal/mol)    -39.94501     (kJ/mol)        -0.01521424    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   15
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   15


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      376.981         368.687         yes       1.20305    0.527        0.741        1.085        0.418        1.537
  2      376.981         368.687         yes       1.20305    0.527        0.741        1.085        0.418        1.537
  3      886.940         867.427         yes       1.01544    1.240        1.278        0.159        1.231        0.546
  4      886.940         867.427         yes       1.01544    1.240        1.278        0.159        1.231        0.546
  5      887.543         868.017         yes       1.01540    1.241        1.279        0.159        1.232        0.545
  6     1023.967        1001.440         yes       1.00803    1.432        1.455        0.093        1.427        0.376
  7     1023.967        1001.440         yes       1.00803    1.432        1.455        0.093        1.427        0.376
  8     1120.986        1096.325         yes       1.00506    1.567        1.583        0.063        1.564        0.283
  9     1428.967        1397.530         yes       1.00118    1.998        2.003        0.018        1.997        0.107
 10     1491.663        1458.847         yes       1.00088    2.086        2.089        0.014        2.085        0.086
 11     2077.631        2031.923         yes       1.00006    2.905        2.905        0.001        2.905        0.011
 12     3154.992        3085.582         yes       1.00000    4.411        4.411        0.000        4.411        0.000
 13     3157.432        3087.968         yes       1.00000    4.414        4.414        0.000        4.414        0.000
 14     3238.535        3167.287         yes       1.00000    4.528        4.528        0.000        4.528        0.000
 15     3238.535        3167.287         yes       1.00000    4.528        4.528        0.000        4.528        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   1.55086       The ln(Q)    0.43881
    H vibration       34.68855   (kcal/mol)    145.13688     (kJ/mol)         0.05527967    (hartree)
    U vibration       34.68855   (kcal/mol)    145.13688     (kJ/mol)         0.05527967    (hartree)
           ZPE        34.07509   (kcal/mol)    142.57018     (kJ/mol)         0.05430207    (hartree)
    S vibration        2.92954  (cal/mol*K)     12.25721    (J/mol*K)         0.00000467  (hartree/K)
   Cv vibration        5.94905  (cal/mol*K)     24.89081    (J/mol*K)         0.00000948  (hartree/K)
    G vibration       33.81510   (kcal/mol)    141.48239     (kJ/mol)         0.05388775    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total         30844735940.56131       The ln(Q)   32.66604
        H total       37.05849   (kcal/mol)    155.05272     (kJ/mol)         0.05905641    (hartree)
        U total       36.46600   (kcal/mol)    152.57376     (kJ/mol)         0.05811222    (hartree)
       Cv total       11.91067  (cal/mol*K)     49.83422    (J/mol*K)         0.00001898  (hartree/K)
           ZPE        34.07509   (kcal/mol)    142.57018     (kJ/mol)         0.05430207    (hartree)
        S total       58.00184  (cal/mol*K)    242.67970    (J/mol*K)         0.00009243  (hartree/K)
        G total       20.35773   (kcal/mol)     85.17673     (kJ/mol)         0.03244207    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.05811222 (hartree)
                       Thermal correction to Enthalpy :   0.05905641 
              Thermal correction to Gibbs Free Energy :   0.03149789 (hartree)
              ZPE correction to the Electronic Energy :   0.05430207 (hartree)


