The thermochemical analysis of the Molecule:                     C4H6

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000       0.6260740000       1.8656110000       0.0000000000
  C     6   12.00000       0.0000000000       0.8445670000       0.0000000000
  H     1    1.00782       1.1769920000       2.7750660000       0.0000000000
  C     6   12.00000      -0.7386920000      -0.4141050000       0.0000000000
  C     6   12.00000       0.1773530000      -1.6392930000       0.0000000000
  H     1    1.00782      -0.4158370000      -2.5544820000       0.0000000000
  H     1    1.00782       0.8176690000      -1.6431070000       0.8822340000
  H     1    1.00782       0.8176690000      -1.6431070000      -0.8822340000
  H     1    1.00782      -1.3924520000      -0.4375280000       0.8755040000
  H     1    1.00782      -1.3924520000      -0.4375280000      -0.8755040000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           1
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          24
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
          0.00713028      0.07234151      0.00000000

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x       107.62717       -17.05249         0.00000
    y       -17.05249        21.56642         0.00000
    z         0.00000         0.00000       122.96586

              Principal moments of inertia (amu*A**2): 
             110.88287000          18.31072000         122.96586000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation               38169.83359       The ln(Q)   10.54980

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       23.94544  (cal/mol*K)    100.18774    (J/mol*K)         0.00003816  (hartree/K)
  G rotation       -6.25061   (kcal/mol)    -26.15253     (kJ/mol)        -0.00996097    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    54.04695   amu

              *****      Translation thermodynamic functions     ******

  Q translation            15617518.49231       The ln(Q)   16.56390
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       37.88392  (cal/mol*K)    158.50630    (J/mol*K)         0.00006037  (hartree/K)
  G translation       -9.81388   (kcal/mol)    -41.06125     (kJ/mol)        -0.01563939    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   24
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   24


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      205.374         200.855         yes       1.61125    0.287        0.638        2.125        0.005        1.839
  2      224.036         219.107         yes       1.53228    0.313        0.647        1.966        0.060        1.812
  3      369.439         361.312         yes       1.21197    0.517        0.735        1.116        0.403        1.552
  4      530.741         519.065         yes       1.08896    0.742        0.874        0.612        0.692        1.208
  5      686.743         671.635         yes       1.04071    0.960        1.038        0.342        0.937        0.885
  6      693.104         677.855         yes       1.03946    0.969        1.046        0.333        0.946        0.872
  7      796.880         779.348         yes       1.02382    1.114        1.167        0.225        1.100        0.685
  8      857.253         838.394         yes       1.01781    1.199        1.241        0.178        1.188        0.590
  9     1038.633        1015.784         yes       1.00749    1.452        1.474        0.088        1.448        0.360
 10     1099.936        1075.737         yes       1.00560    1.538        1.555        0.069        1.535        0.301
 11     1116.234        1091.677         yes       1.00518    1.561        1.577        0.064        1.558        0.287
 12     1296.996        1268.462         yes       1.00220    1.813        1.821        0.031        1.812        0.164
 13     1361.264        1331.316         yes       1.00162    1.903        1.909        0.024        1.902        0.133
 14     1420.647        1389.393         yes       1.00123    1.986        1.991        0.019        1.986        0.110
 15     1484.871        1452.203         yes       1.00091    2.076        2.080        0.014        2.075        0.088
 16     1501.131        1468.106         yes       1.00084    2.099        2.102        0.013        2.098        0.084
 17     1509.229        1476.026         yes       1.00081    2.110        2.113        0.013        2.110        0.081
 18     2247.707        2198.257         yes       1.00002    3.143        3.143        0.001        3.143        0.006
 19     3058.838        2991.544         yes       1.00000    4.277        4.277        0.000        4.277        0.000
 20     3061.747        2994.388         yes       1.00000    4.281        4.281        0.000        4.281        0.000
 21     3093.293        3025.241         yes       1.00000    4.325        4.325        0.000        4.325        0.000
 22     3141.050        3071.947         yes       1.00000    4.392        4.392        0.000        4.392        0.000
 23     3144.256        3075.082         yes       1.00000    4.396        4.396        0.000        4.396        0.000
 24     3478.220        3401.699         yes       1.00000    4.863        4.863        0.000        4.863        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   3.76919       The ln(Q)    1.32686
    H vibration       53.68528   (kcal/mol)    224.61921     (kJ/mol)         0.08555286    (hartree)
    U vibration       53.68528   (kcal/mol)    224.61921     (kJ/mol)         0.08555286    (hartree)
           ZPE        52.31437   (kcal/mol)    218.88331     (kJ/mol)         0.08336818    (hartree)
    S vibration        7.23481  (cal/mol*K)     30.27043    (J/mol*K)         0.00001153  (hartree/K)
   Cv vibration       11.05831  (cal/mol*K)     46.26797    (J/mol*K)         0.00001762  (hartree/K)
    G vibration       51.52822   (kcal/mol)    215.59408     (kJ/mol)         0.08211537    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total       2246881939010.58643       The ln(Q)   34.45467
        H total       56.05522   (kcal/mol)    234.53505     (kJ/mol)         0.08932960    (hartree)
        U total       55.46274   (kcal/mol)    232.05609     (kJ/mol)         0.08838542    (hartree)
       Cv total       17.01993  (cal/mol*K)     71.21139    (J/mol*K)         0.00002712  (hartree/K)
           ZPE        52.31437   (kcal/mol)    218.88331     (kJ/mol)         0.08336818    (hartree)
        S total       69.06417  (cal/mol*K)    288.96447    (J/mol*K)         0.00011006  (hartree/K)
        G total       36.05623   (kcal/mol)    150.85925     (kJ/mol)         0.05745920    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.08838542 (hartree)
                       Thermal correction to Enthalpy :   0.08932960 
              Thermal correction to Gibbs Free Energy :   0.05651502 (hartree)
              ZPE correction to the Electronic Energy :   0.08336818 (hartree)


