The thermochemical analysis of the Molecule:                     C2H6

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000       0.0000000000       0.0000000000       0.7614010000
  C     6   12.00000       0.0000000000       0.0000000000      -0.7614010000
  H     1    1.00782       0.0000000000       1.0171170000       1.1572460000
  H     1    1.00782      -0.8808490000      -0.5085590000       1.1572460000
  H     1    1.00782       0.8808490000      -0.5085590000       1.1572460000
  H     1    1.00782       0.0000000000      -1.0171170000      -1.1572460000
  H     1    1.00782      -0.8808490000       0.5085590000      -1.1572460000
  H     1    1.00782       0.8808490000       0.5085590000      -1.1572460000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           6
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          18
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
          0.00000000     -0.00000000      0.00000000

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x        25.13961         0.00000         0.00000
    y         0.00000        25.13961         0.00000
    z         0.00000         0.00000         6.25573

              Principal moments of inertia (amu*A**2): 
               6.25573000          25.13961000          25.13961000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation                 800.55176       The ln(Q)    6.68530

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       16.26588  (cal/mol*K)     68.05646    (J/mol*K)         0.00002592  (hartree/K)
  G rotation       -3.96095   (kcal/mol)    -16.57259     (kJ/mol)        -0.00631216    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    30.04695   amu

              *****      Translation thermodynamic functions     ******

  Q translation             6473748.66189       The ln(Q)   15.68327
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       36.13391  (cal/mol*K)    151.18426    (J/mol*K)         0.00005758  (hartree/K)
  G translation       -9.29211   (kcal/mol)    -38.87819     (kJ/mol)        -0.01480791    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   18
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   18


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      309.005         302.207         yes       1.30313    0.432        0.694        1.405        0.275        1.670
  2      833.176         814.846         yes       1.01999    1.165        1.211        0.196        1.153        0.627
  3      833.193         814.863         yes       1.01999    1.165        1.211        0.196        1.153        0.627
  4     1017.600         995.213         yes       1.00828    1.423        1.446        0.095        1.418        0.382
  5     1225.949        1198.978         yes       1.00308    1.714        1.725        0.042        1.712        0.206
  6     1225.953        1198.982         yes       1.00308    1.714        1.725        0.042        1.712        0.206
  7     1411.091        1380.047         yes       1.00128    1.973        1.978        0.020        1.972        0.113
  8     1432.110        1400.603         yes       1.00116    2.002        2.007        0.018        2.002        0.106
  9     1507.795        1474.624         yes       1.00081    2.108        2.112        0.013        2.108        0.082
 10     1507.799        1474.627         yes       1.00081    2.108        2.112        0.013        2.108        0.082
 11     1508.717        1475.525         yes       1.00081    2.109        2.113        0.013        2.109        0.082
 12     1508.717        1475.525         yes       1.00081    2.109        2.113        0.013        2.109        0.082
 13     3053.270        2986.098         yes       1.00000    4.269        4.269        0.000        4.269        0.000
 14     3054.083        2986.893         yes       1.00000    4.270        4.270        0.000        4.270        0.000
 15     3111.700        3043.242         yes       1.00000    4.351        4.351        0.000        4.351        0.000
 16     3111.705        3043.247         yes       1.00000    4.351        4.351        0.000        4.351        0.000
 17     3135.600        3066.616         yes       1.00000    4.384        4.384        0.000        4.384        0.000
 18     3135.605        3066.621         yes       1.00000    4.384        4.384        0.000        4.384        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   1.38326       The ln(Q)    0.32444
    H vibration       46.45360   (kcal/mol)    194.36187     (kJ/mol)         0.07402846    (hartree)
    U vibration       46.45360   (kcal/mol)    194.36187     (kJ/mol)         0.07402846    (hartree)
           ZPE        46.03044   (kcal/mol)    192.59135     (kJ/mol)         0.07335411    (hartree)
    S vibration        2.06403  (cal/mol*K)      8.63590    (J/mol*K)         0.00000329  (hartree/K)
   Cv vibration        4.26304  (cal/mol*K)     17.83654    (J/mol*K)         0.00000679  (hartree/K)
    G vibration       45.83821   (kcal/mol)    191.78707     (kJ/mol)         0.07304777    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total          7168838694.21825       The ln(Q)   31.69097
        H total       48.82354   (kcal/mol)    204.27771     (kJ/mol)         0.07780520    (hartree)
        U total       48.23106   (kcal/mol)    201.79875     (kJ/mol)         0.07686101    (hartree)
       Cv total       10.22466  (cal/mol*K)     42.77996    (J/mol*K)         0.00001629  (hartree/K)
           ZPE        46.03044   (kcal/mol)    192.59135     (kJ/mol)         0.07335411    (hartree)
        S total       54.46382  (cal/mol*K)    227.87663    (J/mol*K)         0.00008679  (hartree/K)
        G total       33.17764   (kcal/mol)    138.81525     (kJ/mol)         0.05287189    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.07686101 (hartree)
                       Thermal correction to Enthalpy :   0.07780520 
              Thermal correction to Gibbs Free Energy :   0.05192770 (hartree)
              ZPE correction to the Electronic Energy :   0.07335411 (hartree)


