The thermochemical analysis of the Molecule:                     C4H8

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000      -0.7617740000      -0.7617740000      -0.1269590000
  C     6   12.00000      -0.7617740000       0.7617740000       0.1269590000
  C     6   12.00000       0.7617740000      -0.7617740000       0.1269590000
  C     6   12.00000       0.7617740000       0.7617740000      -0.1269590000
  H     1    1.00782      -1.3845390000      -1.3845390000       0.5146760000
  H     1    1.00782      -0.9926130000      -0.9926130000      -1.1679660000
  H     1    1.00782      -1.3845390000       1.3845390000      -0.5146760000
  H     1    1.00782      -0.9926130000       0.9926130000       1.1679660000
  H     1    1.00782       1.3845390000       1.3845390000       0.5146760000
  H     1    1.00782       0.9926130000       0.9926130000      -1.1679660000
  H     1    1.00782       1.3845390000      -1.3845390000      -0.5146760000
  H     1    1.00782       0.9926130000      -0.9926130000       1.1679660000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           2
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          30
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
         -0.00000000      0.00000000      0.00000000

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x        46.89496        -0.00000         0.00000
    y        -0.00000        46.89496         0.00000
    z         0.00000         0.00000        79.10827

              Principal moments of inertia (amu*A**2): 
              46.89496000          46.89496000          79.10827000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation               15931.26156       The ln(Q)    9.67604

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       22.20910  (cal/mol*K)     92.92287    (J/mol*K)         0.00003539  (hartree/K)
  G rotation       -5.73291   (kcal/mol)    -23.98651     (kJ/mol)        -0.00913597    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    56.06260   amu

              *****      Translation thermodynamic functions     ******

  Q translation            16499283.89863       The ln(Q)   16.61883
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       37.99306  (cal/mol*K)    158.96297    (J/mol*K)         0.00006055  (hartree/K)
  G translation       -9.84642   (kcal/mol)    -41.19741     (kJ/mol)        -0.01569125    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   30
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   30


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      196.835         192.505         yes       1.65279    0.275        0.634        2.204       -0.023        1.850
  2      638.113         624.075         yes       1.05176    0.892        0.985        0.410        0.862        0.981
  3      766.237         749.380         yes       1.02763    1.071        1.130        0.253        1.055        0.738
  4      766.237         749.380         yes       1.02763    1.071        1.130        0.253        1.055        0.738
  5      895.952         876.241         yes       1.01479    1.253        1.290        0.153        1.244        0.533
  6      935.275         914.699         yes       1.01225    1.308        1.340        0.132        1.300        0.480
  7      935.275         914.699         yes       1.01225    1.308        1.340        0.132        1.300        0.480
  8      965.397         944.159         yes       1.01061    1.350        1.378        0.117        1.343        0.442
  9      977.067         955.572         yes       1.01004    1.366        1.393        0.112        1.360        0.428
 10     1036.877        1014.066         yes       1.00755    1.450        1.472        0.088        1.445        0.362
 11     1183.046        1157.019         yes       1.00377    1.654        1.667        0.049        1.652        0.235
 12     1184.743        1158.678         yes       1.00374    1.656        1.669        0.049        1.654        0.233
 13     1259.956        1232.237         yes       1.00262    1.762        1.771        0.036        1.760        0.185
 14     1259.956        1232.237         yes       1.00262    1.762        1.771        0.036        1.760        0.185
 15     1269.080        1241.160         yes       1.00251    1.774        1.783        0.035        1.773        0.179
 16     1271.034        1243.072         yes       1.00249    1.777        1.786        0.035        1.776        0.178
 17     1302.972        1274.306         yes       1.00214    1.822        1.830        0.030        1.820        0.161
 18     1302.972        1274.306         yes       1.00214    1.822        1.830        0.030        1.820        0.161
 19     1490.238        1457.453         yes       1.00088    2.084        2.087        0.014        2.083        0.087
 20     1490.238        1457.453         yes       1.00088    2.084        2.087        0.014        2.083        0.087
 21     1493.520        1460.663         yes       1.00087    2.088        2.092        0.014        2.088        0.086
 22     1530.553        1496.881         yes       1.00073    2.140        2.143        0.012        2.139        0.076
 23     3072.950        3005.345         yes       1.00000    4.296        4.296        0.000        4.296        0.000
 24     3074.756        3007.111         yes       1.00000    4.299        4.299        0.000        4.299        0.000
 25     3074.756        3007.111         yes       1.00000    4.299        4.299        0.000        4.299        0.000
 26     3080.606        3012.833         yes       1.00000    4.307        4.307        0.000        4.307        0.000
 27     3115.038        3046.507         yes       1.00000    4.355        4.355        0.000        4.355        0.000
 28     3128.319        3059.496         yes       1.00000    4.374        4.374        0.000        4.374        0.000
 29     3128.319        3059.496         yes       1.00000    4.374        4.374        0.000        4.374        0.000
 30     3145.629        3076.425         yes       1.00000    4.398        4.398        0.000        4.398        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   2.01359       The ln(Q)    0.69992
    H vibration       69.30872   (kcal/mol)    289.98770     (kJ/mol)         0.11045038    (hartree)
    U vibration       69.30872   (kcal/mol)    289.98770     (kJ/mol)         0.11045038    (hartree)
           ZPE        68.46872   (kcal/mol)    286.47311     (kJ/mol)         0.10911175    (hartree)
    S vibration        4.20828  (cal/mol*K)     17.60745    (J/mol*K)         0.00000671  (hartree/K)
   Cv vibration        8.88834  (cal/mol*K)     37.18882    (J/mol*K)         0.00001416  (hartree/K)
    G vibration       68.05402   (kcal/mol)    284.73804     (kJ/mol)         0.10845089    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total        529280924271.41956       The ln(Q)   33.93757
        H total       71.67867   (kcal/mol)    299.90354     (kJ/mol)         0.11422712    (hartree)
        U total       71.08618   (kcal/mol)    297.42458     (kJ/mol)         0.11328294    (hartree)
       Cv total       14.84996  (cal/mol*K)     62.13223    (J/mol*K)         0.00002366  (hartree/K)
           ZPE        68.46872   (kcal/mol)    286.47311     (kJ/mol)         0.10911175    (hartree)
        S total       64.41044  (cal/mol*K)    269.49328    (J/mol*K)         0.00010264  (hartree/K)
        G total       53.06718   (kcal/mol)    222.03308     (kJ/mol)         0.08456786    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.11328294 (hartree)
                       Thermal correction to Enthalpy :   0.11422712 
              Thermal correction to Gibbs Free Energy :   0.08362367 (hartree)
              ZPE correction to the Electronic Energy :   0.10911175 (hartree)


