The thermochemical analysis of the Molecule:                     C1H4

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000       0.0000000000       0.0000000000       0.0000000000
  H     1    1.00782       0.6286950000       0.6286950000       0.6286950000
  H     1    1.00782      -0.6286950000      -0.6286950000       0.6286950000
  H     1    1.00782      -0.6286950000       0.6286950000      -0.6286950000
  H     1    1.00782       0.6286950000      -0.6286950000      -0.6286950000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):          12
               The frequencies scale coefficient:     0.97800
                          The frequencies number:           9
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
          0.00000000      0.00000000      0.00000000

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x         3.18680         0.00000         0.00000
    y         0.00000         3.18680         0.00000
    z         0.00000         0.00000         3.18680

              Principal moments of inertia (amu*A**2): 
               3.18680000           3.18680000           3.18680000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation                  36.21550       The ln(Q)    3.58949

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       10.11386  (cal/mol*K)     42.31640    (J/mol*K)         0.00001612  (hartree/K)
  G rotation       -2.12672   (kcal/mol)     -8.89819     (kJ/mol)        -0.00338914    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    16.03130   amu

              *****      Translation thermodynamic functions     ******

  Q translation             2522948.32147       The ln(Q)   14.74094
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       34.26131  (cal/mol*K)    143.34931    (J/mol*K)         0.00005460  (hartree/K)
  G translation       -8.73379   (kcal/mol)    -36.54220     (kJ/mol)        -0.01391818    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:    9
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:    9


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1     1342.660        1313.121         yes       1.00177    1.877        1.884        0.026        1.876        0.142
  2     1342.660        1313.121         yes       1.00177    1.877        1.884        0.026        1.876        0.142
  3     1342.660        1313.121         yes       1.00177    1.877        1.884        0.026        1.876        0.142
  4     1560.968        1526.626         yes       1.00063    2.182        2.185        0.011        2.182        0.068
  5     1560.968        1526.626         yes       1.00063    2.182        2.185        0.011        2.182        0.068
  6     3045.356        2978.359         yes       1.00000    4.258        4.258        0.000        4.258        0.000
  7     3165.277        3095.641         yes       1.00000    4.425        4.425        0.000        4.425        0.000
  8     3165.277        3095.641         yes       1.00000    4.425        4.425        0.000        4.425        0.000
  9     3165.277        3095.641         yes       1.00000    4.425        4.425        0.000        4.425        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   1.00660       The ln(Q)    0.00658
    H vibration       27.55605   (kcal/mol)    115.29451     (kJ/mol)         0.04391332    (hartree)
    U vibration       27.55605   (kcal/mol)    115.29451     (kJ/mol)         0.04391332    (hartree)
           ZPE        27.53054   (kcal/mol)    115.18780     (kJ/mol)         0.04387268    (hartree)
    S vibration        0.09862  (cal/mol*K)      0.41263    (J/mol*K)         0.00000016  (hartree/K)
   Cv vibration        0.56235  (cal/mol*K)      2.35289    (J/mol*K)         0.00000090  (hartree/K)
    G vibration       27.52665   (kcal/mol)    115.17149     (kJ/mol)         0.04386646    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total            91973080.89674       The ln(Q)   29.48846
        H total       29.92599   (kcal/mol)    125.21035     (kJ/mol)         0.04769006    (hartree)
        U total       29.33351   (kcal/mol)    122.73139     (kJ/mol)         0.04674588    (hartree)
       Cv total        6.52397  (cal/mol*K)     27.29631    (J/mol*K)         0.00001040  (hartree/K)
           ZPE        27.53054   (kcal/mol)    115.18780     (kJ/mol)         0.04387268    (hartree)
        S total       44.47379  (cal/mol*K)    186.07834    (J/mol*K)         0.00007087  (hartree/K)
        G total       17.25862   (kcal/mol)     72.21005     (kJ/mol)         0.02750333    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.04674588 (hartree)
                       Thermal correction to Enthalpy :   0.04769006 
              Thermal correction to Gibbs Free Energy :   0.02655915 (hartree)
              ZPE correction to the Electronic Energy :   0.04387268 (hartree)


