The thermochemical analysis of the Molecule:                     C4H4

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000      -0.1127930000      -1.6857910000       0.0000000000
  C     6   12.00000       0.5866340000      -0.5559690000       0.0000000000
  C     6   12.00000       0.0000000000       0.7432410000       0.0000000000
  C     6   12.00000      -0.4690960000       1.8471020000       0.0000000000
  H     1    1.00782       0.3869830000      -2.6453760000       0.0000000000
  H     1    1.00782      -1.1952410000      -1.6810380000       0.0000000000
  H     1    1.00782       1.6711900000      -0.5882100000       0.0000000000
  H     1    1.00782      -0.8914050000       2.8231250000       0.0000000000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           1
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          18
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
          0.00054283      0.03988236      0.00000000

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x       103.58134        14.56450         0.00000
    y        14.56450        12.12920         0.00000
    z         0.00000         0.00000       115.71054

              Principal moments of inertia (amu*A**2): 
             105.84484000           9.86570000         115.71054000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation               26553.90046       The ln(Q)   10.18693

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       23.22435  (cal/mol*K)     97.17067    (J/mol*K)         0.00003701  (hartree/K)
  G rotation       -6.03561   (kcal/mol)    -25.25300     (kJ/mol)        -0.00961835    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    52.03130   amu

              *****      Translation thermodynamic functions     ******

  Q translation            14752046.00594       The ln(Q)   16.50689
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       37.77062  (cal/mol*K)    158.03228    (J/mol*K)         0.00006019  (hartree/K)
  G translation       -9.78010   (kcal/mol)    -40.91993     (kJ/mol)        -0.01558556    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   18
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   18


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      228.238         223.216         yes       1.51643    0.319        0.649        1.933        0.072        1.806
  2      326.598         319.413         yes       1.27240    0.457        0.705        1.313        0.314        1.636
  3      565.931         553.481         yes       1.07433    0.791        0.909        0.537        0.749        1.132
  4      685.317         670.240         yes       1.04100    0.958        1.037        0.343        0.934        0.887
  5      703.381         687.906         yes       1.03752    0.983        1.057        0.321        0.962        0.853
  6      715.651         699.907         yes       1.03534    1.001        1.071        0.306        0.980        0.829
  7      896.272         876.554         yes       1.01477    1.253        1.290        0.153        1.244        0.533
  8      982.176         960.568         yes       1.00980    1.373        1.400        0.110        1.367        0.422
  9     1023.690        1001.169         yes       1.00804    1.431        1.454        0.093        1.426        0.376
 10     1118.402        1093.797         yes       1.00513    1.564        1.580        0.064        1.561        0.285
 11     1331.476        1302.183         yes       1.00187    1.862        1.869        0.027        1.860        0.147
 12     1451.434        1419.502         yes       1.00106    2.029        2.034        0.017        2.029        0.099
 13     1703.933        1666.447         yes       1.00032    2.382        2.384        0.006        2.382        0.041
 14     2242.452        2193.118         yes       1.00003    3.135        3.135        0.001        3.135        0.006
 15     3169.172        3099.450         yes       1.00000    4.431        4.431        0.000        4.431        0.000
 16     3181.824        3111.824         yes       1.00000    4.449        4.449        0.000        4.449        0.000
 17     3265.051        3193.220         yes       1.00000    4.565        4.565        0.000        4.565        0.000
 18     3479.961        3403.402         yes       1.00000    4.865        4.865        0.000        4.865        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   2.41457       The ln(Q)    0.88152
    H vibration       38.88349   (kcal/mol)    162.68853     (kJ/mol)         0.06196473    (hartree)
    U vibration       38.88349   (kcal/mol)    162.68853     (kJ/mol)         0.06196473    (hartree)
           ZPE        37.84848   (kcal/mol)    158.35804     (kJ/mol)         0.06031534    (hartree)
    S vibration        5.22321  (cal/mol*K)     21.85392    (J/mol*K)         0.00000832  (hartree/K)
   Cv vibration        9.05340  (cal/mol*K)     37.87941    (J/mol*K)         0.00001443  (hartree/K)
    G vibration       37.32619   (kcal/mol)    156.17279     (kJ/mol)         0.05948302    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total        945845859524.88098       The ln(Q)   33.89531
        H total       41.25344   (kcal/mol)    172.60437     (kJ/mol)         0.06574147    (hartree)
        U total       40.66095   (kcal/mol)    170.12541     (kJ/mol)         0.06479729    (hartree)
       Cv total       15.01502  (cal/mol*K)     62.82282    (J/mol*K)         0.00002393  (hartree/K)
           ZPE        37.84848   (kcal/mol)    158.35804     (kJ/mol)         0.06031534    (hartree)
        S total       66.21818  (cal/mol*K)    277.05688    (J/mol*K)         0.00010553  (hartree/K)
        G total       22.10297   (kcal/mol)     92.47883     (kJ/mol)         0.03522329    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.06479729 (hartree)
                       Thermal correction to Enthalpy :   0.06574147 
              Thermal correction to Gibbs Free Energy :   0.03427911 (hartree)
              ZPE correction to the Electronic Energy :   0.06031534 (hartree)


