The thermochemical analysis of the Molecule:                     C4H6

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000       0.0000000000       0.6656010000       0.8102650000
  C     6   12.00000       0.0000000000      -0.6656010000       0.8102650000
  H     1    1.00782       0.0000000000       1.4100930000       1.5961380000
  H     1    1.00782       0.0000000000      -1.4100930000       1.5961380000
  C     6   12.00000       0.0000000000       0.7809910000      -0.6969600000
  C     6   12.00000       0.0000000000      -0.7809910000      -0.6969600000
  H     1    1.00782      -0.8877430000       1.2383790000      -1.1379860000
  H     1    1.00782       0.8877430000      -1.2383790000      -1.1379860000
  H     1    1.00782       0.8877430000       1.2383790000      -1.1379860000
  H     1    1.00782      -0.8877430000      -1.2383790000      -1.1379860000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           2
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          24
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
          0.00000000      0.00000000      0.02496001

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x        73.19837         0.00000         0.00000
    y         0.00000        40.91390         0.00000
    z         0.00000         0.00000        38.63851

              Principal moments of inertia (amu*A**2): 
              73.19837000          40.91390000          38.63851000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation               12992.99689       The ln(Q)    9.47217

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       21.80396  (cal/mol*K)     91.22777    (J/mol*K)         0.00003475  (hartree/K)
  G rotation       -5.61212   (kcal/mol)    -23.48112     (kJ/mol)        -0.00894348    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    54.04695   amu

              *****      Translation thermodynamic functions     ******

  Q translation            15617518.49231       The ln(Q)   16.56390
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       37.88392  (cal/mol*K)    158.50630    (J/mol*K)         0.00006037  (hartree/K)
  G translation       -9.81388   (kcal/mol)    -41.06125     (kJ/mol)        -0.01563939    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   24
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   24


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      323.125         316.016         yes       1.27816    0.452        0.703        1.331        0.306        1.643
  2      656.056         641.622         yes       1.04736    0.917        1.004        0.383        0.890        0.945
  3      868.809         849.695         yes       1.01685    1.215        1.256        0.170        1.205        0.572
  4      879.108         859.768         yes       1.01603    1.229        1.269        0.164        1.220        0.557
  5      911.451         891.399         yes       1.01373    1.274        1.309        0.144        1.266        0.512
  6      911.769         891.710         yes       1.01371    1.275        1.310        0.144        1.267        0.511
  7      956.058         935.025         yes       1.01110    1.337        1.366        0.121        1.330        0.454
  8     1010.968         988.727         yes       1.00854    1.413        1.438        0.098        1.408        0.390
  9     1050.295        1027.188         yes       1.00708    1.468        1.489        0.084        1.464        0.348
 10     1110.269        1085.843         yes       1.00533    1.552        1.569        0.066        1.549        0.292
 11     1147.730        1122.480         yes       1.00446    1.605        1.619        0.057        1.602        0.261
 12     1181.493        1155.500         yes       1.00380    1.652        1.664        0.050        1.650        0.236
 13     1233.092        1205.964         yes       1.00298    1.724        1.734        0.040        1.722        0.201
 14     1249.458        1221.970         yes       1.00276    1.747        1.757        0.038        1.745        0.191
 15     1336.718        1307.311         yes       1.00182    1.869        1.876        0.026        1.868        0.145
 16     1473.091        1440.683         yes       1.00096    2.060        2.064        0.015        2.059        0.092
 17     1496.649        1463.723         yes       1.00086    2.092        2.096        0.014        2.092        0.085
 18     1666.004        1629.351         yes       1.00038    2.329        2.331        0.007        2.329        0.047
 19     3064.266        2996.852         yes       1.00000    4.284        4.284        0.000        4.284        0.000
 20     3070.072        3002.531         yes       1.00000    4.292        4.292        0.000        4.292        0.000
 21     3107.453        3039.089         yes       1.00000    4.345        4.345        0.000        4.345        0.000
 22     3121.739        3053.061         yes       1.00000    4.365        4.365        0.000        4.365        0.000
 23     3197.918        3127.564         yes       1.00000    4.471        4.471        0.000        4.471        0.000
 24     3229.465        3158.417         yes       1.00000    4.515        4.515        0.000        4.515        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   1.49402       The ln(Q)    0.40147
    H vibration       54.12501   (kcal/mol)    226.45903     (kJ/mol)         0.08625361    (hartree)
    U vibration       54.12501   (kcal/mol)    226.45903     (kJ/mol)         0.08625361    (hartree)
           ZPE        53.48241   (kcal/mol)    223.77039     (kJ/mol)         0.08522956    (hartree)
    S vibration        2.95310  (cal/mol*K)     12.35576    (J/mol*K)         0.00000471  (hartree/K)
   Cv vibration        7.48426  (cal/mol*K)     31.31412    (J/mol*K)         0.00001193  (hartree/K)
    G vibration       53.24454   (kcal/mol)    222.77516     (kJ/mol)         0.08485050    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total        303164138965.76208       The ln(Q)   33.52928
        H total       56.49495   (kcal/mol)    236.37487     (kJ/mol)         0.09003035    (hartree)
        U total       55.90246   (kcal/mol)    233.89591     (kJ/mol)         0.08908617    (hartree)
       Cv total       13.44588  (cal/mol*K)     56.25754    (J/mol*K)         0.00002143  (hartree/K)
           ZPE        53.48241   (kcal/mol)    223.77039     (kJ/mol)         0.08522956    (hartree)
        S total       62.64097  (cal/mol*K)    262.08983    (J/mol*K)         0.00009982  (hartree/K)
        G total       38.41103   (kcal/mol)    160.71174     (kJ/mol)         0.06121182    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.08908617 (hartree)
                       Thermal correction to Enthalpy :   0.09003035 
              Thermal correction to Gibbs Free Energy :   0.06026763 (hartree)
              ZPE correction to the Electronic Energy :   0.08522956 (hartree)


