The thermochemical analysis of the Molecule:                     C6H4

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000       0.0000000000       0.6183140000      -1.2271960000
  C     6   12.00000       0.0000000000      -0.6183140000      -1.2271960000
  C     6   12.00000       0.0000000000       1.4539870000      -0.1325150000
  C     6   12.00000       0.0000000000      -1.4539870000      -0.1325150000
  C     6   12.00000       0.0000000000       0.7000210000       1.0490170000
  C     6   12.00000       0.0000000000      -0.7000210000       1.0490170000
  H     1    1.00782       0.0000000000       2.5346350000      -0.1344190000
  H     1    1.00782       0.0000000000      -2.5346350000      -0.1344190000
  H     1    1.00782       0.0000000000       1.2222030000       1.9985800000
  H     1    1.00782       0.0000000000      -1.2222030000       1.9985800000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           2
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          24
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
          0.00000000      0.00000000     -0.04865312

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x       158.51807         0.00000         0.00000
    y         0.00000        70.88377         0.00000
    z         0.00000         0.00000        87.63430

              Principal moments of inertia (amu*A**2): 
             158.51807000          70.88377000          87.63430000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation               37902.06488       The ln(Q)   10.54276

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       23.93145  (cal/mol*K)    100.12920    (J/mol*K)         0.00003814  (hartree/K)
  G rotation       -6.24643   (kcal/mol)    -26.13508     (kJ/mol)        -0.00995432    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    76.03130   amu

              *****      Translation thermodynamic functions     ******

  Q translation            26058167.24602       The ln(Q)   17.07584
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       38.90124  (cal/mol*K)    162.76280    (J/mol*K)         0.00006199  (hartree/K)
  G translation      -10.11719   (kcal/mol)    -42.33033     (kJ/mol)        -0.01612276    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   24
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   24


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      398.157         389.398         yes       1.18026    0.557        0.757        1.002        0.458        1.493
  2      409.673         400.660         yes       1.16911    0.573        0.766        0.960        0.480        1.469
  3      460.545         450.413         yes       1.12838    0.644        0.809        0.795        0.572        1.360
  4      615.938         602.387         yes       1.05780    0.861        0.961        0.446        0.828        1.027
  5      628.790         614.957         yes       1.05422    0.879        0.974        0.425        0.848        1.000
  6      762.467         745.692         yes       1.02814    1.066        1.126        0.256        1.050        0.744
  7      852.463         833.709         yes       1.01822    1.192        1.235        0.182        1.181        0.597
  8      886.690         867.182         yes       1.01546    1.240        1.278        0.159        1.231        0.546
  9      945.034         924.243         yes       1.01170    1.321        1.352        0.127        1.314        0.468
 10      986.519         964.816         yes       1.00960    1.379        1.406        0.108        1.374        0.417
 11     1013.030         990.744         yes       1.00846    1.416        1.440        0.097        1.411        0.387
 12     1083.233        1059.402         yes       1.00606    1.514        1.533        0.074        1.511        0.317
 13     1122.999        1098.293         yes       1.00502    1.570        1.586        0.063        1.567        0.281
 14     1172.005        1146.221         yes       1.00398    1.639        1.652        0.052        1.636        0.243
 15     1279.790        1251.634         yes       1.00239    1.789        1.798        0.033        1.788        0.173
 16     1321.793        1292.713         yes       1.00196    1.848        1.855        0.028        1.847        0.152
 17     1445.009        1413.219         yes       1.00109    2.020        2.025        0.017        2.020        0.101
 18     1501.347        1468.317         yes       1.00084    2.099        2.103        0.013        2.099        0.084
 19     1502.021        1468.977         yes       1.00084    2.100        2.104        0.013        2.100        0.083
 20     2059.632        2014.320         yes       1.00006    2.880        2.880        0.001        2.880        0.011
 21     3192.735        3122.495         yes       1.00000    4.464        4.464        0.000        4.464        0.000
 22     3208.418        3137.832         yes       1.00000    4.486        4.486        0.000        4.486        0.000
 23     3229.610        3158.558         yes       1.00000    4.515        4.515        0.000        4.515        0.000
 24     3233.186        3162.056         yes       1.00000    4.520        4.520        0.000        4.520        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   1.94386       The ln(Q)    0.66467
    H vibration       47.62535   (kcal/mol)    199.26448     (kJ/mol)         0.07589576    (hartree)
    U vibration       47.62535   (kcal/mol)    199.26448     (kJ/mol)         0.07589576    (hartree)
           ZPE        46.57293   (kcal/mol)    194.86115     (kJ/mol)         0.07421863    (hartree)
    S vibration        4.85068  (cal/mol*K)     20.29525    (J/mol*K)         0.00000773  (hartree/K)
   Cv vibration       10.95450  (cal/mol*K)     45.83361    (J/mol*K)         0.00001746  (hartree/K)
    G vibration       46.17912   (kcal/mol)    193.21345     (kJ/mol)         0.07359105    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total       1919867387019.18262       The ln(Q)   34.81636
        H total       49.99530   (kcal/mol)    209.18032     (kJ/mol)         0.07967250    (hartree)
        U total       49.40281   (kcal/mol)    206.70136     (kJ/mol)         0.07872832    (hartree)
       Cv total       16.91612  (cal/mol*K)     70.77703    (J/mol*K)         0.00002696  (hartree/K)
           ZPE        46.57293   (kcal/mol)    194.86115     (kJ/mol)         0.07421863    (hartree)
        S total       67.68338  (cal/mol*K)    283.18725    (J/mol*K)         0.00010786  (hartree/K)
        G total       30.40798   (kcal/mol)    127.22700     (kJ/mol)         0.04845816    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.07872832 (hartree)
                       Thermal correction to Enthalpy :   0.07967250 
              Thermal correction to Gibbs Free Energy :   0.04751398 (hartree)
              ZPE correction to the Electronic Energy :   0.07421863 (hartree)


