The thermochemical analysis of the Molecule:                     C3H4

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000       0.0000000000       0.0000000000       0.2187420000
  C     6   12.00000       0.0000000000       0.0000000000       1.4157790000
  H     1    1.00782       0.0000000000       0.0000000000       2.4790590000
  C     6   12.00000       0.0000000000       0.0000000000      -1.2366740000
  H     1    1.00782       0.0000000000       1.0205400000      -1.6220460000
  H     1    1.00782       0.8838140000      -0.5102700000      -1.6220460000
  H     1    1.00782      -0.8838140000      -0.5102700000      -1.6220460000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           3
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          15
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
          0.00000000      0.00000000      0.05916386

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x        58.56273         0.00000         0.00000
    y         0.00000        58.56273         0.00000
    z         0.00000         0.00000         3.14896

              Principal moments of inertia (amu*A**2): 
              58.56273000          58.56273000           3.14896000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation                2646.22286       The ln(Q)    7.88089

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       18.64176  (cal/mol*K)     77.99714    (J/mol*K)         0.00002971  (hartree/K)
  G rotation       -4.66931   (kcal/mol)    -19.53641     (kJ/mol)        -0.00744102    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    40.03130   amu

              *****      Translation thermodynamic functions     ******

  Q translation             9955309.89635       The ln(Q)   16.11362
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       36.98910  (cal/mol*K)    154.76240    (J/mol*K)         0.00005895  (hartree/K)
  G translation       -9.54709   (kcal/mol)    -39.94501     (kJ/mol)        -0.01521424    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   15
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   15


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      356.386         348.546         yes       1.22851    0.498        0.726        1.173        0.376        1.578
  2      356.505         348.662         yes       1.22836    0.498        0.726        1.172        0.377        1.578
  3      693.163         677.914         yes       1.03945    0.969        1.046        0.333        0.946        0.872
  4      693.164         677.914         yes       1.03945    0.969        1.046        0.333        0.946        0.872
  5      950.765         929.848         yes       1.01138    1.329        1.360        0.124        1.323        0.461
  6     1060.905        1037.565         yes       1.00674    1.483        1.503        0.080        1.479        0.338
  7     1060.922        1037.582         yes       1.00674    1.483        1.503        0.080        1.479        0.338
  8     1418.845        1387.630         yes       1.00124    1.984        1.989        0.019        1.983        0.110
  9     1483.269        1450.637         yes       1.00091    2.074        2.078        0.015        2.073        0.089
 10     1483.269        1450.637         yes       1.00091    2.074        2.078        0.015        2.073        0.089
 11     2257.318        2207.657         yes       1.00002    3.156        3.156        0.001        3.156        0.005
 12     3060.581        2993.248         yes       1.00000    4.279        4.279        0.000        4.279        0.000
 13     3134.124        3065.173         yes       1.00000    4.382        4.382        0.000        4.382        0.000
 14     3134.129        3065.178         yes       1.00000    4.382        4.382        0.000        4.382        0.000
 15     3481.007        3404.424         yes       1.00000    4.867        4.867        0.000        4.867        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   1.67648       The ln(Q)    0.51669
    H vibration       35.11898   (kcal/mol)    146.93782     (kJ/mol)         0.05596561    (hartree)
    U vibration       35.11898   (kcal/mol)    146.93782     (kJ/mol)         0.05596561    (hartree)
           ZPE        34.42783   (kcal/mol)    144.04602     (kJ/mol)         0.05486418    (hartree)
    S vibration        3.34493  (cal/mol*K)     13.99517    (J/mol*K)         0.00000533  (hartree/K)
   Cv vibration        6.33081  (cal/mol*K)     26.48809    (J/mol*K)         0.00001009  (hartree/K)
    G vibration       34.12169   (kcal/mol)    142.76516     (kJ/mol)         0.05437633    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total         44165043825.26023       The ln(Q)   32.74393
        H total       37.48892   (kcal/mol)    156.85366     (kJ/mol)         0.05974235    (hartree)
        U total       36.89644   (kcal/mol)    154.37470     (kJ/mol)         0.05879817    (hartree)
       Cv total       12.29242  (cal/mol*K)     51.43151    (J/mol*K)         0.00001959  (hartree/K)
           ZPE        34.42783   (kcal/mol)    144.04602     (kJ/mol)         0.05486418    (hartree)
        S total       58.97579  (cal/mol*K)    246.75471    (J/mol*K)         0.00009398  (hartree/K)
        G total       20.49778   (kcal/mol)     85.76270     (kJ/mol)         0.03266526    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.05879817 (hartree)
                       Thermal correction to Enthalpy :   0.05974235 
              Thermal correction to Gibbs Free Energy :   0.03172107 (hartree)
              ZPE correction to the Electronic Energy :   0.05486418 (hartree)


