The thermochemical analysis of the Molecule:                     C2H2

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000       0.0000000000       0.0000000000      -0.4744890000
  C     6   12.00000       0.0000000000       0.0000000000       0.8148980000
  H     1    1.00782       0.0000000000       0.9393730000      -1.0212250000
  H     1    1.00782       0.0000000000      -0.9393730000      -1.0212250000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           2
               The frequencies scale coefficient:     0.97800
                          The frequencies number:           6
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
          0.00000000      0.00000000      0.07789449

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x        14.39331         0.00000         0.00000
    y         0.00000        12.61465         0.00000
    z         0.00000         0.00000         1.77865

              Principal moments of inertia (amu*A**2): 
              14.39331000          12.61465000           1.77865000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation                 686.39897       The ln(Q)    6.53146

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       15.96017  (cal/mol*K)     66.77735    (J/mol*K)         0.00002543  (hartree/K)
  G rotation       -3.86980   (kcal/mol)    -16.19123     (kJ/mol)        -0.00616691    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    26.01565   amu

              *****      Translation thermodynamic functions     ******

  Q translation             5215635.88359       The ln(Q)   15.46717
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       35.70448  (cal/mol*K)    149.38755    (J/mol*K)         0.00005690  (hartree/K)
  G translation       -9.16408   (kcal/mol)    -38.34250     (kJ/mol)        -0.01460387    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:    6
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:    6


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      352.736         344.976         yes       1.23341    0.493        0.723        1.189        0.369        1.585
  2      772.927         755.923         yes       1.02674    1.081        1.138        0.246        1.065        0.726
  3     1222.580        1195.683         yes       1.00313    1.709        1.720        0.042        1.707        0.208
  4     1735.043        1696.872         yes       1.00028    2.426        2.427        0.005        2.426        0.037
  5     3143.725        3074.563         yes       1.00000    4.395        4.395        0.000        4.395        0.000
  6     3230.834        3159.755         yes       1.00000    4.517        4.517        0.000        4.517        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   1.27071       The ln(Q)    0.23958
    H vibration       14.92141   (kcal/mol)     62.43117     (kJ/mol)         0.02377876    (hartree)
    U vibration       14.92141   (kcal/mol)     62.43117     (kJ/mol)         0.02377876    (hartree)
           ZPE        14.62133   (kcal/mol)     61.17566     (kJ/mol)         0.02330056    (hartree)
    S vibration        1.48255  (cal/mol*K)      6.20298    (J/mol*K)         0.00000236  (hartree/K)
   Cv vibration        2.55661  (cal/mol*K)     10.69684    (J/mol*K)         0.00000407  (hartree/K)
    G vibration       14.47939   (kcal/mol)     60.58175     (kJ/mol)         0.02307435    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total          4549164654.56457       The ln(Q)   31.17392
        H total       17.29135   (kcal/mol)     72.34701     (kJ/mol)         0.02755550    (hartree)
        U total       16.69887   (kcal/mol)     69.86805     (kJ/mol)         0.02661131    (hartree)
       Cv total        8.51823  (cal/mol*K)     35.64026    (J/mol*K)         0.00001357  (hartree/K)
           ZPE        14.62133   (kcal/mol)     61.17566     (kJ/mol)         0.02330056    (hartree)
        S total       53.14720  (cal/mol*K)    222.36788    (J/mol*K)         0.00008470  (hartree/K)
        G total        2.03800   (kcal/mol)      8.52699     (kJ/mol)         0.00324776    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.02661131 (hartree)
                       Thermal correction to Enthalpy :   0.02755550 
              Thermal correction to Gibbs Free Energy :   0.00230357 (hartree)
              ZPE correction to the Electronic Energy :   0.02330056 (hartree)


