The thermochemical analysis of the Molecule:                     C3H4

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000       0.0000000000       0.0000000000       0.8602550000
  C     6   12.00000       0.0000000000       0.6420650000      -0.4990290000
  C     6   12.00000       0.0000000000      -0.6420650000      -0.4990290000
  H     1    1.00782      -0.9122480000       0.0000000000       1.4547340000
  H     1    1.00782       0.9122480000       0.0000000000       1.4547340000
  H     1    1.00782       0.0000000000       1.5701050000      -1.0413250000
  H     1    1.00782       0.0000000000      -1.5701050000      -1.0413250000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           2
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          15
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
          0.00000000      0.00000000     -0.02049267

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x        36.15466         0.00000         0.00000
    y         0.00000        22.96910         0.00000
    z         0.00000         0.00000        16.54040

              Principal moments of inertia (amu*A**2): 
              36.15466000          22.96910000          16.54040000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation                4476.51507       The ln(Q)    8.40660

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       19.68646  (cal/mol*K)     82.36815    (J/mol*K)         0.00003137  (hartree/K)
  G rotation       -4.98079   (kcal/mol)    -20.83963     (kJ/mol)        -0.00793739    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    40.03130   amu

              *****      Translation thermodynamic functions     ******

  Q translation             9955309.89635       The ln(Q)   16.11362
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       36.98910  (cal/mol*K)    154.76240    (J/mol*K)         0.00005895  (hartree/K)
  G translation       -9.54709   (kcal/mol)    -39.94501     (kJ/mol)        -0.01521424    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   15
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   15


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      609.840         596.423         yes       1.05959    0.853        0.954        0.456        0.818        1.039
  2      809.634         791.822         yes       1.02239    1.132        1.183        0.214        1.119        0.664
  3      887.393         867.870         yes       1.01541    1.241        1.279        0.159        1.232        0.545
  4      923.359         903.045         yes       1.01297    1.291        1.324        0.138        1.283        0.496
  5     1023.946        1001.419         yes       1.00803    1.432        1.455        0.093        1.427        0.376
  6     1052.069        1028.924         yes       1.00703    1.471        1.492        0.083        1.467        0.347
  7     1083.590        1059.751         yes       1.00605    1.515        1.533        0.073        1.511        0.316
  8     1116.787        1092.218         yes       1.00517    1.561        1.578        0.064        1.558        0.287
  9     1159.360        1133.854         yes       1.00422    1.621        1.635        0.054        1.618        0.252
 10     1529.403        1495.756         yes       1.00073    2.138        2.141        0.012        2.138        0.076
 11     1754.918        1716.310         yes       1.00025    2.454        2.455        0.005        2.453        0.034
 12     3068.090        3000.592         yes       1.00000    4.290        4.290        0.000        4.290        0.000
 13     3135.867        3066.878         yes       1.00000    4.384        4.384        0.000        4.384        0.000
 14     3279.123        3206.982         yes       1.00000    4.585        4.585        0.000        4.585        0.000
 15     3324.914        3251.765         yes       1.00000    4.649        4.649        0.000        4.649        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   1.14981       The ln(Q)    0.13959
    H vibration       34.93534   (kcal/mol)    146.16946     (kJ/mol)         0.05567296    (hartree)
    U vibration       34.93534   (kcal/mol)    146.16946     (kJ/mol)         0.05567296    (hartree)
           ZPE        34.61509   (kcal/mol)    144.82955     (kJ/mol)         0.05516261    (hartree)
    S vibration        1.35152  (cal/mol*K)      5.65474    (J/mol*K)         0.00000215  (hartree/K)
   Cv vibration        4.43353  (cal/mol*K)     18.54991    (J/mol*K)         0.00000707  (hartree/K)
    G vibration       34.53239   (kcal/mol)    144.48350     (kJ/mol)         0.05503081    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total         51241282783.72995       The ln(Q)   32.36683
        H total       37.30528   (kcal/mol)    156.08530     (kJ/mol)         0.05944970    (hartree)
        U total       36.71280   (kcal/mol)    153.60634     (kJ/mol)         0.05850551    (hartree)
       Cv total       10.39515  (cal/mol*K)     43.49333    (J/mol*K)         0.00001657  (hartree/K)
           ZPE        34.61509   (kcal/mol)    144.82955     (kJ/mol)         0.05516261    (hartree)
        S total       58.02708  (cal/mol*K)    242.78530    (J/mol*K)         0.00009247  (hartree/K)
        G total       20.59699   (kcal/mol)     86.17782     (kJ/mol)         0.03282337    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.05850551 (hartree)
                       Thermal correction to Enthalpy :   0.05944970 
              Thermal correction to Gibbs Free Energy :   0.03187919 (hartree)
              ZPE correction to the Electronic Energy :   0.05516261 (hartree)


