The thermochemical analysis of the Molecule:                     C4H8

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000      -1.8482060000       0.0171150000      -0.2769140000
  C     6   12.00000      -0.7176110000      -0.2937000000       0.3375920000
  C     6   12.00000       0.5376150000       0.5216400000       0.3046540000
  H     1    1.00782      -1.9425680000       0.9273720000      -0.8598040000
  H     1    1.00782      -2.7201570000      -0.6223330000      -0.2195580000
  H     1    1.00782      -0.6655330000      -1.2186830000       0.9083990000
  H     1    1.00782       0.7919820000       0.8254260000       1.3253950000
  H     1    1.00782       0.3630060000       1.4388690000      -0.2631080000
  C     6   12.00000       1.7158880000      -0.2473510000      -0.2919240000
  H     1    1.00782       2.6251830000       0.3554430000      -0.2765890000
  H     1    1.00782       1.5106010000      -0.5295000000      -1.3259820000
  H     1    1.00782       1.9113690000      -1.1628210000       0.2707960000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           1
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          30
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
         -0.03316332     -0.00024386      0.00779483

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x        22.14708        -0.20877         0.38786
    y        -0.20877       121.11598        -0.75756
    z         0.38786        -0.75756       123.64457

              Principal moments of inertia (amu*A**2): 
              22.14517000         123.85597000         120.90649000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation               43991.20157       The ln(Q)   10.69174

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       24.22752  (cal/mol*K)    101.36793    (J/mol*K)         0.00003861  (hartree/K)
  G rotation       -6.33471   (kcal/mol)    -26.50441     (kJ/mol)        -0.01009499    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    56.06260   amu

              *****      Translation thermodynamic functions     ******

  Q translation            16499283.89863       The ln(Q)   16.61883
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       37.99306  (cal/mol*K)    158.96297    (J/mol*K)         0.00006055  (hartree/K)
  G translation       -9.84642   (kcal/mol)    -41.19741     (kJ/mol)        -0.01569125    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   30
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   30


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      104.813         102.507         yes       2.56263    0.147        0.605        3.406       -0.411        1.947
  2      232.413         227.300         yes       1.50131    0.325        0.651        1.900        0.084        1.799
  3      321.809         314.729         yes       1.28038    0.450        0.702        1.337        0.303        1.646
  4      442.095         432.369         yes       1.14171    0.618        0.793        0.851        0.540        1.400
  5      662.377         647.805         yes       1.04590    0.926        1.011        0.374        0.899        0.932
  6      805.006         787.296         yes       1.02290    1.125        1.177        0.218        1.112        0.672
  7      871.271         852.103         yes       1.01665    1.218        1.259        0.169        1.208        0.569
  8      963.755         942.553         yes       1.01070    1.347        1.376        0.118        1.341        0.444
  9      998.767         976.794         yes       1.00905    1.396        1.422        0.103        1.391        0.403
 10     1037.417        1014.594         yes       1.00753    1.450        1.472        0.088        1.446        0.362
 11     1049.015        1025.936         yes       1.00713    1.467        1.488        0.084        1.462        0.350
 12     1105.589        1081.266         yes       1.00545    1.546        1.563        0.067        1.543        0.296
 13     1209.931        1183.312         yes       1.00332    1.692        1.703        0.044        1.690        0.216
 14     1298.913        1270.337         yes       1.00218    1.816        1.824        0.031        1.815        0.163
 15     1331.094        1301.810         yes       1.00187    1.861        1.868        0.027        1.860        0.147
 16     1357.086        1327.230         yes       1.00166    1.897        1.904        0.024        1.896        0.135
 17     1417.179        1386.001         yes       1.00125    1.981        1.986        0.019        1.981        0.111
 18     1462.758        1430.577         yes       1.00101    2.045        2.049        0.016        2.045        0.095
 19     1490.485        1457.694         yes       1.00088    2.084        2.088        0.014        2.083        0.087
 20     1502.413        1469.360         yes       1.00083    2.101        2.104        0.013        2.100        0.083
 21     1510.714        1477.478         yes       1.00080    2.112        2.116        0.013        2.112        0.081
 22     1737.848        1699.615         yes       1.00027    2.430        2.431        0.005        2.430        0.037
 23     3042.015        2975.090         yes       1.00000    4.253        4.253        0.000        4.253        0.000
 24     3050.388        2983.279         yes       1.00000    4.265        4.265        0.000        4.265        0.000
 25     3087.166        3019.249         yes       1.00000    4.316        4.316        0.000        4.316        0.000
 26     3124.738        3055.994         yes       1.00000    4.369        4.369        0.000        4.369        0.000
 27     3130.827        3061.949         yes       1.00000    4.377        4.377        0.000        4.377        0.000
 28     3142.611        3073.473         yes       1.00000    4.394        4.394        0.000        4.394        0.000
 29     3153.773        3084.390         yes       1.00000    4.409        4.409        0.000        4.409        0.000
 30     3238.987        3167.729         yes       1.00000    4.528        4.528        0.000        4.528        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   6.45494       The ln(Q)    1.86485
    H vibration       68.50207   (kcal/mol)    286.61268     (kJ/mol)         0.10916491    (hartree)
    U vibration       68.50207   (kcal/mol)    286.61268     (kJ/mol)         0.10916491    (hartree)
           ZPE        66.94659   (kcal/mol)    280.10451     (kJ/mol)         0.10668608    (hartree)
    S vibration        8.92297  (cal/mol*K)     37.33372    (J/mol*K)         0.00001422  (hartree/K)
   Cv vibration       11.97736  (cal/mol*K)     50.11327    (J/mol*K)         0.00001909  (hartree/K)
    G vibration       65.84169   (kcal/mol)    275.48163     (kJ/mol)         0.10492532    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total       4685148717689.91309       The ln(Q)   35.10250
        H total       70.87202   (kcal/mol)    296.52852     (kJ/mol)         0.11294165    (hartree)
        U total       70.27953   (kcal/mol)    294.04956     (kJ/mol)         0.11199746    (hartree)
       Cv total       17.93898  (cal/mol*K)     75.05669    (J/mol*K)         0.00002859  (hartree/K)
           ZPE        66.94659   (kcal/mol)    280.10451     (kJ/mol)         0.10668608    (hartree)
        S total       71.14355  (cal/mol*K)    297.66461    (J/mol*K)         0.00011337  (hartree/K)
        G total       50.25305   (kcal/mol)    210.25878     (kJ/mol)         0.08008327    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.11199746 (hartree)
                       Thermal correction to Enthalpy :   0.11294165 
              Thermal correction to Gibbs Free Energy :   0.07913908 (hartree)
              ZPE correction to the Electronic Energy :   0.10668608 (hartree)


