The thermochemical analysis of the Molecule:                     C4H8

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000       0.0000000000       0.0000000000       1.4520930000
  C     6   12.00000       0.0000000000       0.0000000000       0.1250880000
  H     1    1.00782       0.0000000000       0.9241170000       2.0179870000
  H     1    1.00782       0.0000000000      -0.9241170000       2.0179870000
  C     6   12.00000       0.0000000000      -1.2688730000      -0.6761850000
  H     1    1.00782       0.0000000000      -2.1517970000      -0.0376970000
  H     1    1.00782      -0.8777280000      -1.3129560000      -1.3273620000
  H     1    1.00782       0.8777280000      -1.3129560000      -1.3273620000
  C     6   12.00000       0.0000000000       1.2688730000      -0.6761850000
  H     1    1.00782       0.0000000000       2.1517970000      -0.0376970000
  H     1    1.00782       0.8777280000       1.3129560000      -1.3273620000
  H     1    1.00782      -0.8777280000       1.3129560000      -1.3273620000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           2
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          30
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
          0.00000000      0.00000000      0.02387169

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x       108.39055         0.00000         0.00000
    y         0.00000        54.85172         0.00000
    z         0.00000         0.00000        59.75031

              Principal moments of inertia (amu*A**2): 
              59.75031000          54.85172000         108.39055000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation               22765.32943       The ln(Q)   10.03299

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       22.91844  (cal/mol*K)     95.89076    (J/mol*K)         0.00003652  (hartree/K)
  G rotation       -5.94441   (kcal/mol)    -24.87139     (kJ/mol)        -0.00947300    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    56.06260   amu

              *****      Translation thermodynamic functions     ******

  Q translation            16499283.89863       The ln(Q)   16.61883
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       37.99306  (cal/mol*K)    158.96297    (J/mol*K)         0.00006055  (hartree/K)
  G translation       -9.84642   (kcal/mol)    -41.19741     (kJ/mol)        -0.01569125    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   30
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   30


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      166.276         162.618         yes       1.83904    0.232        0.623        2.519       -0.128        1.888
  2      211.148         206.502         yes       1.58520    0.295        0.641        2.074        0.022        1.831
  3      388.283         379.740         yes       1.19049    0.543        0.750        1.040        0.440        1.513
  4      446.873         437.042         yes       1.13812    0.625        0.797        0.836        0.548        1.389
  5      448.900         439.024         yes       1.13662    0.628        0.799        0.830        0.552        1.385
  6      711.689         696.032         yes       1.03603    0.995        1.067        0.311        0.974        0.837
  7      829.428         811.181         yes       1.02036    1.160        1.207        0.198        1.148        0.632
  8      938.229         917.587         yes       1.01208    1.312        1.343        0.130        1.305        0.476
  9      970.239         948.894         yes       1.01037    1.357        1.385        0.115        1.350        0.437
 10      995.753         973.846         yes       1.00918    1.392        1.418        0.104        1.387        0.407
 11     1025.377        1002.819         yes       1.00798    1.434        1.456        0.092        1.429        0.374
 12     1091.272        1067.264         yes       1.00583    1.526        1.544        0.071        1.522        0.309
 13     1113.937        1089.430         yes       1.00524    1.557        1.574        0.065        1.554        0.289
 14     1312.303        1283.433         yes       1.00205    1.835        1.842        0.029        1.834        0.156
 15     1417.611        1386.424         yes       1.00124    1.982        1.987        0.019        1.981        0.111
 16     1420.584        1389.331         yes       1.00123    1.986        1.991        0.019        1.985        0.110
 17     1452.242        1420.293         yes       1.00106    2.030        2.035        0.016        2.030        0.099
 18     1474.950        1442.501         yes       1.00095    2.062        2.066        0.015        2.062        0.091
 19     1487.483        1454.758         yes       1.00089    2.080        2.083        0.014        2.079        0.088
 20     1494.307        1461.432         yes       1.00087    2.089        2.093        0.014        2.089        0.086
 21     1507.874        1474.701         yes       1.00081    2.108        2.112        0.013        2.108        0.082
 22     1749.284        1710.800         yes       1.00026    2.446        2.447        0.005        2.446        0.035
 23     3036.922        2970.110         yes       1.00000    4.246        4.246        0.000        4.246        0.000
 24     3040.902        2974.002         yes       1.00000    4.252        4.252        0.000        4.252        0.000
 25     3093.701        3025.640         yes       1.00000    4.325        4.325        0.000        4.325        0.000
 26     3095.884        3027.774         yes       1.00000    4.328        4.328        0.000        4.328        0.000
 27     3137.335        3068.314         yes       1.00000    4.386        4.386        0.000        4.386        0.000
 28     3139.465        3070.397         yes       1.00000    4.389        4.389        0.000        4.389        0.000
 29     3154.412        3085.014         yes       1.00000    4.410        4.410        0.000        4.410        0.000
 30     3238.271        3167.029         yes       1.00000    4.527        4.527        0.000        4.527        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   5.03852       The ln(Q)    1.61711
    H vibration       68.12330   (kcal/mol)    285.02790     (kJ/mol)         0.10856129    (hartree)
    U vibration       68.12330   (kcal/mol)    285.02790     (kJ/mol)         0.10856129    (hartree)
           ZPE        66.53789   (kcal/mol)    278.39453     (kJ/mol)         0.10603478    (hartree)
    S vibration        8.53103  (cal/mol*K)     35.69384    (J/mol*K)         0.00001360  (hartree/K)
   Cv vibration       12.62735  (cal/mol*K)     52.83285    (J/mol*K)         0.00002012  (hartree/K)
    G vibration       65.57977   (kcal/mol)    274.38578     (kJ/mol)         0.10450793    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total       1892526039604.92993       The ln(Q)   34.85477
        H total       70.49324   (kcal/mol)    294.94374     (kJ/mol)         0.11233803    (hartree)
        U total       69.90076   (kcal/mol)    292.46478     (kJ/mol)         0.11139385    (hartree)
       Cv total       18.58897  (cal/mol*K)     77.77626    (J/mol*K)         0.00002962  (hartree/K)
           ZPE        66.53789   (kcal/mol)    278.39453     (kJ/mol)         0.10603478    (hartree)
        S total       69.44254  (cal/mol*K)    290.54757    (J/mol*K)         0.00011066  (hartree/K)
        G total       50.38144   (kcal/mol)    210.79594     (kJ/mol)         0.08028786    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.11139385 (hartree)
                       Thermal correction to Enthalpy :   0.11233803 
              Thermal correction to Gibbs Free Energy :   0.07934367 (hartree)
              ZPE correction to the Electronic Energy :   0.10603478 (hartree)


