The thermochemical analysis of the Molecule:                     C6H4

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000       0.0000000000       1.1880640000       0.7398050000
  C     6   12.00000       0.0000000000       0.0000000000       1.3415420000
  C     6   12.00000       0.0000000000      -1.1880640000       0.7398050000
  C     6   12.00000       0.0000000000      -1.1880640000      -0.7398050000
  C     6   12.00000       0.0000000000       0.0000000000      -1.3415420000
  C     6   12.00000       0.0000000000       1.1880640000      -0.7398050000
  H     1    1.00782       0.0677660000       2.1696800000       1.1862300000
  H     1    1.00782      -0.0677660000      -2.1696800000       1.1862300000
  H     1    1.00782      -0.0677660000      -2.1696800000      -1.1862300000
  H     1    1.00782       0.0677660000       2.1696800000      -1.1862300000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           2
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          24
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
          0.00000000      0.00000000     -0.00000000

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x       161.86640        -0.59272         0.00000
    y        -0.59272        75.15571         0.00000
    z         0.00000         0.00000        86.74771

              Principal moments of inertia (amu*A**2): 
             161.87045000          75.15166000          86.74771000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation               39236.93886       The ln(Q)   10.57737

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       24.00024  (cal/mol*K)    100.41699    (J/mol*K)         0.00003825  (hartree/K)
  G rotation       -6.26694   (kcal/mol)    -26.22089     (kJ/mol)        -0.00998700    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    76.03130   amu

              *****      Translation thermodynamic functions     ******

  Q translation            26058167.24602       The ln(Q)   17.07584
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       38.90124  (cal/mol*K)    162.76280    (J/mol*K)         0.00006199  (hartree/K)
  G translation      -10.11719   (kcal/mol)    -42.33033     (kJ/mol)        -0.01612276    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   24
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   24


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      161.406         157.855         yes       1.87563    0.226        0.621        2.575       -0.147        1.894
  2      459.243         449.140         yes       1.12927    0.642        0.808        0.798        0.570        1.363
  3      469.766         459.431         yes       1.12224    0.657        0.817        0.768        0.588        1.340
  4      478.125         467.606         yes       1.11696    0.668        0.825        0.744        0.603        1.322
  5      561.603         549.247         yes       1.07598    0.785        0.905        0.546        0.742        1.141
  6      623.443         609.727         yes       1.05568    0.872        0.969        0.433        0.840        1.011
  7      728.159         712.140         yes       1.03325    1.018        1.086        0.292        0.999        0.806
  8      730.497         714.426         yes       1.03287    1.021        1.088        0.289        1.002        0.802
  9      753.206         736.635         yes       1.02943    1.053        1.115        0.266        1.036        0.761
 10      859.002         840.104         yes       1.01766    1.201        1.243        0.177        1.191        0.587
 11      911.705         891.647         yes       1.01372    1.275        1.310        0.144        1.267        0.512
 12      951.007         930.085         yes       1.01137    1.330        1.360        0.124        1.323        0.460
 13     1087.799        1063.868         yes       1.00593    1.521        1.539        0.072        1.517        0.312
 14     1092.704        1068.664         yes       1.00579    1.528        1.545        0.071        1.524        0.308
 15     1173.647        1147.827         yes       1.00395    1.641        1.654        0.051        1.639        0.242
 16     1235.362        1208.184         yes       1.00295    1.727        1.737        0.040        1.725        0.200
 17     1321.538        1292.464         yes       1.00196    1.848        1.855        0.028        1.847        0.152
 18     1414.451        1383.333         yes       1.00126    1.978        1.983        0.019        1.977        0.112
 19     1506.749        1473.601         yes       1.00082    2.107        2.110        0.013        2.106        0.082
 20     1758.168        1719.488         yes       1.00025    2.458        2.459        0.005        2.458        0.034
 21     3232.352        3161.240         yes       1.00000    4.519        4.519        0.000        4.519        0.000
 22     3235.496        3164.315         yes       1.00000    4.524        4.524        0.000        4.524        0.000
 23     3252.692        3181.133         yes       1.00000    4.548        4.548        0.000        4.548        0.000
 24     3252.719        3181.159         yes       1.00000    4.548        4.548        0.000        4.548        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   3.53676       The ln(Q)    1.26321
    H vibration       45.16719   (kcal/mol)    188.97951     (kJ/mol)         0.07197843    (hartree)
    U vibration       45.16719   (kcal/mol)    188.97951     (kJ/mol)         0.07197843    (hartree)
           ZPE        43.69246   (kcal/mol)    182.80924     (kJ/mol)         0.06962830    (hartree)
    S vibration        7.45653  (cal/mol*K)     31.19810    (J/mol*K)         0.00001188  (hartree/K)
   Cv vibration       13.44037  (cal/mol*K)     56.23449    (J/mol*K)         0.00002142  (hartree/K)
    G vibration       42.94402   (kcal/mol)    179.67779     (kJ/mol)         0.06843560    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total       3616132298400.86377       The ln(Q)   35.41489
        H total       47.53713   (kcal/mol)    198.89535     (kJ/mol)         0.07575517    (hartree)
        U total       46.94464   (kcal/mol)    196.41639     (kJ/mol)         0.07481098    (hartree)
       Cv total       19.40198  (cal/mol*K)     81.17790    (J/mol*K)         0.00003092  (hartree/K)
           ZPE        43.69246   (kcal/mol)    182.80924     (kJ/mol)         0.06962830    (hartree)
        S total       70.35800  (cal/mol*K)    294.37789    (J/mol*K)         0.00011212  (hartree/K)
        G total       27.15238   (kcal/mol)    113.60554     (kJ/mol)         0.04327003    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.07481098 (hartree)
                       Thermal correction to Enthalpy :   0.07575517 
              Thermal correction to Gibbs Free Energy :   0.04232584 (hartree)
              ZPE correction to the Electronic Energy :   0.06962830 (hartree)


