The thermochemical analysis of the Molecule:                     C4H8

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000      -0.3233060000       0.5783600000       0.0000000000
  C     6   12.00000       0.3233060000      -0.5783600000       0.0000000000
  H     1    1.00782      -1.4115440000       0.5667050000       0.0000000000
  H     1    1.00782       1.4115440000      -0.5667050000       0.0000000000
  C     6   12.00000       0.3233060000       1.9266830000       0.0000000000
  C     6   12.00000      -0.3233060000      -1.9266830000       0.0000000000
  H     1    1.00782       1.4112990000       1.8461690000       0.0000000000
  H     1    1.00782       0.0242200000       2.5054990000       0.8778790000
  H     1    1.00782       0.0242200000       2.5054990000      -0.8778790000
  H     1    1.00782      -1.4112990000      -1.8461690000       0.0000000000
  H     1    1.00782      -0.0242200000      -2.5054990000       0.8778790000
  H     1    1.00782      -0.0242200000      -2.5054990000      -0.8778790000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           2
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          30
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
         -0.00000000      0.00000000      0.00000000

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x       133.04934       -14.34613         0.00000
    y       -14.34613        16.15725         0.00000
    z         0.00000         0.00000       142.99297

              Principal moments of inertia (amu*A**2): 
             134.78428000          14.42231000         142.99297000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation               20137.58519       The ln(Q)    9.91034

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       22.67471  (cal/mol*K)     94.87098    (J/mol*K)         0.00003613  (hartree/K)
  G rotation       -5.87174   (kcal/mol)    -24.56734     (kJ/mol)        -0.00935720    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    56.06260   amu

              *****      Translation thermodynamic functions     ******

  Q translation            16499283.89863       The ln(Q)   16.61883
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       37.99306  (cal/mol*K)    158.96297    (J/mol*K)         0.00006055  (hartree/K)
  G translation       -9.84642   (kcal/mol)    -41.19741     (kJ/mol)        -0.01569125    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   30
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   30


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      176.236         172.359         yes       1.77081    0.246        0.626        2.410       -0.092        1.877
  2      227.645         222.637         yes       1.51863    0.318        0.648        1.938        0.071        1.807
  3      248.438         242.973         yes       1.44841    0.347        0.659        1.781        0.128        1.774
  4      289.638         283.266         yes       1.34207    0.405        0.682        1.514        0.231        1.705
  5      510.887         499.647         yes       1.09856    0.714        0.855        0.659        0.659        1.251
  6      771.652         754.675         yes       1.02691    1.079        1.137        0.248        1.063        0.728
  7      886.206         866.709         yes       1.01550    1.239        1.277        0.159        1.230        0.547
  8      995.786         973.879         yes       1.00918    1.392        1.418        0.104        1.387        0.407
  9     1009.865         987.648         yes       1.00859    1.412        1.436        0.098        1.407        0.391
 10     1074.029        1050.401         yes       1.00633    1.502        1.521        0.076        1.498        0.325
 11     1083.052        1059.225         yes       1.00606    1.514        1.533        0.074        1.511        0.317
 12     1090.971        1066.970         yes       1.00584    1.525        1.543        0.071        1.522        0.309
 13     1176.843        1150.952         yes       1.00389    1.645        1.658        0.051        1.643        0.239
 14     1338.673        1309.222         yes       1.00181    1.872        1.878        0.026        1.871        0.144
 15     1345.422        1315.822         yes       1.00175    1.881        1.888        0.026        1.880        0.140
 16     1420.571        1389.318         yes       1.00123    1.986        1.991        0.019        1.985        0.110
 17     1421.442        1390.170         yes       1.00122    1.987        1.992        0.019        1.987        0.109
 18     1483.916        1451.270         yes       1.00091    2.075        2.078        0.014        2.074        0.089
 19     1484.406        1451.749         yes       1.00091    2.075        2.079        0.014        2.075        0.089
 20     1494.117        1461.246         yes       1.00087    2.089        2.093        0.014        2.088        0.086
 21     1502.072        1469.026         yes       1.00083    2.100        2.104        0.013        2.100        0.083
 22     1774.603        1735.562         yes       1.00023    2.481        2.482        0.004        2.481        0.032
 23     3040.782        2973.885         yes       1.00000    4.251        4.251        0.000        4.251        0.000
 24     3041.299        2974.391         yes       1.00000    4.252        4.252        0.000        4.252        0.000
 25     3098.129        3029.970         yes       1.00000    4.332        4.332        0.000        4.332        0.000
 26     3098.541        3030.373         yes       1.00000    4.332        4.332        0.000        4.332        0.000
 27     3123.510        3054.793         yes       1.00000    4.367        4.367        0.000        4.367        0.000
 28     3124.380        3055.644         yes       1.00000    4.368        4.368        0.000        4.368        0.000
 29     3142.471        3073.337         yes       1.00000    4.394        4.394        0.000        4.394        0.000
 30     3148.145        3078.886         yes       1.00000    4.401        4.401        0.000        4.401        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   6.29251       The ln(Q)    1.83936
    H vibration       68.27626   (kcal/mol)    285.66788     (kJ/mol)         0.10880505    (hartree)
    U vibration       68.27626   (kcal/mol)    285.66788     (kJ/mol)         0.10880505    (hartree)
           ZPE        66.58374   (kcal/mol)    278.58637     (kJ/mol)         0.10610785    (hartree)
    S vibration        9.33193  (cal/mol*K)     39.04480    (J/mol*K)         0.00001487  (hartree/K)
   Cv vibration       12.55998  (cal/mol*K)     52.55095    (J/mol*K)         0.00002002  (hartree/K)
    G vibration       65.49395   (kcal/mol)    274.02667     (kJ/mol)         0.10437115    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total       2090722805529.15210       The ln(Q)   35.07702
        H total       70.64620   (kcal/mol)    295.58372     (kJ/mol)         0.11258179    (hartree)
        U total       70.05372   (kcal/mol)    293.10476     (kJ/mol)         0.11163761    (hartree)
       Cv total       18.52160  (cal/mol*K)     77.49436    (J/mol*K)         0.00002952  (hartree/K)
           ZPE        66.58374   (kcal/mol)    278.58637     (kJ/mol)         0.10610785    (hartree)
        S total       69.99970  (cal/mol*K)    292.87875    (J/mol*K)         0.00011155  (hartree/K)
        G total       50.36828   (kcal/mol)    210.74088     (kJ/mol)         0.08026689    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.11163761 (hartree)
                       Thermal correction to Enthalpy :   0.11258179 
              Thermal correction to Gibbs Free Energy :   0.07932270 (hartree)
              ZPE correction to the Electronic Energy :   0.10610785 (hartree)


