The thermochemical analysis of the Molecule:                     C6H4

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000       0.0000000000       0.0000000000       1.7590510000
  C     6   12.00000       0.0000000000       0.7667890000       0.6560490000
  C     6   12.00000       0.0000000000      -0.7667890000       0.6560490000
  C     6   12.00000       0.0000000000       1.1638300000      -0.6638680000
  C     6   12.00000       0.0000000000      -1.1638300000      -0.6638680000
  C     6   12.00000       0.0000000000       0.0000000000      -1.4511740000
  H     1    1.00782       0.0000000000       0.0000000000       2.8412910000
  H     1    1.00782       0.0000000000       2.1788830000      -1.0291300000
  H     1    1.00782       0.0000000000      -2.1788830000      -1.0291300000
  H     1    1.00782       0.0000000000       0.0000000000      -2.5364700000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           2
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          24
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
          0.00000000     -0.00000000      0.02288148

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x       156.21255         0.00000         0.00000
    y         0.00000       100.02402         0.00000
    z         0.00000         0.00000        56.18854

              Principal moments of inertia (amu*A**2): 
              56.18854000         100.02402000         156.21255000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation               35788.78785       The ln(Q)   10.48539

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       23.81745  (cal/mol*K)     99.65219    (J/mol*K)         0.00003796  (hartree/K)
  G rotation       -6.21244   (kcal/mol)    -25.99286     (kJ/mol)        -0.00990015    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    76.03130   amu

              *****      Translation thermodynamic functions     ******

  Q translation            26058167.24602       The ln(Q)   17.07584
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       38.90124  (cal/mol*K)    162.76280    (J/mol*K)         0.00006199  (hartree/K)
  G translation      -10.11719   (kcal/mol)    -42.33033     (kJ/mol)        -0.01612276    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   24
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   24


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      308.202         301.421         yes       1.30464    0.431        0.693        1.409        0.273        1.671
  2      580.092         567.330         yes       1.06919    0.811        0.923        0.509        0.771        1.102
  3      598.070         584.912         yes       1.06321    0.836        0.942        0.476        0.800        1.064
  4      626.510         612.726         yes       1.05483    0.876        0.972        0.428        0.844        1.005
  5      642.881         628.737         yes       1.05055    0.899        0.990        0.403        0.870        0.972
  6      803.387         785.713         yes       1.02308    1.123        1.175        0.219        1.110        0.675
  7      819.158         801.137         yes       1.02139    1.145        1.194        0.206        1.133        0.649
  8      823.380         805.265         yes       1.02096    1.151        1.199        0.203        1.139        0.642
  9      840.803         822.305         yes       1.01927    1.176        1.221        0.190        1.164        0.615
 10      913.315         893.222         yes       1.01361    1.277        1.312        0.143        1.269        0.509
 11      998.845         976.871         yes       1.00905    1.397        1.422        0.103        1.391        0.403
 12     1071.270        1047.702         yes       1.00641    1.498        1.517        0.077        1.494        0.328
 13     1071.408        1047.837         yes       1.00641    1.498        1.517        0.077        1.494        0.328
 14     1106.408        1082.067         yes       1.00543    1.547        1.564        0.067        1.544        0.296
 15     1148.917        1123.641         yes       1.00444    1.606        1.621        0.057        1.604        0.260
 16     1302.345        1273.694         yes       1.00215    1.821        1.829        0.030        1.820        0.161
 17     1378.890        1348.555         yes       1.00149    1.928        1.934        0.022        1.927        0.126
 18     1431.552        1400.058         yes       1.00116    2.001        2.006        0.018        2.001        0.106
 19     1576.747        1542.058         yes       1.00059    2.204        2.207        0.010        2.204        0.065
 20     1858.520        1817.633         yes       1.00016    2.598        2.599        0.003        2.598        0.024
 21     3190.091        3119.909         yes       1.00000    4.460        4.460        0.000        4.460        0.000
 22     3209.238        3138.635         yes       1.00000    4.487        4.487        0.000        4.487        0.000
 23     3246.674        3175.247         yes       1.00000    4.539        4.539        0.000        4.539        0.000
 24     3250.759        3179.242         yes       1.00000    4.545        4.545        0.000        4.545        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   1.88010       The ln(Q)    0.63132
    H vibration       46.86778   (kcal/mol)    196.09480     (kJ/mol)         0.07468850    (hartree)
    U vibration       46.86778   (kcal/mol)    196.09480     (kJ/mol)         0.07468850    (hartree)
           ZPE        45.85483   (kcal/mol)    191.85659     (kJ/mol)         0.07307425    (hartree)
    S vibration        4.65204  (cal/mol*K)     19.46414    (J/mol*K)         0.00000741  (hartree/K)
   Cv vibration       10.99974  (cal/mol*K)     46.02290    (J/mol*K)         0.00001753  (hartree/K)
    G vibration       45.48078   (kcal/mol)    190.29156     (kJ/mol)         0.07247816    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total       1753360342822.38013       The ln(Q)   34.78301
        H total       49.23772   (kcal/mol)    206.01064     (kJ/mol)         0.07846524    (hartree)
        U total       48.64524   (kcal/mol)    203.53168     (kJ/mol)         0.07752105    (hartree)
       Cv total       16.96136  (cal/mol*K)     70.96632    (J/mol*K)         0.00002703  (hartree/K)
           ZPE        45.85483   (kcal/mol)    191.85659     (kJ/mol)         0.07307425    (hartree)
        S total       67.37073  (cal/mol*K)    281.87914    (J/mol*K)         0.00010736  (hartree/K)
        G total       29.74363   (kcal/mol)    124.44733     (kJ/mol)         0.04739944    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.07752105 (hartree)
                       Thermal correction to Enthalpy :   0.07846524 
              Thermal correction to Gibbs Free Energy :   0.04645526 (hartree)
              ZPE correction to the Electronic Energy :   0.07307425 (hartree)


