The thermochemical analysis of the Molecule:                     C2H2

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000       0.0000000000       0.0000000000       0.5973210000
  C     6   12.00000       0.0000000000       0.0000000000      -0.5973210000
  H     1    1.00782       0.0000000000       0.0000000000       1.6613360000
  H     1    1.00782       0.0000000000       0.0000000000      -1.6613360000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           2
               The frequencies scale coefficient:     0.97800
                          The frequencies number:           7
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
          0.00000000      0.00000000      0.00000000

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x        14.12629         0.00000         0.00000
    y         0.00000        14.12629         0.00000
    z         0.00000         0.00000         0.00000

              Principal moments of inertia (amu*A**2): 
              14.12629000          14.12629000           0.00000000

                   The molecule was found to be linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation                  86.82472       The ln(Q)    4.46389

  H rotation        0.59249   (kcal/mol)      2.47896     (kJ/mol)         0.00094419    (hartree)
  U rotation        0.59249   (kcal/mol)      2.47896     (kJ/mol)         0.00094419    (hartree)
 Cv rotation        1.98721  (cal/mol*K)      8.31447    (J/mol*K)         0.00000317  (hartree/K)
  S rotation       10.85788  (cal/mol*K)     45.42937    (J/mol*K)         0.00001730  (hartree/K)
  G rotation       -2.64479   (kcal/mol)    -11.06581     (kJ/mol)        -0.00421474    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    26.01565   amu

              *****      Translation thermodynamic functions     ******

  Q translation             5215635.88359       The ln(Q)   15.46717
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       35.70448  (cal/mol*K)    149.38755    (J/mol*K)         0.00005690  (hartree/K)
  G translation       -9.16408   (kcal/mol)    -38.34250     (kJ/mol)        -0.01460387    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:    7
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:    7


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      675.784         660.917         yes       1.04297    0.945        1.026        0.356        0.920        0.906
  2      675.784         660.917         yes       1.04297    0.945        1.026        0.356        0.920        0.906
  3      777.318         760.217         yes       1.02618    1.087        1.144        0.242        1.071        0.719
  4      777.318         760.217         yes       1.02618    1.087        1.144        0.242        1.071        0.719
  5     2093.773        2047.710         yes       1.00005    2.927        2.928        0.001        2.927        0.010
  6     3422.031        3346.747         yes       1.00000    4.784        4.784        0.000        4.784        0.000
  7     3525.229        3447.674         yes       1.00000    4.929        4.929        0.000        4.929        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   1.14555       The ln(Q)    0.13588
    H vibration       16.98019   (kcal/mol)     71.04511     (kJ/mol)         0.02705963    (hartree)
    U vibration       16.98019   (kcal/mol)     71.04511     (kJ/mol)         0.02705963    (hartree)
           ZPE        16.70369   (kcal/mol)     69.88822     (kJ/mol)         0.02661899    (hartree)
    S vibration        1.19742  (cal/mol*K)      5.01000    (J/mol*K)         0.00000191  (hartree/K)
   Cv vibration        3.25882  (cal/mol*K)     13.63490    (J/mol*K)         0.00000519  (hartree/K)
    G vibration       16.62318   (kcal/mol)     69.55138     (kJ/mol)         0.02649070    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total           518755688.62430       The ln(Q)   31.07022
        H total       19.05389   (kcal/mol)     79.72147     (kJ/mol)         0.03036428    (hartree)
        U total       18.46140   (kcal/mol)     77.24251     (kJ/mol)         0.02942009    (hartree)
       Cv total        8.22684  (cal/mol*K)     34.42108    (J/mol*K)         0.00001311  (hartree/K)
           ZPE        16.70369   (kcal/mol)     69.88822     (kJ/mol)         0.02661899    (hartree)
        S total       47.75978  (cal/mol*K)    199.82693    (J/mol*K)         0.00007611  (hartree/K)
        G total        5.40680   (kcal/mol)     22.62203     (kJ/mol)         0.00861627    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.02942009 (hartree)
                       Thermal correction to Enthalpy :   0.03036428 
              Thermal correction to Gibbs Free Energy :   0.00767208 (hartree)
              ZPE correction to the Electronic Energy :   0.02661899 (hartree)


