The thermochemical analysis of the Molecule:                     C3H8

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000       0.0000000000       0.0000000000       0.5855560000
  C     6   12.00000       0.0000000000       1.2677460000      -0.2590880000
  C     6   12.00000       0.0000000000      -1.2677460000      -0.2590880000
  H     1    1.00782       0.8745400000       0.0000000000       1.2420450000
  H     1    1.00782      -0.8745400000       0.0000000000       1.2420450000
  H     1    1.00782       0.0000000000       2.1643010000       0.3631080000
  H     1    1.00782       0.8814590000       1.3076880000      -0.9036460000
  H     1    1.00782      -0.8814590000       1.3076880000      -0.9036460000
  H     1    1.00782       0.0000000000      -2.1643010000       0.3631080000
  H     1    1.00782      -0.8814590000      -1.3076880000      -0.9036460000
  H     1    1.00782       0.8814590000      -1.3076880000      -0.9036460000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           2
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          27
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
          0.00000000      0.00000000      0.00910338

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x        67.29675         0.00000         0.00000
    y         0.00000        17.06282         0.00000
    z         0.00000         0.00000        59.58155

              Principal moments of inertia (amu*A**2): 
              67.29675000          17.06282000          59.58155000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation                9990.59589       The ln(Q)    9.20940

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       21.28179  (cal/mol*K)     89.04301    (J/mol*K)         0.00003391  (hartree/K)
  G rotation       -5.45644   (kcal/mol)    -22.82973     (kJ/mol)        -0.00869538    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    44.06260   amu

              *****      Translation thermodynamic functions     ******

  Q translation            11496361.79520       The ln(Q)   16.25754
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       37.27511  (cal/mol*K)    155.95906    (J/mol*K)         0.00005940  (hartree/K)
  G translation       -9.63236   (kcal/mol)    -40.30179     (kJ/mol)        -0.01535013    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   27
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   27


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      221.917         217.035         yes       1.54052    0.310        0.646        1.984        0.054        1.815
  2      278.010         271.894         yes       1.36848    0.389        0.675        1.584        0.203        1.725
  3      374.368         366.132         yes       1.20609    0.523        0.739        1.096        0.412        1.542
  4      758.629         741.939         yes       1.02866    1.061        1.121        0.260        1.044        0.751
  5      888.843         869.288         yes       1.01530    1.243        1.281        0.158        1.234        0.543
  6      919.414         899.187         yes       1.01322    1.285        1.319        0.140        1.278        0.501
  7      941.200         920.493         yes       1.01191    1.316        1.347        0.129        1.309        0.473
  8     1077.984        1054.269         yes       1.00621    1.507        1.526        0.075        1.503        0.321
  9     1186.331        1160.231         yes       1.00372    1.659        1.671        0.049        1.656        0.232
 10     1220.617        1193.763         yes       1.00316    1.707        1.717        0.042        1.705        0.209
 11     1324.949        1295.801         yes       1.00193    1.852        1.860        0.028        1.851        0.150
 12     1375.950        1345.679         yes       1.00152    1.924        1.930        0.023        1.923        0.127
 13     1415.288        1384.152         yes       1.00126    1.979        1.984        0.019        1.978        0.112
 14     1427.415        1396.012         yes       1.00119    1.996        2.000        0.018        1.995        0.107
 15     1494.327        1461.452         yes       1.00087    2.089        2.093        0.014        2.089        0.086
 16     1498.362        1465.398         yes       1.00085    2.095        2.098        0.014        2.094        0.085
 17     1501.444        1468.412         yes       1.00084    2.099        2.103        0.013        2.099        0.084
 18     1512.226        1478.957         yes       1.00080    2.114        2.118        0.013        2.114        0.081
 19     1516.727        1483.359         yes       1.00078    2.121        2.124        0.013        2.120        0.079
 20     3041.906        2974.984         yes       1.00000    4.253        4.253        0.000        4.253        0.000
 21     3043.938        2976.971         yes       1.00000    4.256        4.256        0.000        4.256        0.000
 22     3046.932        2979.900         yes       1.00000    4.260        4.260        0.000        4.260        0.000
 23     3074.803        3007.157         yes       1.00000    4.299        4.299        0.000        4.299        0.000
 24     3108.982        3040.584         yes       1.00000    4.347        4.347        0.000        4.347        0.000
 25     3119.392        3050.765         yes       1.00000    4.361        4.361        0.000        4.361        0.000
 26     3120.815        3052.157         yes       1.00000    4.363        4.363        0.000        4.363        0.000
 27     3123.584        3054.865         yes       1.00000    4.367        4.367        0.000        4.367        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   2.78625       The ln(Q)    1.02470
    H vibration       64.85809   (kcal/mol)    271.36624     (kJ/mol)         0.10335785    (hartree)
    U vibration       64.85809   (kcal/mol)    271.36624     (kJ/mol)         0.10335785    (hartree)
           ZPE        63.77439   (kcal/mol)    266.83205     (kJ/mol)         0.10163087    (hartree)
    S vibration        5.67102  (cal/mol*K)     23.72757    (J/mol*K)         0.00000904  (hartree/K)
   Cv vibration        9.02479  (cal/mol*K)     37.75971    (J/mol*K)         0.00001438  (hartree/K)
    G vibration       63.16727   (kcal/mol)    264.29187     (kJ/mol)         0.10066336    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total        320015960240.32904       The ln(Q)   33.53978
        H total       67.22803   (kcal/mol)    281.28208     (kJ/mol)         0.10713459    (hartree)
        U total       66.63555   (kcal/mol)    278.80312     (kJ/mol)         0.10619040    (hartree)
       Cv total       14.98641  (cal/mol*K)     62.70312    (J/mol*K)         0.00002388  (hartree/K)
           ZPE        63.77439   (kcal/mol)    266.83205     (kJ/mol)         0.10163087    (hartree)
        S total       64.22792  (cal/mol*K)    268.72964    (J/mol*K)         0.00010235  (hartree/K)
        G total       48.67096   (kcal/mol)    203.63930     (kJ/mol)         0.07756204    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.10619040 (hartree)
                       Thermal correction to Enthalpy :   0.10713459 
              Thermal correction to Gibbs Free Energy :   0.07661786 (hartree)
              ZPE correction to the Electronic Energy :   0.10163087 (hartree)


