The thermochemical analysis of the Molecule:                     C5H8

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000      -0.5868550000       1.7226640000       0.0000000000
  C     6   12.00000       0.0000000000       0.5261200000       0.0000000000
  C     6   12.00000      -0.8243710000      -0.6874820000       0.0000000000
  H     1    1.00782      -0.0094640000       2.6389380000       0.0000000000
  H     1    1.00782      -1.6661040000       1.8198080000       0.0000000000
  C     6   12.00000       1.4931590000       0.3761920000       0.0000000000
  H     1    1.00782       1.9839180000       1.3484000000       0.0000000000
  H     1    1.00782       1.8287570000      -0.1787260000       0.8794590000
  H     1    1.00782       1.8287570000      -0.1787260000      -0.8794590000
  C     6   12.00000      -0.3674890000      -1.9354230000       0.0000000000
  H     1    1.00782      -1.8978430000      -0.5215250000       0.0000000000
  H     1    1.00782      -1.0464250000      -2.7781060000       0.0000000000
  H     1    1.00782       0.6917380000      -2.1624870000       0.0000000000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           1
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          33
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
         -0.02497600      0.00018117      0.00000000

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x       117.82987       -11.32140         0.00000
    y       -11.32140        60.90054         0.00000
    z         0.00000         0.00000       175.61241

              Principal moments of inertia (amu*A**2): 
             119.99870000          58.73171000         175.61241000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation               84985.57611       The ln(Q)   11.35024

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       25.53608  (cal/mol*K)    106.84294    (J/mol*K)         0.00004069  (hartree/K)
  G rotation       -6.72485   (kcal/mol)    -28.13678     (kJ/mol)        -0.01071672    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    68.06260   amu

              *****      Translation thermodynamic functions     ******

  Q translation            22070798.48931       The ln(Q)   16.90977
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       38.57122  (cal/mol*K)    161.38196    (J/mol*K)         0.00006147  (hartree/K)
  G translation      -10.01879   (kcal/mol)    -41.91863     (kJ/mol)        -0.01596595    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   33
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   33


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      157.231         153.772         yes       1.90889    0.220        0.619        2.625       -0.163        1.898
  2      214.728         210.004         yes       1.56981    0.300        0.642        2.044        0.033        1.826
  3      291.005         284.603         yes       1.33913    0.407        0.683        1.506        0.234        1.702
  4      413.325         404.232         yes       1.16574    0.578        0.769        0.947        0.487        1.461
  5      436.488         426.885         yes       1.14607    0.610        0.789        0.869        0.529        1.412
  6      542.212         530.284         yes       1.08387    0.758        0.885        0.587        0.710        1.183
  7      654.280         639.886         yes       1.04778    0.915        1.002        0.386        0.887        0.949
  8      798.232         780.671         yes       1.02366    1.116        1.169        0.224        1.102        0.683
  9      802.021         784.376         yes       1.02323    1.121        1.173        0.220        1.108        0.677
 10      948.261         927.399         yes       1.01152    1.326        1.356        0.125        1.319        0.464
 11      961.940         940.778         yes       1.01079    1.345        1.374        0.119        1.339        0.447
 12      973.358         951.944         yes       1.01022    1.361        1.389        0.113        1.355        0.433
 13     1018.191         995.791         yes       1.00825    1.424        1.447        0.095        1.419        0.382
 14     1042.742        1019.801         yes       1.00734    1.458        1.479        0.086        1.454        0.356
 15     1077.148        1053.450         yes       1.00624    1.506        1.525        0.075        1.502        0.322
 16     1097.857        1073.704         yes       1.00565    1.535        1.552        0.069        1.532        0.303
 17     1336.450        1307.048         yes       1.00183    1.869        1.875        0.027        1.867        0.145
 18     1343.881        1314.315         yes       1.00176    1.879        1.886        0.026        1.878        0.141
 19     1418.004        1386.807         yes       1.00124    1.983        1.987        0.019        1.982        0.111
 20     1444.389        1412.613         yes       1.00110    2.019        2.024        0.017        2.019        0.101
 21     1466.012        1433.760         yes       1.00099    2.050        2.054        0.016        2.049        0.094
 22     1485.886        1453.197         yes       1.00090    2.077        2.081        0.014        2.077        0.088
 23     1508.064        1474.886         yes       1.00081    2.108        2.112        0.013        2.108        0.082
 24     1691.060        1653.857         yes       1.00034    2.364        2.366        0.006        2.364        0.043
 25     1740.637        1702.343         yes       1.00027    2.434        2.435        0.005        2.433        0.036
 26     3049.770        2982.675         yes       1.00000    4.264        4.264        0.000        4.264        0.000
 27     3109.671        3041.258         yes       1.00000    4.348        4.348        0.000        4.348        0.000
 28     3145.637        3076.433         yes       1.00000    4.398        4.398        0.000        4.398        0.000
 29     3157.983        3088.508         yes       1.00000    4.415        4.415        0.000        4.415        0.000
 30     3162.046        3092.481         yes       1.00000    4.421        4.421        0.000        4.421        0.000
 31     3172.523        3102.727         yes       1.00000    4.436        4.436        0.000        4.436        0.000
 32     3244.867        3173.480         yes       1.00000    4.537        4.537        0.000        4.537        0.000
 33     3252.536        3180.981         yes       1.00000    4.547        4.547        0.000        4.547        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   6.83279       The ln(Q)    1.92173
    H vibration       72.03999   (kcal/mol)    301.41532     (kJ/mol)         0.11480293    (hartree)
    U vibration       72.03999   (kcal/mol)    301.41532     (kJ/mol)         0.11480293    (hartree)
           ZPE        70.12757   (kcal/mol)    293.41376     (kJ/mol)         0.11175530    (hartree)
    S vibration       10.23316  (cal/mol*K)     42.81555    (J/mol*K)         0.00001631  (hartree/K)
   Cv vibration       15.33996  (cal/mol*K)     64.18241    (J/mol*K)         0.00002445  (hartree/K)
    G vibration       68.98897   (kcal/mol)    288.64987     (kJ/mol)         0.10994083    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total      12816256937605.92383       The ln(Q)   35.74126
        H total       74.40993   (kcal/mol)    311.33116     (kJ/mol)         0.11857967    (hartree)
        U total       73.81745   (kcal/mol)    308.85220     (kJ/mol)         0.11763548    (hartree)
       Cv total       21.30158  (cal/mol*K)     89.12583    (J/mol*K)         0.00003395  (hartree/K)
           ZPE        70.12757   (kcal/mol)    293.41376     (kJ/mol)         0.11175530    (hartree)
        S total       74.34045  (cal/mol*K)    311.04045    (J/mol*K)         0.00011847  (hartree/K)
        G total       52.83781   (kcal/mol)    221.07341     (kJ/mol)         0.08420234    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.11763548 (hartree)
                       Thermal correction to Enthalpy :   0.11857967 
              Thermal correction to Gibbs Free Energy :   0.08325815 (hartree)
              ZPE correction to the Electronic Energy :   0.11175530 (hartree)


