The thermochemical analysis of the Molecule:                     C2H4

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000       0.5906750000       0.0226660000      -0.0305230000
  C     6   12.00000      -0.8428950000      -0.1909680000      -0.0398440000
  H     1    1.00782      -1.3106110000       0.8119120000       0.0056950000
  H     1    1.00782       0.6008960000       0.0694070000       1.0904920000
  H     1    1.00782       1.0193790000       0.9680460000      -0.3804280000
  H     1    1.00782       1.2036550000      -0.8395560000      -0.2935570000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           1
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          12
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
         -0.05356438     -0.03574266     -0.01494395

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x         4.18720        -0.98427        -0.07016
    y        -0.98427        18.68962        -0.02621
    z        -0.07016        -0.02621        19.96644

              Principal moments of inertia (amu*A**2): 
               4.12038000          18.75574000          19.96715000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation                3000.79644       The ln(Q)    8.00663

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       18.89164  (cal/mol*K)     79.04264    (J/mol*K)         0.00003011  (hartree/K)
  G rotation       -4.74382   (kcal/mol)    -19.84812     (kJ/mol)        -0.00755974    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    28.03130   amu

              *****      Translation thermodynamic functions     ******

  Q translation             5833377.76472       The ln(Q)   15.57911
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       35.92692  (cal/mol*K)    150.31824    (J/mol*K)         0.00005725  (hartree/K)
  G translation       -9.23040   (kcal/mol)    -38.61998     (kJ/mol)        -0.01470956    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   12
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   12


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      447.135         437.298         yes       1.13792    0.625        0.798        0.835        0.549        1.389
  2      636.784         622.775         yes       1.05210    0.890        0.983        0.412        0.860        0.984
  3      965.886         944.637         yes       1.01059    1.350        1.379        0.117        1.344        0.442
  4     1138.872        1113.816         yes       1.00465    1.592        1.607        0.059        1.590        0.268
  5     1264.724        1236.900         yes       1.00256    1.768        1.777        0.035        1.767        0.182
  6     1310.432        1281.602         yes       1.00207    1.832        1.840        0.029        1.831        0.157
  7     1354.563        1324.762         yes       1.00168    1.894        1.900        0.025        1.893        0.136
  8     1515.049        1481.718         yes       1.00079    2.118        2.122        0.013        2.118        0.080
  9     2856.003        2793.171         yes       1.00000    3.993        3.993        0.000        3.993        0.001
 10     2951.944        2887.001         yes       1.00000    4.127        4.127        0.000        4.127        0.000
 11     3038.262        2971.421         yes       1.00000    4.248        4.248        0.000        4.248        0.000
 12     3125.649        3056.885         yes       1.00000    4.370        4.370        0.000        4.370        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   1.22417       The ln(Q)    0.20226
    H vibration       29.14369   (kcal/mol)    121.93718     (kJ/mol)         0.04644338    (hartree)
    U vibration       29.14369   (kcal/mol)    121.93718     (kJ/mol)         0.04644338    (hartree)
           ZPE        28.80871   (kcal/mol)    120.53565     (kJ/mol)         0.04590956    (hartree)
    S vibration        1.52544  (cal/mol*K)      6.38244    (J/mol*K)         0.00000243  (hartree/K)
   Cv vibration        3.63976  (cal/mol*K)     15.22876    (J/mol*K)         0.00000580  (hartree/K)
    G vibration       28.68888   (kcal/mol)    120.03426     (kJ/mol)         0.04571859    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total         21428738204.42395       The ln(Q)   31.36047
        H total       31.51363   (kcal/mol)    131.85302     (kJ/mol)         0.05022012    (hartree)
        U total       30.92114   (kcal/mol)    129.37406     (kJ/mol)         0.04927593    (hartree)
       Cv total        9.60138  (cal/mol*K)     40.17218    (J/mol*K)         0.00001530  (hartree/K)
           ZPE        28.80871   (kcal/mol)    120.53565     (kJ/mol)         0.04590956    (hartree)
        S total       56.34400  (cal/mol*K)    235.74331    (J/mol*K)         0.00008979  (hartree/K)
        G total       15.30715   (kcal/mol)     64.04511     (kJ/mol)         0.02439347    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.04927593 (hartree)
                       Thermal correction to Enthalpy :   0.05022012 
              Thermal correction to Gibbs Free Energy :   0.02344929 (hartree)
              ZPE correction to the Electronic Energy :   0.04590956 (hartree)


