The thermochemical analysis of the Molecule:                     C4H8

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000       0.0000000000       0.6640200000       0.6615820000
  C     6   12.00000       0.0000000000      -0.6640200000       0.6615820000
  H     1    1.00782       0.0000000000       1.1609360000       1.6277610000
  H     1    1.00782       0.0000000000      -1.1609360000       1.6277610000
  C     6   12.00000       0.0000000000       1.5810550000      -0.5208700000
  C     6   12.00000       0.0000000000      -1.5810550000      -0.5208700000
  H     1    1.00782       0.0000000000       1.0493600000      -1.4712080000
  H     1    1.00782       0.8773450000       2.2328180000      -0.5004140000
  H     1    1.00782      -0.8773450000       2.2328180000      -0.5004140000
  H     1    1.00782       0.0000000000      -1.0493600000      -1.4712080000
  H     1    1.00782      -0.8773450000      -2.2328180000      -0.5004140000
  H     1    1.00782       0.8773450000      -2.2328180000      -0.5004140000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           2
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          30
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
          0.00000000      0.00000000      0.02988311

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x       123.28871         0.00000         0.00000
    y         0.00000        30.78183        -0.00000
    z         0.00000        -0.00000        98.71294

              Principal moments of inertia (amu*A**2): 
              98.71294000          30.78183000         123.28871000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation               23378.08566       The ln(Q)   10.05955

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       22.97122  (cal/mol*K)     96.11160    (J/mol*K)         0.00003661  (hartree/K)
  G rotation       -5.96014   (kcal/mol)    -24.93723     (kJ/mol)        -0.00949808    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    56.06260   amu

              *****      Translation thermodynamic functions     ******

  Q translation            16499283.89863       The ln(Q)   16.61883
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       37.99306  (cal/mol*K)    158.96297    (J/mol*K)         0.00006055  (hartree/K)
  G translation       -9.84642   (kcal/mol)    -41.19741     (kJ/mol)        -0.01569125    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   30
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   30


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      118.482         115.876         yes       2.33469    0.166        0.608        3.168       -0.337        1.936
  2      124.012         121.284         yes       2.25710    0.173        0.609        3.080       -0.309        1.931
  3      312.783         305.902         yes       1.29619    0.437        0.696        1.384        0.284        1.663
  4      402.345         393.494         yes       1.17611    0.563        0.761        0.987        0.466        1.484
  5      577.060         564.365         yes       1.07026    0.807        0.920        0.515        0.767        1.108
  6      705.182         689.668         yes       1.03719    0.986        1.059        0.319        0.964        0.849
  7      881.353         861.963         yes       1.01586    1.232        1.271        0.162        1.223        0.554
  8      990.293         968.506         yes       1.00943    1.385        1.411        0.106        1.379        0.413
  9     1018.669         996.258         yes       1.00823    1.424        1.448        0.095        1.419        0.381
 10     1040.160        1017.276         yes       1.00743    1.454        1.476        0.087        1.450        0.359
 11     1070.465        1046.915         yes       1.00644    1.497        1.516        0.077        1.493        0.329
 12     1075.421        1051.762         yes       1.00629    1.504        1.522        0.076        1.500        0.324
 13     1167.173        1141.495         yes       1.00407    1.632        1.645        0.053        1.629        0.246
 14     1305.101        1276.389         yes       1.00212    1.825        1.832        0.030        1.823        0.160
 15     1396.638        1365.912         yes       1.00137    1.953        1.958        0.021        1.952        0.119
 16     1427.349        1395.948         yes       1.00119    1.996        2.000        0.018        1.995        0.107
 17     1449.693        1417.799         yes       1.00107    2.027        2.031        0.017        2.026        0.100
 18     1484.916        1452.248         yes       1.00091    2.076        2.080        0.014        2.076        0.088
 19     1489.727        1456.953         yes       1.00089    2.083        2.087        0.014        2.082        0.087
 20     1494.446        1461.569         yes       1.00087    2.089        2.093        0.014        2.089        0.086
 21     1504.718        1471.615         yes       1.00082    2.104        2.107        0.013        2.103        0.083
 22     1765.177        1726.343         yes       1.00024    2.468        2.469        0.004        2.468        0.033
 23     3045.061        2978.069         yes       1.00000    4.257        4.257        0.000        4.257        0.000
 24     3047.933        2980.879         yes       1.00000    4.261        4.261        0.000        4.261        0.000
 25     3098.222        3030.062         yes       1.00000    4.332        4.332        0.000        4.332        0.000
 26     3098.494        3030.327         yes       1.00000    4.332        4.332        0.000        4.332        0.000
 27     3136.108        3067.114         yes       1.00000    4.385        4.385        0.000        4.385        0.000
 28     3150.979        3081.658         yes       1.00000    4.405        4.405        0.000        4.405        0.000
 29     3152.910        3083.546         yes       1.00000    4.408        4.408        0.000        4.408        0.000
 30     3174.425        3104.588         yes       1.00000    4.438        4.438        0.000        4.438        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   9.53492       The ln(Q)    2.25496
    H vibration       68.41945   (kcal/mol)    286.26697     (kJ/mol)         0.10903323    (hartree)
    U vibration       68.41945   (kcal/mol)    286.26697     (kJ/mol)         0.10903323    (hartree)
           ZPE        66.69779   (kcal/mol)    279.06354     (kJ/mol)         0.10628959    (hartree)
    S vibration       10.25555  (cal/mol*K)     42.90921    (J/mol*K)         0.00001634  (hartree/K)
   Cv vibration       12.44178  (cal/mol*K)     52.05639    (J/mol*K)         0.00001983  (hartree/K)
    G vibration       65.36176   (kcal/mol)    273.47358     (kJ/mol)         0.10416049    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total       3677827097531.34521       The ln(Q)   35.49262
        H total       70.78939   (kcal/mol)    296.18281     (kJ/mol)         0.11280997    (hartree)
        U total       70.19690   (kcal/mol)    293.70385     (kJ/mol)         0.11186579    (hartree)
       Cv total       18.40340  (cal/mol*K)     76.99981    (J/mol*K)         0.00002933  (hartree/K)
           ZPE        66.69779   (kcal/mol)    279.06354     (kJ/mol)         0.10628959    (hartree)
        S total       71.21983  (cal/mol*K)    297.98377    (J/mol*K)         0.00011350  (hartree/K)
        G total       50.14768   (kcal/mol)    209.81790     (kJ/mol)         0.07991535    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.11186579 (hartree)
                       Thermal correction to Enthalpy :   0.11280997 
              Thermal correction to Gibbs Free Energy :   0.07897116 (hartree)
              ZPE correction to the Electronic Energy :   0.10628959 (hartree)


