The thermochemical analysis of the Molecule:                     C5H6

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000       0.0000000000       0.0000000000       1.2104690000
  C     6   12.00000       0.0000000000      -1.1723460000       0.2796950000
  C     6   12.00000       0.0000000000       1.1723460000       0.2796950000
  C     6   12.00000       0.0000010000      -0.7320980000      -0.9847590000
  C     6   12.00000      -0.0000010000       0.7320980000      -0.9847590000
  H     1    1.00782      -0.8766820000       0.0000000000       1.8678420000
  H     1    1.00782       0.8766820000       0.0000000000       1.8678420000
  H     1    1.00782       0.0000000000      -2.2021480000       0.6051580000
  H     1    1.00782       0.0000000000       2.2021480000       0.6051580000
  H     1    1.00782       0.0000020000      -1.3467970000      -1.8740200000
  H     1    1.00782      -0.0000020000       1.3467970000      -1.8740200000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           2
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          27
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
         -0.00000000      0.00000000     -0.01799589

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x       116.84186         0.00002        -0.00000
    y         0.00002        59.11141         0.00000
    z        -0.00000         0.00000        60.82879

              Principal moments of inertia (amu*A**2): 
             116.84186000          59.11141000          60.82879000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation               24757.25553       The ln(Q)   10.11687

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       23.08513  (cal/mol*K)     96.58818    (J/mol*K)         0.00003679  (hartree/K)
  G rotation       -5.99410   (kcal/mol)    -25.07933     (kJ/mol)        -0.00955220    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    66.04695   amu

              *****      Translation thermodynamic functions     ******

  Q translation            21097665.06043       The ln(Q)   16.86467
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       38.48161  (cal/mol*K)    161.00704    (J/mol*K)         0.00006132  (hartree/K)
  G translation       -9.99208   (kcal/mol)    -41.80685     (kJ/mol)        -0.01592337    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   27
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   27


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      348.170         340.510         yes       1.23971    0.487        0.720        1.210        0.359        1.595
  2      530.994         519.313         yes       1.08884    0.742        0.874        0.612        0.692        1.207
  3      686.575         671.470         yes       1.04075    0.960        1.038        0.342        0.936        0.885
  4      729.311         713.266         yes       1.03306    1.020        1.087        0.291        1.000        0.804
  5      821.930         803.847         yes       1.02111    1.149        1.198        0.204        1.137        0.644
  6      821.998         803.914         yes       1.02110    1.149        1.198        0.204        1.137        0.644
  7      925.935         905.564         yes       1.01281    1.295        1.328        0.137        1.287        0.493
  8      938.287         917.645         yes       1.01208    1.312        1.344        0.130        1.305        0.476
  9      973.999         952.571         yes       1.01019    1.362        1.390        0.113        1.356        0.432
 10      978.742         957.210         yes       1.00996    1.368        1.396        0.111        1.363        0.426
 11      981.691         960.094         yes       1.00982    1.373        1.399        0.110        1.367        0.423
 12     1021.878         999.396         yes       1.00811    1.429        1.452        0.094        1.424        0.378
 13     1119.936        1095.297         yes       1.00509    1.566        1.582        0.064        1.563        0.284
 14     1136.369        1111.368         yes       1.00471    1.589        1.604        0.060        1.586        0.270
 15     1139.528        1114.458         yes       1.00464    1.593        1.608        0.059        1.590        0.268
 16     1282.162        1253.954         yes       1.00236    1.793        1.801        0.033        1.791        0.172
 17     1333.209        1303.879         yes       1.00185    1.864        1.871        0.027        1.863        0.146
 18     1409.311        1378.306         yes       1.00129    1.970        1.975        0.020        1.970        0.114
 19     1424.713        1393.369         yes       1.00120    1.992        1.997        0.018        1.991        0.108
 20     1586.722        1551.815         yes       1.00056    2.218        2.221        0.009        2.218        0.062
 21     1669.648        1632.915         yes       1.00038    2.334        2.336        0.007        2.334        0.047
 22     3047.167        2980.129         yes       1.00000    4.260        4.260        0.000        4.260        0.000
 23     3079.862        3012.105         yes       1.00000    4.306        4.306        0.000        4.306        0.000
 24     3218.489        3147.682         yes       1.00000    4.500        4.500        0.000        4.500        0.000
 25     3228.191        3157.171         yes       1.00000    4.513        4.513        0.000        4.513        0.000
 26     3246.232        3174.815         yes       1.00000    4.539        4.539        0.000        4.539        0.000
 27     3253.098        3181.530         yes       1.00000    4.548        4.548        0.000        4.548        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   1.64691       The ln(Q)    0.49890
    H vibration       58.08405   (kcal/mol)    243.02365     (kJ/mol)         0.09256274    (hartree)
    U vibration       58.08405   (kcal/mol)    243.02365     (kJ/mol)         0.09256274    (hartree)
           ZPE        57.23090   (kcal/mol)    239.45407     (kJ/mol)         0.09120316    (hartree)
    S vibration        3.85291  (cal/mol*K)     16.12057    (J/mol*K)         0.00000614  (hartree/K)
   Cv vibration        9.88045  (cal/mol*K)     41.33980    (J/mol*K)         0.00001575  (hartree/K)
    G vibration       56.93530   (kcal/mol)    238.21731     (kJ/mol)         0.09073210    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total        860217106307.15137       The ln(Q)   34.22825
        H total       60.45399   (kcal/mol)    252.93949     (kJ/mol)         0.09633948    (hartree)
        U total       59.86150   (kcal/mol)    250.46053     (kJ/mol)         0.09539529    (hartree)
       Cv total       15.84207  (cal/mol*K)     66.28322    (J/mol*K)         0.00002525  (hartree/K)
           ZPE        57.23090   (kcal/mol)    239.45407     (kJ/mol)         0.09120316    (hartree)
        S total       65.41964  (cal/mol*K)    273.71579    (J/mol*K)         0.00010425  (hartree/K)
        G total       41.54161   (kcal/mol)    173.81009     (kJ/mol)         0.06620071    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.09539529 (hartree)
                       Thermal correction to Enthalpy :   0.09633948 
              Thermal correction to Gibbs Free Energy :   0.06525652 (hartree)
              ZPE correction to the Electronic Energy :   0.09120316 (hartree)


