The thermochemical analysis of the Molecule:                       H2

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  H     1    1.00782       0.0000000000       0.0000000000       0.3720780000
  H     1    1.00782       0.0000000000       0.0000000000      -0.3720780000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           2
               The frequencies scale coefficient:     0.97800
                          The frequencies number:           1
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
          0.00000000      0.00000000      0.00000000

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x         0.27905         0.00000         0.00000
    y         0.00000         0.27905         0.00000
    z         0.00000         0.00000         0.00000

              Principal moments of inertia (amu*A**2): 
               0.27905000           0.27905000           0.00000000

                   The molecule was found to be linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation                   1.71514       The ln(Q)    0.53949

  H rotation        0.59249   (kcal/mol)      2.47896     (kJ/mol)         0.00094419    (hartree)
  U rotation        0.59249   (kcal/mol)      2.47896     (kJ/mol)         0.00094419    (hartree)
 Cv rotation        1.98721  (cal/mol*K)      8.31447    (J/mol*K)         0.00000317  (hartree/K)
  S rotation        3.05929  (cal/mol*K)     12.80007    (J/mol*K)         0.00000488  (hartree/K)
  G rotation       -0.31964   (kcal/mol)     -1.33738     (kJ/mol)        -0.00050938    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:     2.01565   amu

              *****      Translation thermodynamic functions     ******

  Q translation              112480.67843       The ln(Q)   11.63054
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       28.08030  (cal/mol*K)    117.48796    (J/mol*K)         0.00004475  (hartree/K)
  G translation       -6.89093   (kcal/mol)    -28.83163     (kJ/mol)        -0.01098138    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:    1
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:    1


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1     4438.216        4340.575         yes       1.00000    6.205        6.205        0.000        6.205        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   1.00000       The ln(Q)    0.00000
    H vibration        6.20516   (kcal/mol)     25.96240     (kJ/mol)         0.00988855    (hartree)
    U vibration        6.20516   (kcal/mol)     25.96240     (kJ/mol)         0.00988855    (hartree)
           ZPE         6.20516   (kcal/mol)     25.96240     (kJ/mol)         0.00988855    (hartree)
    S vibration        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   Cv vibration        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
    G vibration        6.20516   (kcal/mol)     25.96240     (kJ/mol)         0.00988855    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total              192919.63348       The ln(Q)   23.26107
        H total        8.27886   (kcal/mol)     34.63876     (kJ/mol)         0.01319320    (hartree)
        U total        7.68638   (kcal/mol)     32.15980     (kJ/mol)         0.01224901    (hartree)
       Cv total        4.96802  (cal/mol*K)     20.78618    (J/mol*K)         0.00000792  (hartree/K)
           ZPE         6.20516   (kcal/mol)     25.96240     (kJ/mol)         0.00988855    (hartree)
        S total       31.13959  (cal/mol*K)    130.28802    (J/mol*K)         0.00004962  (hartree/K)
        G total       -0.41292   (kcal/mol)     -1.72765     (kJ/mol)        -0.00065803    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.01224901 (hartree)
                       Thermal correction to Enthalpy :   0.01319320 
              Thermal correction to Gibbs Free Energy :  -0.00160221 (hartree)
              ZPE correction to the Electronic Energy :   0.00988855 (hartree)


