The thermochemical analysis of the Molecule:                     C4H6

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000       0.6036690000       1.7365340000       0.0000000000
  C     6   12.00000       0.6036690000       0.4076500000       0.0000000000
  C     6   12.00000      -0.6036690000      -0.4076500000       0.0000000000
  H     1    1.00782       1.5252160000       2.3037050000       0.0000000000
  H     1    1.00782      -0.3229280000       2.2999990000       0.0000000000
  H     1    1.00782       1.5485990000      -0.1289620000       0.0000000000
  C     6   12.00000      -0.6036690000      -1.7365340000       0.0000000000
  H     1    1.00782      -1.5252160000      -2.3037050000       0.0000000000
  H     1    1.00782       0.3229280000      -2.2999990000       0.0000000000
  H     1    1.00782      -1.5485990000       0.1289620000       0.0000000000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           2
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          24
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
          0.00000000     -0.00000000      0.00000000

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x        97.75496       -36.24770         0.00000
    y       -36.24770        27.22500         0.00000
    z         0.00000         0.00000       124.97996

              Principal moments of inertia (amu*A**2): 
             113.06186000          11.91810000         124.97996000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation               15674.54180       The ln(Q)    9.65979

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       22.17681  (cal/mol*K)     92.78779    (J/mol*K)         0.00003534  (hartree/K)
  G rotation       -5.72329   (kcal/mol)    -23.94624     (kJ/mol)        -0.00912063    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    54.04695   amu

              *****      Translation thermodynamic functions     ******

  Q translation            15617518.49231       The ln(Q)   16.56390
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       37.88392  (cal/mol*K)    158.50630    (J/mol*K)         0.00006037  (hartree/K)
  G translation       -9.81388   (kcal/mol)    -41.06125     (kJ/mol)        -0.01563939    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   24
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   24


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      164.839         161.213         yes       1.84960    0.230        0.622        2.536       -0.134        1.890
  2      303.007         296.341         yes       1.31458    0.424        0.690        1.437        0.262        1.681
  3      525.153         513.599         yes       1.09155    0.734        0.869        0.625        0.682        1.220
  4      542.178         530.250         yes       1.08389    0.758        0.885        0.587        0.710        1.183
  5      792.032         774.607         yes       1.02438    1.107        1.161        0.229        1.093        0.694
  6      906.484         886.542         yes       1.01406    1.267        1.303        0.147        1.259        0.519
  7      962.835         941.653         yes       1.01074    1.346        1.375        0.118        1.340        0.446
  8      964.147         942.935         yes       1.01068    1.348        1.377        0.118        1.342        0.444
  9     1013.087         990.799         yes       1.00846    1.416        1.440        0.097        1.411        0.387
 10     1018.629         996.219         yes       1.00824    1.424        1.448        0.095        1.419        0.381
 11     1065.012        1041.582         yes       1.00661    1.489        1.509        0.079        1.485        0.334
 12     1236.658        1209.452         yes       1.00293    1.729        1.739        0.040        1.727        0.199
 13     1327.377        1298.174         yes       1.00191    1.856        1.863        0.028        1.855        0.149
 14     1330.265        1300.999         yes       1.00188    1.860        1.867        0.027        1.859        0.148
 15     1426.678        1395.291         yes       1.00119    1.995        1.999        0.018        1.994        0.108
 16     1482.064        1449.458         yes       1.00092    2.072        2.076        0.015        2.072        0.089
 17     1683.263        1646.232         yes       1.00035    2.353        2.355        0.006        2.353        0.045
 18     1747.127        1708.691         yes       1.00026    2.443        2.444        0.005        2.443        0.035
 19     3154.323        3084.928         yes       1.00000    4.410        4.410        0.000        4.410        0.000
 20     3157.573        3088.107         yes       1.00000    4.415        4.415        0.000        4.415        0.000
 21     3165.232        3095.597         yes       1.00000    4.425        4.425        0.000        4.425        0.000
 22     3170.364        3100.616         yes       1.00000    4.433        4.433        0.000        4.433        0.000
 23     3250.294        3178.787         yes       1.00000    4.544        4.544        0.000        4.544        0.000
 24     3250.496        3178.985         yes       1.00000    4.545        4.545        0.000        4.545        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   3.15390       The ln(Q)    1.14864
    H vibration       53.79397   (kcal/mol)    225.07397     (kJ/mol)         0.08572607    (hartree)
    U vibration       53.79397   (kcal/mol)    225.07397     (kJ/mol)         0.08572607    (hartree)
           ZPE        52.62405   (kcal/mol)    220.17901     (kJ/mol)         0.08386168    (hartree)
    S vibration        6.20652  (cal/mol*K)     25.96810    (J/mol*K)         0.00000989  (hartree/K)
   Cv vibration        9.95073  (cal/mol*K)     41.63385    (J/mol*K)         0.00001586  (hartree/K)
    G vibration       51.94349   (kcal/mol)    217.33158     (kJ/mol)         0.08277715    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total        772067116717.86389       The ln(Q)   34.27645
        H total       56.16391   (kcal/mol)    234.98981     (kJ/mol)         0.08950281    (hartree)
        U total       55.57143   (kcal/mol)    232.51085     (kJ/mol)         0.08855863    (hartree)
       Cv total       15.91235  (cal/mol*K)     66.57727    (J/mol*K)         0.00002536  (hartree/K)
           ZPE        52.62405   (kcal/mol)    220.17901     (kJ/mol)         0.08386168    (hartree)
        S total       66.26725  (cal/mol*K)    277.26219    (J/mol*K)         0.00010560  (hartree/K)
        G total       36.99882   (kcal/mol)    154.80305     (kJ/mol)         0.05896131    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.08855863 (hartree)
                       Thermal correction to Enthalpy :   0.08950281 
              Thermal correction to Gibbs Free Energy :   0.05801713 (hartree)
              ZPE correction to the Electronic Energy :   0.08386168 (hartree)


