The thermochemical analysis of the Molecule:                     C4H2

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000       0.0000000000       0.0000000000       0.6862740000
  C     6   12.00000       0.0000000000       0.0000000000      -0.6862740000
  C     6   12.00000       0.0000000000       0.0000000000       1.8861720000
  C     6   12.00000       0.0000000000       0.0000000000      -1.8861720000
  H     1    1.00782       0.0000000000       0.0000000000       2.9498770000
  H     1    1.00782       0.0000000000       0.0000000000      -2.9498770000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           2
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          13
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
          0.00000000      0.00000000      0.00000000

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x       114.22653         0.00000         0.00000
    y         0.00000       114.22653         0.00000
    z         0.00000         0.00000         0.00000

              Principal moments of inertia (amu*A**2): 
             114.22653000         114.22653000           0.00000000

                   The molecule was found to be linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation                 702.07320       The ln(Q)    6.55404

  H rotation        0.59249   (kcal/mol)      2.47896     (kJ/mol)         0.00094419    (hartree)
  U rotation        0.59249   (kcal/mol)      2.47896     (kJ/mol)         0.00094419    (hartree)
 Cv rotation        1.98721  (cal/mol*K)      8.31447    (J/mol*K)         0.00000317  (hartree/K)
  S rotation       15.01143  (cal/mol*K)     62.80784    (J/mol*K)         0.00002392  (hartree/K)
  G rotation       -3.88317   (kcal/mol)    -16.24720     (kJ/mol)        -0.00618822    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    50.01565   amu

              *****      Translation thermodynamic functions     ******

  Q translation            13903179.14219       The ln(Q)   16.44763
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       37.65285  (cal/mol*K)    157.53953    (J/mol*K)         0.00006000  (hartree/K)
  G translation       -9.74498   (kcal/mol)    -40.77301     (kJ/mol)        -0.01552961    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   13
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   13


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      237.396         232.173         yes       1.48401    0.332        0.653        1.862        0.098        1.792
  2      237.396         232.173         yes       1.48401    0.332        0.653        1.862        0.098        1.792
  3      536.104         524.310         yes       1.08654    0.750        0.879        0.600        0.700        1.196
  4      536.104         524.310         yes       1.08654    0.750        0.879        0.600        0.700        1.196
  5      696.624         681.298         yes       1.03879    0.974        1.050        0.329        0.951        0.865
  6      696.624         681.298         yes       1.03879    0.974        1.050        0.329        0.951        0.865
  7      701.721         686.283         yes       1.03783    0.981        1.055        0.323        0.959        0.856
  8      701.721         686.283         yes       1.03783    0.981        1.055        0.323        0.959        0.856
  9      910.658         890.624         yes       1.01379    1.273        1.308        0.145        1.265        0.513
 10     2147.441        2100.197         yes       1.00004    3.002        3.003        0.001        3.002        0.008
 11     2332.774        2281.453         yes       1.00002    3.262        3.262        0.000        3.261        0.004
 12     3478.420        3401.895         yes       1.00000    4.863        4.863        0.000        4.863        0.000
 13     3478.949        3402.412         yes       1.00000    4.864        4.864        0.000        4.864        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   3.06368       The ln(Q)    1.11962
    H vibration       24.57441   (kcal/mol)    102.81935     (kJ/mol)         0.03916179    (hartree)
    U vibration       24.57441   (kcal/mol)    102.81935     (kJ/mol)         0.03916179    (hartree)
           ZPE        23.33734   (kcal/mol)     97.64344     (kJ/mol)         0.03719039    (hartree)
    S vibration        6.37406  (cal/mol*K)     26.66908    (J/mol*K)         0.00001016  (hartree/K)
   Cv vibration        9.94337  (cal/mol*K)     41.60308    (J/mol*K)         0.00001585  (hartree/K)
    G vibration       22.67399   (kcal/mol)     94.86796     (kJ/mol)         0.03613327    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total         29904709339.83199       The ln(Q)   34.01487
        H total       26.64811   (kcal/mol)    111.49571     (kJ/mol)         0.04246643    (hartree)
        U total       26.05563   (kcal/mol)    109.01675     (kJ/mol)         0.04152225    (hartree)
       Cv total       14.91139  (cal/mol*K)     62.38926    (J/mol*K)         0.00002376  (hartree/K)
           ZPE        23.33734   (kcal/mol)     97.64344     (kJ/mol)         0.03719039    (hartree)
        S total       59.03835  (cal/mol*K)    247.01645    (J/mol*K)         0.00009408  (hartree/K)
        G total        9.63832   (kcal/mol)     40.32671     (kJ/mol)         0.01535962    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.04152225 (hartree)
                       Thermal correction to Enthalpy :   0.04246643 
              Thermal correction to Gibbs Free Energy :   0.01441543 (hartree)
              ZPE correction to the Electronic Energy :   0.03719039 (hartree)


