The thermochemical analysis of the Molecule:                     C7H8

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000       2.4109270000       0.0000000000       0.0092040000
  C     6   12.00000       0.9073630000       0.0000010000      -0.0119810000
  C     6   12.00000       0.1931960000       1.1942530000      -0.0088890000
  C     6   12.00000       0.1931970000      -1.1942520000      -0.0088890000
  C     6   12.00000      -1.1930860000       1.1972670000       0.0020440000
  C     6   12.00000      -1.1930850000      -1.1972680000       0.0020440000
  C     6   12.00000      -1.8922690000       0.0000000000       0.0085210000
  H     1    1.00782       2.7832790000      -0.0000310000       1.0368350000
  H     1    1.00782       2.8147050000      -0.8834520000      -0.4864890000
  H     1    1.00782       2.8147050000       0.8834820000      -0.4864370000
  H     1    1.00782       0.7312010000       2.1355840000      -0.0175320000
  H     1    1.00782       0.7312020000      -2.1355840000      -0.0175330000
  H     1    1.00782      -1.7288630000       2.1384500000       0.0022150000
  H     1    1.00782      -1.7288620000      -2.1384510000       0.0022140000
  H     1    1.00782      -2.9748280000      -0.0000010000       0.0144030000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           1
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          39
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
         -0.03710092      0.00000010     -0.00051381

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x        90.18294         0.00000         0.08744
    y         0.00000       198.89512        -0.00000
    z         0.08744        -0.00000       285.94435

              Principal moments of inertia (amu*A**2): 
              90.18291000         285.94439000         198.89512000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation              173004.73334       The ln(Q)   12.06107

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       26.94866  (cal/mol*K)    112.75318    (J/mol*K)         0.00004295  (hartree/K)
  G rotation       -7.14601   (kcal/mol)    -29.89892     (kJ/mol)        -0.01138789    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    92.06260   amu

              *****      Translation thermodynamic functions     ******

  Q translation            34720030.39526       The ln(Q)   17.36283
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       39.47154  (cal/mol*K)    165.14893    (J/mol*K)         0.00006290  (hartree/K)
  G translation      -10.28723   (kcal/mol)    -43.04175     (kJ/mol)        -0.01639372    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   39
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   39


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1       33.189          32.459         yes       6.89724    0.046        0.594        5.673       -1.098        1.983
  2      211.419         206.768         yes       1.58401    0.296        0.641        2.072        0.023        1.830
  3      350.862         343.143         yes       1.23597    0.491        0.722        1.198        0.365        1.589
  4      419.139         409.918         yes       1.16053    0.586        0.774        0.927        0.498        1.449
  5      481.406         470.815         yes       1.11496    0.673        0.828        0.735        0.609        1.315
  6      534.369         522.612         yes       1.08731    0.747        0.878        0.604        0.698        1.200
  7      641.393         627.283         yes       1.05093    0.897        0.988        0.405        0.867        0.975
  8      720.379         704.530         yes       1.03453    1.007        1.077        0.301        0.987        0.821
  9      754.750         738.146         yes       1.02921    1.055        1.117        0.264        1.038        0.758
 10      809.889         792.072         yes       1.02237    1.132        1.183        0.214        1.119        0.664
 11      872.335         853.143         yes       1.01656    1.220        1.260        0.168        1.210        0.567
 12      926.640         906.254         yes       1.01277    1.296        1.329        0.136        1.288        0.492
 13      991.339         969.529         yes       1.00938    1.386        1.412        0.106        1.380        0.412
 14     1003.648         981.568         yes       1.00884    1.403        1.428        0.101        1.398        0.398
 15     1009.794         987.578         yes       1.00859    1.412        1.436        0.098        1.407        0.391
 16     1028.154        1005.534         yes       1.00787    1.437        1.460        0.091        1.433        0.371
 17     1065.509        1042.068         yes       1.00659    1.490        1.509        0.079        1.486        0.333
 18     1071.395        1047.824         yes       1.00641    1.498        1.517        0.077        1.494        0.328
 19     1123.282        1098.569         yes       1.00501    1.570        1.586        0.063        1.568        0.281
 20     1188.147        1162.008         yes       1.00368    1.661        1.673        0.048        1.659        0.231
 21     1215.696        1188.951         yes       1.00323    1.700        1.711        0.043        1.698        0.212
 22     1246.991        1219.557         yes       1.00279    1.743        1.753        0.038        1.742        0.192
 23     1332.003        1302.699         yes       1.00186    1.862        1.869        0.027        1.861        0.147
 24     1366.173        1336.118         yes       1.00159    1.910        1.916        0.023        1.909        0.131
 25     1421.116        1389.852         yes       1.00122    1.987        1.992        0.019        1.986        0.110
 26     1479.896        1447.338         yes       1.00093    2.069        2.073        0.015        2.069        0.090
 27     1494.780        1461.895         yes       1.00086    2.090        2.093        0.014        2.089        0.086
 28     1513.788        1480.485         yes       1.00079    2.116        2.120        0.013        2.116        0.080
 29     1549.077        1514.997         yes       1.00067    2.166        2.169        0.011        2.165        0.071
 30     1660.016        1623.496         yes       1.00040    2.321        2.323        0.007        2.321        0.048
 31     1683.389        1646.355         yes       1.00035    2.354        2.355        0.006        2.353        0.044
 32     3051.609        2984.474         yes       1.00000    4.267        4.267        0.000        4.267        0.000
 33     3116.337        3047.778         yes       1.00000    4.357        4.357        0.000        4.357        0.000
 34     3139.260        3070.196         yes       1.00000    4.389        4.389        0.000        4.389        0.000
 35     3183.239        3113.208         yes       1.00000    4.451        4.451        0.000        4.451        0.000
 36     3184.713        3114.649         yes       1.00000    4.453        4.453        0.000        4.453        0.000
 37     3197.867        3127.514         yes       1.00000    4.471        4.471        0.000        4.471        0.000
 38     3207.366        3136.804         yes       1.00000    4.484        4.484        0.000        4.484        0.000
 39     3219.631        3148.800         yes       1.00000    4.501        4.501        0.000        4.501        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                  24.01913       The ln(Q)    3.17885
    H vibration       81.15825   (kcal/mol)    339.56614     (kJ/mol)         0.12933379    (hartree)
    U vibration       81.15825   (kcal/mol)    339.56614     (kJ/mol)         0.12933379    (hartree)
           ZPE        78.99382   (kcal/mol)    330.51016     (kJ/mol)         0.12588456    (hartree)
    S vibration       13.57657  (cal/mol*K)     56.80435    (J/mol*K)         0.00002164  (hartree/K)
   Cv vibration       17.59985  (cal/mol*K)     73.63776    (J/mol*K)         0.00002805  (hartree/K)
    G vibration       77.11040   (kcal/mol)    322.62992     (kJ/mol)         0.12288314    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total     144276419693693.34375       The ln(Q)   37.90451
        H total       83.52820   (kcal/mol)    349.48198     (kJ/mol)         0.13311054    (hartree)
        U total       82.93571   (kcal/mol)    347.00302     (kJ/mol)         0.13216635    (hartree)
       Cv total       23.56147  (cal/mol*K)     98.58118    (J/mol*K)         0.00003755  (hartree/K)
           ZPE        78.99382   (kcal/mol)    330.51016     (kJ/mol)         0.12588456    (hartree)
        S total       79.99676  (cal/mol*K)    334.70646    (J/mol*K)         0.00012748  (hartree/K)
        G total       60.26965   (kcal/mol)    252.16821     (kJ/mol)         0.09604571    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.13216635 (hartree)
                       Thermal correction to Enthalpy :   0.13311054 
              Thermal correction to Gibbs Free Energy :   0.09510153 (hartree)
              ZPE correction to the Electronic Energy :   0.12588456 (hartree)


