The thermochemical analysis of the Molecule:                     C6H8

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000       0.2383830000       0.7911310000       0.0000000000
  C     6   12.00000       0.2322360000      -0.1501560000       1.1696510000
  C     6   12.00000       0.2322360000      -0.1501560000      -1.1696510000
  C     6   12.00000       0.2322360000      -1.4145190000       0.7328500000
  C     6   12.00000       0.2322360000      -1.4145190000      -0.7328500000
  H     1    1.00782       1.1856850000       1.3481270000       0.0000000000
  C     6   12.00000      -0.9148410000       1.7971300000       0.0000000000
  H     1    1.00782       0.2267420000       0.1786910000       2.1992610000
  H     1    1.00782       0.2267420000       0.1786910000      -2.1992610000
  H     1    1.00782       0.2315530000      -2.3036680000       1.3478930000
  H     1    1.00782       0.2315530000      -2.3036680000      -1.3478930000
  H     1    1.00782      -1.8731870000       1.2754840000       0.0000000000
  H     1    1.00782      -0.8720000000       2.4364390000      -0.8831800000
  H     1    1.00782      -0.8720000000       2.4364390000       0.8831800000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           1
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          36
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
          0.01877363     -0.04023263      0.00000000

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x       181.60400        32.19933        -0.00000
    y        32.19933        80.69036         0.00000
    z        -0.00000         0.00000       140.88008

              Principal moments of inertia (amu*A**2): 
             191.00273000          71.29163000         140.88008000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation              105805.16508       The ln(Q)   11.56935

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       25.97151  (cal/mol*K)    108.66479    (J/mol*K)         0.00004139  (hartree/K)
  G rotation       -6.85468   (kcal/mol)    -28.67997     (kJ/mol)        -0.01092361    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    80.06260   amu

              *****      Translation thermodynamic functions     ******

  Q translation            28157868.54610       The ln(Q)   17.15334
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       39.05524  (cal/mol*K)    163.40713    (J/mol*K)         0.00006224  (hartree/K)
  G translation      -10.16311   (kcal/mol)    -42.52244     (kJ/mol)        -0.01619593    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   36
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   36


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      165.988         162.336         yes       1.84114    0.232        0.622        2.522       -0.130        1.889
  2      258.355         252.672         yes       1.41931    0.361        0.664        1.712        0.154        1.758
  3      295.559         289.056         yes       1.32954    0.413        0.686        1.479        0.244        1.694
  4      548.528         536.460         yes       1.08121    0.767        0.891        0.573        0.721        1.169
  5      569.223         556.700         yes       1.07310    0.796        0.912        0.530        0.754        1.125
  6      721.136         705.271         yes       1.03440    1.008        1.078        0.300        0.988        0.819
  7      739.826         723.550         yes       1.03141    1.034        1.099        0.279        1.016        0.785
  8      792.199         774.771         yes       1.02436    1.108        1.162        0.229        1.093        0.693
  9      817.986         799.990         yes       1.02151    1.144        1.193        0.207        1.131        0.651
 10      884.083         864.633         yes       1.01566    1.236        1.275        0.161        1.227        0.550
 11      957.823         936.751         yes       1.01100    1.339        1.369        0.121        1.333        0.452
 12      976.192         954.716         yes       1.01008    1.365        1.392        0.112        1.359        0.429
 13      978.545         957.017         yes       1.00997    1.368        1.395        0.111        1.362        0.427
 14     1004.408         982.311         yes       1.00881    1.404        1.429        0.100        1.399        0.397
 15     1029.466        1006.818         yes       1.00782    1.439        1.462        0.091        1.435        0.370
 16     1093.178        1069.128         yes       1.00578    1.528        1.546        0.071        1.525        0.307
 17     1104.493        1080.195         yes       1.00548    1.544        1.561        0.068        1.541        0.297
 18     1120.590        1095.937         yes       1.00507    1.567        1.583        0.063        1.564        0.283
 19     1156.786        1131.337         yes       1.00427    1.617        1.631        0.055        1.615        0.254
 20     1278.435        1250.310         yes       1.00240    1.787        1.796        0.034        1.786        0.174
 21     1294.159        1265.687         yes       1.00223    1.809        1.817        0.031        1.808        0.166
 22     1335.151        1305.777         yes       1.00184    1.867        1.874        0.027        1.866        0.145
 23     1407.264        1376.304         yes       1.00131    1.968        1.973        0.020        1.967        0.115
 24     1423.217        1391.906         yes       1.00121    1.990        1.995        0.019        1.989        0.109
 25     1502.064        1469.019         yes       1.00083    2.100        2.104        0.013        2.100        0.083
 26     1502.722        1469.662         yes       1.00083    2.101        2.104        0.013        2.100        0.083
 27     1592.578        1557.541         yes       1.00054    2.227        2.229        0.009        2.226        0.061
 28     1672.090        1635.304         yes       1.00037    2.338        2.340        0.007        2.338        0.046
 29     3024.050        2957.521         yes       1.00000    4.228        4.228        0.000        4.228        0.000
 30     3052.691        2985.532         yes       1.00000    4.268        4.268        0.000        4.268        0.000
 31     3128.649        3059.819         yes       1.00000    4.374        4.374        0.000        4.374        0.000
 32     3133.184        3064.253         yes       1.00000    4.381        4.381        0.000        4.381        0.000
 33     3214.764        3144.039         yes       1.00000    4.495        4.495        0.000        4.495        0.000
 34     3222.999        3152.093         yes       1.00000    4.506        4.506        0.000        4.506        0.000
 35     3239.141        3167.880         yes       1.00000    4.529        4.529        0.000        4.529        0.000
 36     3247.510        3176.064         yes       1.00000    4.540        4.540        0.000        4.540        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   4.94928       The ln(Q)    1.59924
    H vibration       76.50190   (kcal/mol)    320.08394     (kJ/mol)         0.12191343    (hartree)
    U vibration       76.50190   (kcal/mol)    320.08394     (kJ/mol)         0.12191343    (hartree)
           ZPE        74.77855   (kcal/mol)    312.87346     (kJ/mol)         0.11916710    (hartree)
    S vibration        8.95816  (cal/mol*K)     37.48093    (J/mol*K)         0.00001428  (hartree/K)
   Cv vibration       15.33487  (cal/mol*K)     64.16109    (J/mol*K)         0.00002444  (hartree/K)
    G vibration       73.83102   (kcal/mol)    308.90901     (kJ/mol)         0.11765712    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total      14745144721832.70898       The ln(Q)   35.90592
        H total       78.87184   (kcal/mol)    329.99978     (kJ/mol)         0.12569017    (hartree)
        U total       78.27936   (kcal/mol)    327.52082     (kJ/mol)         0.12474598    (hartree)
       Cv total       21.29649  (cal/mol*K)     89.10451    (J/mol*K)         0.00003394  (hartree/K)
           ZPE        74.77855   (kcal/mol)    312.87346     (kJ/mol)         0.11916710    (hartree)
        S total       73.98491  (cal/mol*K)    309.55285    (J/mol*K)         0.00011790  (hartree/K)
        G total       57.40573   (kcal/mol)    240.18556     (kJ/mol)         0.09148177    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.12474598 (hartree)
                       Thermal correction to Enthalpy :   0.12569017 
              Thermal correction to Gibbs Free Energy :   0.09053758 (hartree)
              ZPE correction to the Electronic Energy :   0.11916710 (hartree)


