The thermochemical analysis of the Molecule:                    C4H10

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000       0.0000000000       0.0000000000       0.3739980000
  H     1    1.00782       0.0000000000       0.0000000000       1.4694520000
  C     6   12.00000       0.0000000000       1.4516600000      -0.0955970000
  C     6   12.00000      -1.2571740000      -0.7258300000      -0.0955970000
  C     6   12.00000       1.2571740000      -0.7258300000      -0.0955970000
  H     1    1.00782       0.0000000000       1.5014760000      -1.1884150000
  H     1    1.00782      -0.8834440000       1.9846720000       0.2620930000
  H     1    1.00782       0.8834440000       1.9846720000       0.2620930000
  H     1    1.00782      -1.3003160000      -0.7507380000      -1.1884150000
  H     1    1.00782      -1.2770550000      -1.7574210000       0.2620930000
  H     1    1.00782      -2.1604980000      -0.2272520000       0.2620930000
  H     1    1.00782       1.3003160000      -0.7507380000      -1.1884150000
  H     1    1.00782       2.1604980000      -0.2272520000       0.2620930000
  H     1    1.00782       1.2770550000      -1.7574210000       0.2620930000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           3
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          36
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
         -0.00000000     -0.00000003      0.00893888

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x        64.47335         0.00000        -0.00000
    y         0.00000        64.47332         0.00000
    z        -0.00000         0.00000       111.21754

              Principal moments of inertia (amu*A**2): 
              64.47335000         111.21754000          64.47332000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation               17313.64613       The ln(Q)    9.75925

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       22.37446  (cal/mol*K)     93.61473    (J/mol*K)         0.00003566  (hartree/K)
  G rotation       -5.78222   (kcal/mol)    -24.19279     (kJ/mol)        -0.00921454    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    58.07825   amu

              *****      Translation thermodynamic functions     ******

  Q translation            17397046.55131       The ln(Q)   16.67181
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       38.09835  (cal/mol*K)    159.40349    (J/mol*K)         0.00006071  (hartree/K)
  G translation       -9.87781   (kcal/mol)    -41.32875     (kJ/mol)        -0.01574128    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   36
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   36


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      212.611         207.934         yes       1.57884    0.297        0.641        2.062        0.027        1.829
  2      264.717         258.894         yes       1.40192    0.370        0.668        1.669        0.170        1.748
  3      264.718         258.894         yes       1.40192    0.370        0.668        1.669        0.170        1.748
  4      373.277         365.065         yes       1.20737    0.522        0.738        1.100        0.410        1.544
  5      373.416         365.201         yes       1.20721    0.522        0.738        1.100        0.411        1.544
  6      440.091         430.409         yes       1.14325    0.615        0.792        0.857        0.536        1.404
  7      813.777         795.874         yes       1.02195    1.138        1.188        0.211        1.125        0.658
  8      935.947         915.357         yes       1.01222    1.309        1.341        0.131        1.301        0.479
  9      936.119         915.524         yes       1.01221    1.309        1.341        0.131        1.302        0.479
 10      965.536         944.294         yes       1.01061    1.350        1.379        0.117        1.344        0.442
 11      988.060         966.322         yes       1.00953    1.381        1.408        0.107        1.376        0.416
 12      988.179         966.439         yes       1.00952    1.382        1.408        0.107        1.376        0.415
 13     1205.499        1178.978         yes       1.00339    1.685        1.697        0.045        1.683        0.219
 14     1205.520        1178.998         yes       1.00339    1.685        1.697        0.045        1.683        0.219
 15     1218.766        1191.953         yes       1.00319    1.704        1.715        0.043        1.702        0.210
 16     1369.445        1339.317         yes       1.00156    1.915        1.921        0.023        1.914        0.130
 17     1369.581        1339.450         yes       1.00156    1.915        1.921        0.023        1.914        0.130
 18     1410.211        1379.186         yes       1.00129    1.972        1.977        0.020        1.971        0.114
 19     1410.214        1379.189         yes       1.00129    1.972        1.977        0.020        1.971        0.114
 20     1434.482        1402.923         yes       1.00115    2.006        2.010        0.018        2.005        0.105
 21     1485.408        1452.729         yes       1.00090    2.077        2.081        0.014        2.076        0.088
 22     1491.749        1458.930         yes       1.00088    2.086        2.089        0.014        2.085        0.086
 23     1491.758        1458.940         yes       1.00088    2.086        2.089        0.014        2.085        0.086
 24     1510.666        1477.431         yes       1.00080    2.112        2.115        0.013        2.112        0.081
 25     1510.677        1477.442         yes       1.00080    2.112        2.115        0.013        2.112        0.081
 26     1518.682        1485.271         yes       1.00077    2.123        2.127        0.013        2.123        0.079
 27     3034.204        2967.451         yes       1.00000    4.242        4.242        0.000        4.242        0.000
 28     3036.595        2969.790         yes       1.00000    4.246        4.246        0.000        4.246        0.000
 29     3036.595        2969.790         yes       1.00000    4.246        4.246        0.000        4.246        0.000
 30     3042.101        2975.175         yes       1.00000    4.253        4.253        0.000        4.253        0.000
 31     3106.072        3037.738         yes       1.00000    4.343        4.343        0.000        4.343        0.000
 32     3106.072        3037.738         yes       1.00000    4.343        4.343        0.000        4.343        0.000
 33     3114.914        3046.386         yes       1.00000    4.355        4.355        0.000        4.355        0.000
 34     3117.313        3048.732         yes       1.00000    4.358        4.358        0.000        4.358        0.000
 35     3121.076        3052.413         yes       1.00000    4.364        4.364        0.000        4.364        0.000
 36     3121.076        3052.413         yes       1.00000    4.364        4.364        0.000        4.364        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   5.69932       The ln(Q)    1.74035
    H vibration       82.95116   (kcal/mol)    347.06764     (kJ/mol)         0.13219096    (hartree)
    U vibration       82.95116   (kcal/mol)    347.06764     (kJ/mol)         0.13219096    (hartree)
           ZPE        81.12615   (kcal/mol)    339.43182     (kJ/mol)         0.12928264    (hartree)
    S vibration        9.57952  (cal/mol*K)     40.08072    (J/mol*K)         0.00001527  (hartree/K)
   Cv vibration       14.44947  (cal/mol*K)     60.45659    (J/mol*K)         0.00002303  (hartree/K)
    G vibration       80.09502   (kcal/mol)    335.11757     (kJ/mol)         0.12763943    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total       1716670985231.83032       The ln(Q)   35.08397
        H total       85.32110   (kcal/mol)    356.98348     (kJ/mol)         0.13596770    (hartree)
        U total       84.72861   (kcal/mol)    354.50452     (kJ/mol)         0.13502352    (hartree)
       Cv total       20.41109  (cal/mol*K)     85.40001    (J/mol*K)         0.00003253  (hartree/K)
           ZPE        81.12615   (kcal/mol)    339.43182     (kJ/mol)         0.12928264    (hartree)
        S total       70.05233  (cal/mol*K)    293.09894    (J/mol*K)         0.00011164  (hartree/K)
        G total       65.02748   (kcal/mol)    272.07499     (kJ/mol)         0.10362780    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.13502352 (hartree)
                       Thermal correction to Enthalpy :   0.13596770 
              Thermal correction to Gibbs Free Energy :   0.10268361 (hartree)
              ZPE correction to the Electronic Energy :   0.12928264 (hartree)


