The thermochemical analysis of the Molecule:                     C2H4

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000       0.0000000000       0.0000000000       0.6608610000
  C     6   12.00000       0.0000000000       0.0000000000      -0.6608610000
  H     1    1.00782       0.0000000000       0.9225810000       1.2292620000
  H     1    1.00782       0.0000000000      -0.9225810000       1.2292620000
  H     1    1.00782       0.0000000000       0.9225810000      -1.2292620000
  H     1    1.00782       0.0000000000      -0.9225810000      -1.2292620000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           4
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          12
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
          0.00000000      0.00000000      0.00000000

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x        20.00460         0.00000         0.00000
    y         0.00000        16.57333         0.00000
    z         0.00000         0.00000         3.43126

              Principal moments of inertia (amu*A**2): 
              20.00460000          16.57333000           3.43126000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation                 644.13944       The ln(Q)    6.46792

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       15.83389  (cal/mol*K)     66.24901    (J/mol*K)         0.00002523  (hartree/K)
  G rotation       -3.83215   (kcal/mol)    -16.03370     (kJ/mol)        -0.00610691    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    28.03130   amu

              *****      Translation thermodynamic functions     ******

  Q translation             5833377.76472       The ln(Q)   15.57911
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       35.92692  (cal/mol*K)    150.31824    (J/mol*K)         0.00005725  (hartree/K)
  G translation       -9.23040   (kcal/mol)    -38.61998     (kJ/mol)        -0.01470956    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   12
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   12


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      843.055         824.508         yes       1.01906    1.179        1.224        0.188        1.168        0.611
  2      988.944         967.187         yes       1.00949    1.383        1.409        0.107        1.377        0.415
  3     1002.328         980.277         yes       1.00890    1.401        1.426        0.101        1.396        0.399
  4     1071.377        1047.807         yes       1.00641    1.498        1.517        0.077        1.494        0.328
  5     1249.324        1221.839         yes       1.00276    1.747        1.756        0.038        1.745        0.191
  6     1391.904        1361.282         yes       1.00141    1.946        1.952        0.021        1.945        0.121
  7     1478.499        1445.972         yes       1.00093    2.067        2.071        0.015        2.067        0.090
  8     1715.846        1678.098         yes       1.00030    2.399        2.400        0.006        2.399        0.040
  9     3148.948        3079.671         yes       1.00000    4.403        4.403        0.000        4.403        0.000
 10     3166.981        3097.307         yes       1.00000    4.428        4.428        0.000        4.428        0.000
 11     3227.954        3156.939         yes       1.00000    4.513        4.513        0.000        4.513        0.000
 12     3254.295        3182.701         yes       1.00000    4.550        4.550        0.000        4.550        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   1.05019       The ln(Q)    0.04897
    H vibration       31.64864   (kcal/mol)    132.41792     (kJ/mol)         0.05043528    (hartree)
    U vibration       31.64864   (kcal/mol)    132.41792     (kJ/mol)         0.05043528    (hartree)
           ZPE        31.51289   (kcal/mol)    131.84993     (kJ/mol)         0.05021894    (hartree)
    S vibration        0.55264  (cal/mol*K)      2.31223    (J/mol*K)         0.00000088  (hartree/K)
   Cv vibration        2.19503  (cal/mol*K)      9.18402    (J/mol*K)         0.00000350  (hartree/K)
    G vibration       31.48387   (kcal/mol)    131.72853     (kJ/mol)         0.05017270    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total          3946105133.40974       The ln(Q)   31.20719
        H total       34.01858   (kcal/mol)    142.33376     (kJ/mol)         0.05421202    (hartree)
        U total       33.42610   (kcal/mol)    139.85480     (kJ/mol)         0.05326783    (hartree)
       Cv total        8.15665  (cal/mol*K)     34.12744    (J/mol*K)         0.00001300  (hartree/K)
           ZPE        31.51289   (kcal/mol)    131.84993     (kJ/mol)         0.05021894    (hartree)
        S total       52.31345  (cal/mol*K)    218.87948    (J/mol*K)         0.00008337  (hartree/K)
        G total       19.01381   (kcal/mol)     79.55380     (kJ/mol)         0.03030042    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.05326783 (hartree)
                       Thermal correction to Enthalpy :   0.05421202 
              Thermal correction to Gibbs Free Energy :   0.02935623 (hartree)
              ZPE correction to the Electronic Energy :   0.05021894 (hartree)


