The thermochemical analysis of the Molecule:                     C4H8

  ---------------------------------------------------------------------------
        N      M                 x                  y                  z
  ---------------------------------------------------------------------------
  C     6   12.00000      -0.3463020000       0.4017580000       0.0000000000
  C     6   12.00000      -0.3463020000      -0.8955430000       0.7519710000
  C     6   12.00000      -0.3463020000      -0.8955430000      -0.7519710000
  H     1    1.00782      -1.2505970000      -1.1989920000       1.2619790000
  H     1    1.00782       0.5688690000      -1.1814820000       1.2550680000
  H     1    1.00782      -1.2505970000      -1.1989920000      -1.2619790000
  H     1    1.00782       0.5688690000      -1.1814820000      -1.2550680000
  H     1    1.00782      -1.2864030000       0.9416590000       0.0000000000
  C     6   12.00000       0.8797340000       1.2756730000       0.0000000000
  H     1    1.00782       1.7875500000       0.6676800000       0.0000000000
  H     1    1.00782       0.9086740000       1.9167690000       0.8837660000
  H     1    1.00782       0.9086740000       1.9167690000      -0.8837660000
  ---------------------------------------------------------------------------

   The external parameters for thermodynamic calculations:
  ---------------------------------------------------------------------------
                                  Pressure (atm):     1.00000
                            Temperature (Kelvin):   298.15000
                         Symmetry number (sigma):           1
               The frequencies scale coefficient:     0.97800
                          The frequencies number:          30
  ---------------------------------------------------------------------------

The internal rotation options have not been found
The hindered rotation will not be considered

   ==========  The reading of the input file has been finished ==========


  ===========================================================================
    The thermochemistry evaluation at 298.15 K and 1.0 atm
  ===========================================================================

      ******    Rotation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                        The approximation : Rigid rotor
  ---------------------------------------------------------------------------
      The coordinates of the center of mass: 
              x               y               z
         -0.01690167     -0.01206856     -0.00000000

         The non-diagonalized matrix moments of inertia (amu*A**2): 
                 x               y               z
    x        76.69505       -24.38948         0.00000
    y       -24.38948        45.47615        -0.00000
    z         0.00000        -0.00000        79.11018

              Principal moments of inertia (amu*A**2): 
              90.04249000          32.12870000          79.11018000

               The molecule was found to be non-linear.

               *****     Rotation thermodynamic functions     *****

  Q rotation               36545.13326       The ln(Q)   10.50630

  H rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
  U rotation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv rotation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S rotation       23.85901  (cal/mol*K)     99.82608    (J/mol*K)         0.00003802  (hartree/K)
  G rotation       -6.22483   (kcal/mol)    -26.04471     (kJ/mol)        -0.00991990    (hartree)


             *****     Translation of a molecule as a whole     *****

  ---------------------------------------------------------------------------
                         The approximation : Ideal gas 
  ---------------------------------------------------------------------------
                         The molecular mass:    56.06260   amu

              *****      Translation thermodynamic functions     ******

  Q translation            16499283.89863       The ln(Q)   16.61883
  H translation        1.48121   (kcal/mol)      6.19740     (kJ/mol)         0.00236046    (hartree)
  U translation        0.88873   (kcal/mol)      3.71844     (kJ/mol)         0.00141628    (hartree)
 Cv translation        2.98081  (cal/mol*K)     12.47171    (J/mol*K)         0.00000475  (hartree/K)
  S translation       37.99306  (cal/mol*K)    158.96297    (J/mol*K)         0.00006055  (hartree/K)
  G translation       -9.84642   (kcal/mol)    -41.19741     (kJ/mol)        -0.01569125    (hartree)


                *****      Molecular vibrations     *****

  ---------------------------------------------------------------------------
                         The approximation : harmonic oscillator
  ---------------------------------------------------------------------------
                            The number of frequencies:   30
                  The number of imaginary frequencies:    0 (no TD analysis)
        The number of frequencies used in TD analysis:   30


   N  Freq (cm-1)     Freq (cm-1)        TD?          Q        ZPE          H            S            G           Cv
                         Scaled                              kcal/mol    kcal/mol     cal/mol*K     kcal/mol    cal/mol*K
  1      223.707         218.786         yes       1.53355    0.313        0.647        1.969        0.059        1.812
  2      349.128         341.447         yes       1.23837    0.488        0.721        1.205        0.361        1.593
  3      374.042         365.813         yes       1.20647    0.523        0.739        1.097        0.412        1.543
  4      781.306         764.117         yes       1.02568    1.092        1.148        0.239        1.077        0.712
  5      807.484         789.719         yes       1.02263    1.129        1.180        0.216        1.116        0.668
  6      833.030         814.703         yes       1.02001    1.165        1.211        0.196        1.153        0.627
  7      884.300         864.846         yes       1.01564    1.236        1.275        0.161        1.227        0.550
  8      952.327         931.376         yes       1.01130    1.331        1.362        0.123        1.325        0.459
  9     1008.757         986.564         yes       1.00863    1.410        1.435        0.099        1.405        0.392
 10     1065.981        1042.529         yes       1.00658    1.490        1.510        0.079        1.486        0.333
 11     1084.465        1060.607         yes       1.00602    1.516        1.534        0.073        1.513        0.315
 12     1116.850        1092.279         yes       1.00517    1.561        1.578        0.064        1.558        0.287
 13     1155.089        1129.677         yes       1.00431    1.615        1.629        0.055        1.612        0.256
 14     1203.892        1177.407         yes       1.00342    1.683        1.695        0.045        1.681        0.220
 15     1219.965        1193.125         yes       1.00317    1.706        1.716        0.043        1.704        0.209
 16     1241.238        1213.931         yes       1.00287    1.735        1.745        0.039        1.734        0.196
 17     1401.258        1370.430         yes       1.00134    1.959        1.964        0.020        1.958        0.117
 18     1436.366        1404.766         yes       1.00114    2.008        2.013        0.018        2.008        0.104
 19     1476.312        1443.833         yes       1.00094    2.064        2.068        0.015        2.064        0.091
 20     1496.157        1463.241         yes       1.00086    2.092        2.095        0.014        2.091        0.085
 21     1505.534        1472.412         yes       1.00082    2.105        2.108        0.013        2.104        0.082
 22     1525.904        1492.334         yes       1.00075    2.133        2.137        0.012        2.133        0.077
 23     3041.968        2975.044         yes       1.00000    4.253        4.253        0.000        4.253        0.000
 24     3112.837        3044.355         yes       1.00000    4.352        4.352        0.000        4.352        0.000
 25     3113.387        3044.892         yes       1.00000    4.353        4.353        0.000        4.353        0.000
 26     3146.738        3077.509         yes       1.00000    4.400        4.400        0.000        4.400        0.000
 27     3152.528        3083.172         yes       1.00000    4.408        4.408        0.000        4.408        0.000
 28     3167.921        3098.227         yes       1.00000    4.429        4.429        0.000        4.429        0.000
 29     3227.671        3156.662         yes       1.00000    4.513        4.513        0.000        4.513        0.000
 30     3242.280        3170.950         yes       1.00000    4.533        4.533        0.000        4.533        0.000

                   *****     Vibration thermodynamic functions     ******

    Q vibration                   2.63602       The ln(Q)    0.96927
    H vibration       68.75044   (kcal/mol)    287.65184     (kJ/mol)         0.10956070    (hartree)
    U vibration       68.75044   (kcal/mol)    287.65184     (kJ/mol)         0.10956070    (hartree)
           ZPE        67.59695   (kcal/mol)    282.82564     (kJ/mol)         0.10772250    (hartree)
    S vibration        5.79497  (cal/mol*K)     24.24614    (J/mol*K)         0.00000923  (hartree/K)
   Cv vibration       10.72853  (cal/mol*K)     44.88817    (J/mol*K)         0.00001710  (hartree/K)
    G vibration       67.02267   (kcal/mol)    280.42285     (kJ/mol)         0.10680733    (hartree)


                       *****      Electronic part     *****     

  ---------------------------------------------------------------------------
         The approximation : Consider just multiplicity
  ---------------------------------------------------------------------------
                             The molecule multiplicity           1 
                      *****     Electronic thermodynamic functions     *****    

   Q electronic                   1.00000       The ln(Q)    0.00000
   H electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
   U electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)
  Cv electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   S electronic        0.00000  (cal/mol*K)      0.00000    (J/mol*K)         0.00000000  (hartree/K)
   G electronic        0.00000   (kcal/mol)      0.00000     (kJ/mol)         0.00000000    (hartree)


                     *****     Final values for TD functions (no internal rotation)     *****

        Q total       1589440095245.02661       The ln(Q)   34.20693
        H total       71.12038   (kcal/mol)    297.56768     (kJ/mol)         0.11333744    (hartree)
        U total       70.52790   (kcal/mol)    295.08872     (kJ/mol)         0.11239325    (hartree)
       Cv total       16.69015  (cal/mol*K)     69.83159    (J/mol*K)         0.00002660  (hartree/K)
           ZPE        67.59695   (kcal/mol)    282.82564     (kJ/mol)         0.10772250    (hartree)
        S total       67.64703  (cal/mol*K)    283.03518    (J/mol*K)         0.00010780  (hartree/K)
        G total       51.54390   (kcal/mol)    215.65970     (kJ/mol)         0.08214037    (hartree)


                    *****     Final corrections for TD functions (no internal rotation)     *****

                         Thermal correction to Energy :   0.11239325 (hartree)
                       Thermal correction to Enthalpy :   0.11333744 
              Thermal correction to Gibbs Free Energy :   0.08119618 (hartree)
              ZPE correction to the Electronic Energy :   0.10772250 (hartree)


